### ISSUE TITLE
subscribeToMore: Unhandled GraphQL subscription error: Cannot read property 'subscribe' of  undefined

### ISSUE THREAD

**Issue by n1ru4l** [apollographql/subscriptions-transport-ws#101]
I am using the following setup with react-native:
```
"subscriptions-transport-ws": "^0.5.5-alpha.0"
"apollo-client": "1.0.0-rc.6"
"react-apollo": "1.0.0-rc.3"
```

When calling `subscribeToMore` I will always get the following error:
```
Cannot read property 'subscribe' of  undefined
```

Also the apolloClient instance has no method called `subscribeToMore`, so the example in the readme does not work.

**Comment by n1ru4l** [comment]
I solved it it was actually a server side error due to undefined pubsub -.-

**Comment by bcf3ah** [comment]
How did you fix the undefined pubsub problem? I'm having the same issue, but I can't figure out why my imported pubsub instance is undefined

**Comment by devarashetty** [comment]
check the name `pubsub`properly
