### ISSUE TITLE
Middleware for connection params

### ISSUE THREAD

**Issue by marktani** [apollographql/subscriptions-transport-ws#102]
Is there a middleware for connection params, similar to the one used for `apollo-client`? Typically you don't have the authentication token ready when setting up the subscription client. So if you want to require a specific token as the authorization header that the user can only obtain after logging in, how could we set that up?

**Comment by erossv** [comment]
Have you looked at the PR #78? This might be what you are waiting for.

**Comment by dotansimha** [comment]
This feature is already available in 0.7.0, see: https://github.com/apollographql/subscriptions-transport-ws/issues/113 https://github.com/apollographql/subscriptions-transport-ws/pull/78
