### ISSUE TITLE
Publish to single client

### ISSUE THREAD

**Issue by bmsantos** [apollographql/subscriptions-transport-ws#103]
Is it possible to publish the result of a subscription to a single client matching a defined criteria?

For example, say a user has subscribed to user account modifications and I want the WS clients/connections for this user to be notified every time a change to his account occurs.

**Comment by NeoPhi** [comment]
Yes it is possible. You would defined this logic in the `filter` function for the specific message. https://github.com/apollographql/graphql-subscriptions#example-usage
