### ISSUE TITLE
Using `printer` from `graphql-tag` is deprecated

### ISSUE THREAD

**Issue by dacz** [apollographql/subscriptions-transport-ws#104]
When running node graphql server i got:

```
Warning - the `printer` exports from `graphql-tag` will be removed in the next major version.
See https://github.com/apollographql/graphql-tag/issues/54 for more information.
```

Within the file `subscriptions-transport-ws/dist/helpres.js` is used this `printer` and therefore I got the warning.

This issue is mentioned #54 but still there is the issue. I have version "1.3.2" of `graphql-tag`.

Seems like subscriptions-transport-ws should upgrade deps?

**Comment by DxCx** [comment]
Closed by #98 :D
