### ISSUE TITLE
operation name is undefined in `onSubscribe` hook

### ISSUE THREAD

**Issue by thebigredgeek** [apollographql/subscriptions-transport-ws#106]
Are the docs out of date?

**Comment by DxCx** [comment]
`operationName` is something that sent from the client with the request,
if the client did not send the operationName it won't be there..

**Comment by thebigredgeek** [comment]
Ah weird.  I assuming `operationName` -> name of subscription?  Any way you could elaborate on what that is for me? :D

**Comment by Urigo** [comment]
@thebigredgeek 

```graphql
subscription mySubscription {  # <-- this is the operation name 
      newData {
           id
      }
}
```

Operation name is a way to name the operation on the client side. For example, `apollo-client` uses the operation name as a key for the store state, so you can do thing like that with Apollo client:

```js
const client = new ApolloClient(...);
client.mutate({
     mutation: gql`...`,
     variables: { ... },
     updateQueries: {
         mySubscription: (prev, { data: { mutationResult }}) => {
               // modify mySubscription store here, using the mutation result

               return prev;
         },
     },
});
```

**Comment by Urigo** [comment]
@thebigredgeek I think we can close this one :)

**Comment by thebigredgeek** [comment]
Yup!  Thanks
