### ISSUE TITLE
Question: Why two different graphql endpoints?

### ISSUE THREAD

**Issue by smysnk** [apollographql/subscriptions-transport-ws#109]
Trying to understand the endpoint model better, so sorry if this question seems silly.

Why is the subscriptions/websocket endpoint distinctly different from regular http graphql endpoint?  Would it be possible to target strictly websocket endpoint for all graphql queries? Where is the decision made to use one endpoint type over another?

**Comment by DxCx** [comment]
hey @smysnk 
there is a work done for a while now in order to push everything through 1 websocket,
latest work atm is #108 PR :)

**Comment by smysnk** [comment]
@DxCx Understood, thanks for the info!
