### ISSUE TITLE
[FEATURE REQUEST] `connectionParams` accept async function or a function return promise.

### ISSUE THREAD

**Issue by giautm** [apollographql/subscriptions-transport-ws#113]
I want to fetch authToken from local storage any time socket init. But i can't do it right now, because it dont accept a function. This is what i want to write:

```
const wsClient = new SubscriptionClient(GRAPHQL_SUBSCRIPTIONS, {
  reconnect: true,
  connectionParams: async () => {
    const authToken = await LocalStorage.getItem(ID_TOKEN);
    return {
      authToken,
    };
  },
});
```

**Comment by giautm** [comment]
Or

```
const wsClient = new SubscriptionClient(GRAPHQL_SUBSCRIPTIONS, {
  reconnect: true,
  connectionParams: {
    authToken: () => LocalStorage.getItem(ID_TOKEN),
  },
});
```

**Comment by giautm** [comment]
Look like there are some Issues related to this issue. And a PR is open for resolve, so i will close this issue. ^_^

https://github.com/apollographql/subscriptions-transport-ws/issues/102
https://github.com/apollographql/subscriptions-transport-ws/pull/78

**Comment by Access2emma** [comment]
I also have the same issue with using await with AsyncStorage on React Native. I always get undefined as token on the onConnect hook on the server.  If i don't use await AsyncStorage, i'll wrong value for the token. How can i handle this on Apollo GraphQL V2.1

**Comment by Almaju** [comment]
To make it simpler for folks:
```js
const wsLink = new WebSocketLink({
  uri: wsUri,
  options: {
    reconnect: true,
  },
});
wsLink.subscriptionClient.use([{
  async applyMiddleware(options, next) {
    const token = await getLoginToken();
    options.context = { token };
    next();
  },
}]);
```
