### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by phoenix741** [apollographql/subscriptions-transport-ws#114]
Hi,

I use the last version of nodejs, and don't have typescript on my project (and don't want to have it). When i install the package i have the following error :

npm ERR! 404 no such package available : @types/ws
npm ERR! 404 
npm ERR! 404  '@types/ws' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'subscriptions-transport-ws'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Is the @types/ws is a real dependencies of this project, should i have typescript to use this library ?

Thanks

**Comment by NeoPhi** [comment]
What is the output of `node --version` and `npm --version`?

**Comment by phoenix741** [comment]
node --version =》 v7.9.0npm --version =》4.2.0Ulrich Van Den HekkeLe 3 mai 2017 14:10, Daniel Rinehart <notifications@github.com> a écrit :What is the output of node --version and npm --version?

**Comment by NeoPhi** [comment]
I'm unable to reproduce the problem using that version of node and npm. Do you use any kind of npm proxy or custom repository that doesn't understand npm scopes? The package in question can be found at: https://www.npmjs.com/package/@types/ws

To answer your other question, TypeScript is not required to use subscriptions-transport-ws, they are included to aid in those developing with TypeScript.

**Comment by phoenix741** [comment]
Yes, 

The problem is reproduced only when using Sinopia as a proxy for npm package

**Comment by NeoPhi** [comment]
Looks like some people have reported success using: https://github.com/verdaccio/verdaccio
