### ISSUE TITLE
0.6.0 is not convenient to use with Webpack due to new packaging

### ISSUE THREAD

**Issue by vlasenko** [apollographql/subscriptions-transport-ws#118]
The module format for client-side bundle has changed from CommonJS in 0.5.x to global var in 0.6.0.
The webpack is using `package.json` `browser` field by default, which is `dist/client.js` right now. `dist/client.js` is a global var library in `0.6.0`. 

Maybe `libraryTarget: 'umd'` should be used instead in `unpkg-webpack.config.js` to make client-side bundle working both as global var and as CommonJS module suitable for using with bundlers such as webpack?

Global var module style for client-side bundle will work without hacks involved only with `<script>` tags in web browser. But if one uses `webpack` bundler (maybe it is applicable for other bundlers as well), by default it processes `browser` field in package.json and hence attempts to use client-side bundle when you `require('subscritption-transport-ws')`. In `0.5.x` everything was fine with `webpack`, because client-side bundle had CommonJS module style. But in `0.6.0` module style changed to global var and now you need to require this module in rather convoluted way:
```
  require('script!subscriptions-transport-ws');
  const SubscriptionClient = SubscriptionsTransportWs.SubscriptionClient;
```

I propose to not use global var, but rather use the module style for client-side bundle that works BOTH with `<script>` tag and with bundlers. I think `UMD` module style is compatible with any usage scenario.

**Comment by Urigo** [comment]
@vlasenko 
The `unpkg-webpack` has nothing to to with the generated file `dist/client.js` - it's another bundle at all (which use the global scope instead of import), use it only if you are using unpkg service to fetch your libraries. 

The file `dist/client.js` exists and exports `SubscriptionsClient` as regular export, the last line of the generated file is:
```
exports.SubscriptionClient = SubscriptionClient;
```

Which modules loader do you use in your `webpack` config?

**Comment by vlasenko** [comment]
@Urigo Sorry, please disregard. I've used incorrect import line. I should have used ES6 named imports with `0.6.0` as specified in README.md.

**Comment by Urigo** [comment]
thanks for the update @vlasenko !
