### ISSUE TITLE
Client connection events

### ISSUE THREAD

**Issue by mistic** [apollographql/subscriptions-transport-ws#136]
Guys ( @Urigo @DxCx @helfer @dotansimha @NeoPhi  ) this issue is to allow us think about the events we are throwing during the connection handshake between the client and the server. At the moment we are only emitting a single event called `connect` or `reconnect` when the `onopen` callback runs. In my opinion we should do this:

- emit a `connecting` or `reconnecting` event (according it is a connect or reconnect situation) when the `onopen` callback runs
- emit a `connected` or `reconnected` event when we receive the `GQL_CONNECTION_ACK`.

What do u think?

**Comment by dotansimha** [comment]
Sounds good @mistic .

**Comment by Urigo** [comment]
@mistic would you want to open a PR?
We might even get this in for the next release

**Comment by mistic** [comment]
@Urigo @dotansimha I'll open a PR for this. I'm just finishing something even more important so I can open another PR before this one.

**Comment by mistic** [comment]
@Urigo @dotansimha It's done. Please check #139
