### ISSUE TITLE
Object.assign is not defined for older browsers (e.g. IE 11)

### ISSUE THREAD

**Issue by pencilcheck** [apollographql/subscriptions-transport-ws#141]
https://github.com/apollographql/subscriptions-transport-ws/blob/0e81e9e45929db2f4d2699cf34229fb4cb2144e8/src/helpers.ts#L16

Getting error when running inside older browsers using the library.

**Comment by mistic** [comment]
Maybe we can move from `Object.assign` to the `lodash.cloneDeep`. What do u think @DxCx @Urigo @NeoPhi ?

**Comment by NeoPhi** [comment]
We should pull in an use the 'object-assign' library. This is the one that react-apollo uses.

**Comment by mistic** [comment]
Lol ( @NeoPhi @DxCx  ) I was almost sleeping when I wrote this! What I meant was `lodash.assign` and not cloneDeep. As react-apollo already uses the 'object-assign' maybe we can also use it.
