### ISSUE TITLE
It's not possible to install this module from master branch

### ISSUE THREAD

**Issue by mistic** [apollographql/subscriptions-transport-ws#147]
Hi guys ( @Urigo @DxCx @helfer @dotansimha @NeoPhi ),

I tried to install this package as a dependency in a personal project from the master branch `apollographql/subscriptions-transport-ws#master` but it completely fails. I've already spotted a lot of things that are blocking this feature. What u think about that?

**Comment by helfer** [comment]
Hey @mistic! If there are some reasonable changes that will allow us to install the package directly from github, then I think it's definitely worth it! What are the blockers right now?

**Comment by dotansimha** [comment]
@mistic 
I guess that one of the issues was the fact that `graphql` was a direct dependency (now it's a dev dependency and a peer dependency). 
I saw your fork with some attempts: https://github.com/mistic/subscriptions-transport-ws/commits/test , did you managed to fix this issue?

**Comment by mistic** [comment]
@dotansimha not yet. And u? Were u able to fix this? I'll give some more tries today

**Comment by mistic** [comment]
I've opened a PR solving this problem #208 ].
