### ISSUE TITLE
Can't resolve 'graphql/language/printer' in '...\node_modules\subscriptions-transport-ws\dist'

### ISSUE THREAD

**Issue by AlexLeung** [apollographql/subscriptions-transport-ws#160]
I'm getting this error when trying to webpack an app which uses the React Apollo client. I currently have version ^0.7.0 of subscriptions-transport-ws

**Comment by AlexLeung** [comment]
Nevermind. I had actually forgotten to install the graphql peer module.

**Comment by raeesaa** [comment]
`graphql` should have been added as a dependency in `subscriptions-transport-ws` so that it gets installed automatically.

**Comment by NeoPhi** [comment]
`graphql` is listed in `peerDependencies` so that you may chose which version of the library you wish to use. Both `npm` and `yarn` warn about missing peer dependencies.
