### ISSUE TITLE
Add Afterware capability

### ISSUE THREAD

**Issue by NeoPhi** [apollographql/subscriptions-transport-ws#168]
Similar to the standard networking client, for a complete WebSocket client, it would be handy to have [Afterware support](http://dev.apollodata.com/core/network.html#networkInterfaceAfterware). The use case is checking for a standard set of error responses that should be globally handled instead of needing to attach per request handlers.

**Comment by Urigo** [comment]
@NeoPhi sounds good.  Do you think you could PR that?
Would be cool to add it before 1.0

**Comment by helfer** [comment]
@NeoPhi are you talking about transport specific errors, or GraphQL errors? In the case of errors that are not transport-specific, I think those should be handled outside, for example in a custom fetcher module in the architecture that @evanshauser is working on.

**Comment by NeoPhi** [comment]
Sounds like waiting for the new transport mechanisms will provide us the most flexibility.
