### ISSUE TITLE
addGraphQLSubscriptions deprecation warning

### ISSUE THREAD

**Issue by akaNightmare** [apollographql/subscriptions-transport-ws#169]
I see `This method becomes deprecated in the new package graphql-transport-ws. Start using the GraphQLTransportWSClient to make queries, mutations and subscriptions over websockets.` deprecation warning, but I can't find an example how to use GraphQLTransportWSClient.
Can you add some example to README.md for GraphQLTransportWSClient?

Thanks.

**Comment by Japskua** [comment]
Noticed the same thing.

**Comment by ArnaudRinquin** [comment]
In the [project readme](https://github.com/apollographql/subscriptions-transport-ws#full-websocket-transport).

**Comment by akaNightmare** [comment]
@ArnaudRinquin But I'm using Hybrid https://github.com/apollographql/subscriptions-transport-ws#hybrid-websocket-transport, and it says: use addGraphQLSubscriptions.

**Comment by mattiasewers** [comment]
Also using the hybrid implementation and would like to know what to use instead.

**Comment by ArnaudRinquin** [comment]
I might be wrong but I guess that's the whole idea of using an hybrid network that is deprecated.

**Comment by mistic** [comment]
This warning is to notify the users that will be released in the next weeks a new transport package called graphql-transport-ws where the method `addGraphQlSubscriptions` will be removed. The 0.7.x version of the current package was built with retro compatibility in mind and it is the last version because our idea is to move into a new independent transport package with full webscoket support and without backward compatibility.

**Comment by scf4** [comment]
@mistic Could you link me to more information about why you're choosing to go in this direction?

**Comment by dotansimha** [comment]
@mistic @Urigo

I think that the implementation should allow using hybrid network interfaces, and ` addGraphQlSubscriptions` should not be deprecated at the moment, since we do not have other alternative for creating hybrid interfaces.

**Comment by mnpenner** [comment]
@ArnaudRinquin I don't see any reference to `GraphQLTransportWSClient` in the README. [Searching the code](https://github.com/apollographql/subscriptions-transport-ws/search?utf8=%E2%9C%93&q=GraphQLTransportWSClient&type=) only turns up the warning, no implementation. How are we supposed to use something that doesn't exist?

**Comment by dotansimha** [comment]
@mnpenner and everyone, 
`addGraphQLSubscriptions` will be deprecated in 1.0 of the transport, we will create a new hybrid network interface soon, but we have to wait because it will need to be a part of the new [apollo-fetcher](https://github.com/apollographql/apollo-fetcher) done by @helfer and @evanshauser.

The warning is a bit misleading because the new implementation isn't there yet.
Actually the `GraphQLTransportWSClient` is `SubscriptionClient` - it implements the interface of Apollo network interface, so you can use it directly as your network layer, or use regular HTTP interface for queries and mutations, and subscriptions with `addGraphQLSubscriptions`.

**Comment by jmatsushita** [comment]
> The warning is a bit misleading

Would you consider removing the warning since I assume many will try to understand why it's here only to realise that it can't be solved?

**Comment by Urigo** [comment]
you are all right :)
In the new `0.8` release I've changed the deprecation warning to be more understandable:
```
Notice that addGraphQLSubscriptions method will become deprecated in the new package graphql-transport-ws that will be released soon. Keep track for the new hybrid network release here: https://github.com/apollographql/subscriptions-transport-ws/issues/169
```
For those who wants to follow more closely on the exciting improvements happening on Apollo Client's network front, check it out here: https://github.com/apollographql/apollo-link/pull/6/files#diff-d3558ae69a848084cb7c6b40cf743177

**Comment by mnpenner** [comment]
Warnings that can't be fixed are just irritating. If it's not actionable, I don't think it should be displayed at all.

That said, the work you're doing looks great. A more readable version of the spec is [here](https://github.com/apollographql/apollo-link/blob/cdc376930aee6e119e4f840527d9d5f045097410/SPEC.md).

**Comment by farzd** [comment]
It worse if you're using react native 👎 
![screen shot 2017-08-23 at 14 02 20](https://user-images.githubusercontent.com/1423413/29617154-c2ca71ac-880b-11e7-86af-83e4782467de.png)

**Comment by scf4** [comment]
@farzd It doesn't show in production though, right?

**Comment by farzd** [comment]
@scf4  of course not but it interferes with dev and clogs up the logs and makes it difficult to do automated testing.

**Comment by scf4** [comment]
Oh absolutely.
@dotansimha any update on this, it's been 3 months?

**Comment by quadsurf** [comment]
also waiting for an update here... would love a React Native syntax example on how best to adopt only the new implementation, which i'm assuming is GraphQLTransportWSClient/SubscriptionClient

**Comment by quadsurf** [comment]
here's how i'm currently doing it, but 3 months later and i'm still getting that deprecated warning

`
import { AsyncStorage,Alert } from 'react-native'

// ENV VARS
import { PROJECT_ID } from 'react-native-dotenv'

// LIBS
import { SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws'
import { ApolloClient,createNetworkInterface } from 'react-apollo'

const networkInterface = createNetworkInterface({
  uri: `https://api.graph.cool/simple/v1/${PROJECT_ID}`,
  opts: {
    credentials: 'same-origin'
  }
})

const wsClient = new SubscriptionClient(`wss://subscriptions.us-west-2.graph.cool/v1/${PROJECT_ID}`, {
  reconnect: true,
  connectionParams: {
     authToken: AsyncStorage.getItem('token')
  }
})

const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
  networkInterface,
  wsClient
)

networkInterface.use([{
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {}
    }
    AsyncStorage.getItem('token').then(
          token => {
            if (token !== null) {
              req.options.headers['authorization'] = `Bearer ${token}`
            } else {
              req.options.headers['authorization'] = null
            }
            next()
          },
          failure => {
            Alert.alert('ERROR: ', failure.message)
            next()
          })
  }
}])

const client = new ApolloClient({
  networkInterface: networkInterfaceWithSubscriptions
})

export default client
`

**Comment by scf4** [comment]
**Fix:**

`yarn add add-graphql-subscriptions` 

(https://github.com/scf4/add-graphql-subscriptions)

And then:

```js
import { addGraphQLSubscriptions } from 'add-graphql-subscriptions';
```

instead of from `subscriptions-transport-ws`.

**Comment by bakumn** [comment]
how to subscriptions on  "subscriptions-transport-ws" version 0.9.0"?

**Comment by altschuler** [comment]
@bakumn 0.9.0 is very different from 0.8.x. You have to use Apollo Links instead of the previous networkInterface, which means you have to use Apollo Client 2, but that's not out of beta yet.

**Comment by chandlervdw** [comment]
@altschuler so I basically can't do subscriptions with the latest of `subscriptions-transport-ws` and `apollo-links` because Apollo Client 2 isn't released, correct? So, what versions of each do I need to be using to pull off subscriptions. Bleeding edge truly hurts.

**Comment by stubailo** [comment]
Hmmmmm looks like we should look into the release process and versioning here. Maybe it's possible to tag 0.9 as a "preview" release or similar, since there is definitely some confusion here right now.

**Comment by psamim** [comment]
The worst thing here was that `addGraphQLSubscriptions` is still in the README. It took me half an hour to find the commit mentioning this issue.

**Comment by eruby94** [comment]
I've said this on another issue, but this is particularly concerning since the "official" graphql how to refers to the implementation with addGraphQLSubscriptions. This can be found at https://www.howtographql.com/vue-apollo/8-subscriptions/

I've reported this to them so that they may update their docs for specific npm version

**Comment by kidchenko** [comment]
Please update the README because we are now in version 0.9.x and the README still using `addGraphQLSubscriptions`.

https://github.com/apollographql/subscriptions-transport-ws#hybrid-websocket-transport

`import {SubscriptionClient, addGraphQLSubscriptions} from 'subscriptions-transport-ws';`

**Comment by csillag** [comment]
So, currently, if I do exactly what the README file says, I get a deprecation warning.
This is _not_ how things are supposed to work - correct?

**Comment by hiei189** [comment]
I am not getting any warning. It simply does not exist. 
So, how do I do subscriptions with the stable realeses (react apollo 1.4.6)

**Comment by janzheng** [comment]
Came here from https://www.howtographql.com/vue-apollo/8-subscriptions/ as a complete Vue and Apollo newbie... any suggestions as to what the "right" way to do this is, without pinning to an old version?

**Comment by ksrb** [comment]
For future tumbleweeds from go to the links in https://github.com/howtographql/howtographql/issues/226#issuecomment-334991890:

> For anyone who might come across this in the future, I've taken a lot of these pain points and have tried to make a comprehensive guide for upgrading to Apollo 2.0 here, with an example app in Meteor here. Maybe that will help someone.

**Comment by jackgray** [comment]
Thank you for this post @ksrb. Spent a long time reading the docs in circles over this. Looking forward to updated docs :)
