### ISSUE TITLE
Typescript no longer compile : Generic type 'AsyncIterator<T, E>' requires 2 type argument(s)

### ISSUE THREAD

**Issue by mgrenier** [apollographql/subscriptions-transport-ws#175]
`subscriptions-transport-ws` no longer compile with Typescript. AsyncIterator from @types/async requires 2 type arguments.

I'm using `subscriptions-transport-ws@0.7.1`.

Had to manualy add the second type in `*.d.ts` files from `subscriptions-transport-ws` to make it work.

Similar to [this issue in graphql-subscriptions](https://github.com/apollographql/graphql-subscriptions/issues/77).

**Comment by dotansimha** [comment]
@mgrenier please provide the following:
- TypeScript compiler version
- Bundler type (webpack? angular cli?)
- tsconfig.json lib section

Thanks

**Comment by LarsKrogJensen** [comment]
I am seeing this as-well when upgrading from 0.5.4 to 0.7.x. My setup is:

typscript 2.3.4
webpack2
tscconfig 
"lib": [
      "es6",
      "es7",
      "dom"
    ]

**Comment by mgrenier** [comment]
```
typescript@2.3.4
webpack@2.6.0
tsconfig
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "commonjs",
    "target": "esnext",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ],
  "types": [
    "typePatches"
  ]
}

```

**Comment by bruce** [comment]
I'm also seeing this issue (including when using `esnext`).

**Comment by curtiswilkinson** [comment]
We're also experiencing this, thought I'd chip in the environment details as well

typescript@2.3.4
webpack@2.2.1
subscriptions-transport-ws@0.7.3

```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "commonjs",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "experimentalDecorators": true
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ],
  "exclude": [
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts",
    "node_modules"
  ],
  "types": [
    "typePatches"
  ]
}
```

**Comment by olaf89** [comment]
same issue, any workaround?

**Comment by curtiswilkinson** [comment]
I have a little hack that gets around this in place:
`"postInstall" : "rm - rf node_modules/@types/async ## hack until AsycIterator issues are resolved"`
In the scripts section of package.json to remove the definition upon install.

You'll also need to have `esnext` as a lib in your tsconfig to get the AsycIterator definition from there

Not the greatest thing in the world but it'll get you rolling

**Comment by dav-ell** [comment]
Note that `"postinstall"` in the scripts section of package.json may need to be all lowercase: https://docs.npmjs.com/misc/scripts

Snip of example `package.json`:
```
{
  "name": "projectname",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "postinstall": "..."
  }
}
```

**Comment by blocka** [comment]
@curtiswilkinson how does that help? postinstall of what?

**Comment by curtiswilkinson** [comment]
@blocka my example above has:

```
"postinstall" : "rm -rf node_modules/@types/async ## hack until AsycIterator issues are resolved"
```

@dav-ell left it out for brevity, because he was pointing out that I accidentally camelCased my original example. (thanks for noticing that, oops)

This removes the conflicting definitions that are in @types/async and only leaves the new AsyncIterator definition implemented in the latest version of TS.

**Comment by mistic** [comment]
@mgrenier can u please test if u still get the error using this as your tsconfig file:

```javascript
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "noImplicitAny": true,
    "rootDir": "./src",
    "outDir": "./build",
    "allowSyntheticDefaultImports": true,
    "removeComments": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "pretty": true,
    "declaration": true,
    "skipLibCheck": true,
    "lib": ["es6", "esnext"],
    "types": [
      "node"
    ]
  },
  "exclude": [
    "node_modules",
    "build"
  ]
}
```

**Comment by olaf89** [comment]
I have same issues, in version 0.8 as well 
Typescript 2.3.4

Generic type 'AsyncIterator<T, E>' requires 2 type argument(s).

**Comment by marklawlor** [comment]
@mistic Adding `skipLibCheck` would suppress the error, but not actually fix the underlying issue. It also opens the door for subtle Typescript bugs in people's projects.

To quote myself from the graphql-subscriptions issue

> I believe this issue is more related to the typings for the async package (which are included an optional dependency for graphql-client) DefinitelyTyped/DefinitelyTyped#16980
> 
> As of Typescript 2.3 AsyncIterator<T> (what graphql-subscriptions uses) is the correct syntax https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html

I recommend :+1: the @types/async issue (which is the package which introduces the conflicting AsyncIterator types) https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16980

**Comment by mistic** [comment]
@marklawlor you're right, my point wasn't to test with `skipLibCheck` but also testing to use 'types' key.

**Comment by goldenbearkin** [comment]
any progress for this thread? i am completely blocked by this error...  have tried @curtiswilkinson suggestion but still doesn't work.
