### ISSUE TITLE
Why it's not using GraphQLError for subscription errors?

### ISSUE THREAD

**Issue by ezsper** [apollographql/subscriptions-transport-ws#182]
In our GraphQL implementation we have custom errors, like `ClientError` and `InternalServerError` (witch extends the first one), where if the error thrown inside GraphQL is an instance of `ClientError` we show to the user the exactly message thrown, if the error is not, we redirect the error to `InternalServerError` with a default message and display the original error in the server console. Also, we have code for all of our custom errors to be mapped on the front-end. Some of these custom errors include `WrongCredentialError`, `InvalidEmailError`, `InvalidOAuthRedirectURIError`, etc. So error manipulation is important for us to have on subscriptions as well, specially for `subscribe` method.

![error graphql](https://user-images.githubusercontent.com/798804/27254145-a18809e2-5358-11e7-9da0-673075cadae1.PNG)

This implementation should consider implementing a method like `formatError` and use the original `GraphQLError` to handle it.

To make this possible in the current version we are hooking it with `sendMessage` and `sendError`, but it shouldn't be like that.

If this become available the GraphiQL might need to implement this as well, as it only show texts errors.
![graphiql error](https://user-images.githubusercontent.com/798804/27254378-6476c0b6-535d-11e7-97f1-3e3de47c103c.PNG)

![subscribe](https://user-images.githubusercontent.com/798804/27254473-1c0928ee-535f-11e7-8e9c-109da29115f8.PNG)

**Comment by mistic** [comment]
@ezsper Are you using your own server implementation? In our server you can do a `formatError & formatResponse` in the onOperation callback.

**Comment by ezsper** [comment]
No, I'm using Appolo Server. But the problem is that `formatError` is not applied to ws/subscriptions, only for rest requests. As you can see above we need to be able to throw custom errors both in resolve and subscribe methods of the subscription, and we need to be able to format this output on websocket subscriptions messages.

**Comment by mistic** [comment]
@ezsper what is the `SubscriptionServer` version you're using?

**Comment by ezsper** [comment]
```
"graphql": "^0.10.1",
"graphql-subscriptions": "0.4.3",
"subscriptions-transport-ws": "0.7.3",
"graphql-server-koa": "0.8.5"
```

**Comment by scf4** [comment]
Also running into this. Why doesn't the server offer the formatError option?

**Comment by altschuler** [comment]
I managed to work around this by using `formatResponse`. In your `onOperation` handler, add `formatResponse` to the params object and check if the value has errors:

```
onOperation(msg, params, socket) {
    params.formatResponse = value => {
        if (value.errors) {
            // For instance
            value.errors = value.errors.map(e => yourFormatErrorFn(e));
        }
    }
    ...
}
```

**Comment by hlehmann** [comment]
good ! is it possible to implement a formatError directly in:
```javascript
  new SubscriptionServer({
    schema,
    execute,
    subscribe,
    formatError,
    formatResponse
  }, {
    server,
    path,
  });
```

**Comment by mxstbr** [comment]
You can also do 

```JS
onOperation(msg, params, socket) {
  params.formatError = errorFormatter;
}
```

Which works similarly to the vanilla GraphQL `formatError` option. Unfortunately it's not called on all errors. :cry:

**Comment by Richie765** [comment]
@mxstbr, I don't think that works. After some digging I see `formatError` is called inside a `catch()` [here](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L374) but errors are resolved, not rejected and therefor will never reach that catch. Instead it will reach the `formatResponse` [here](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L363). The work-around of @altschuler seems to work, but it's a hack and should be implemented in the package.

**Comment by mjdickinson** [comment]
Thanks @altschuler, that worked for me.  One small point: you need to return value from the formatResponse function.

I have this:
```
onOperation(msg, params, socket) {
    params.formatResponse = value => ({
        ...value,
        errors: value.errors && value.errors.map(formatError),
    })
...
}

```

**Comment by bennypowers** [comment]
I've not yet found the way to handle errors that happen in onConnect

```js
const onConnect = async ({ authToken }, webSocket) => {
  if (!authToken) throw new NoauthError();
  try {
    const token = await validateToken(authToken);
    return objOf('token', token);
  } catch (error) {
    throw error;
  }
};

// HACK: https://github.com/apollographql/subscriptions-transport-ws/issues/182
const onOperation = (msg, params, socket) => {
  console.log('onOperation');
  return ({ ...params, formatResponse });
};

export const createSubscriptionServer = ({ server, path }) => {
  console.log(`Apollo SubscriptionServer is now listening on ws://localhost:${PORT}`);
  return new SubscriptionServer({
    execute,
    onConnect,
    onOperation,
    schema,
    subscribe,
  }, { server, path });
};
```

**Comment by nuragic** [comment]
Wow! Spent almost 1 day debugging every layer (from apollo-client to graphql.js itself) to see how I could solve this one... The good thing is that I actually learnt a lot during the process! 😄 Anyway, many thanks to @altschuler for the final tip, as far as I've seen that's the only way we have to customize the errors sent up to the client (when using this subscription server of course). As mentioned above, keep in mind to return `params` from the `onOperation`:

```js
// …

function formatError(error) {
  const { message, statusCode, body } = error.originalError;
  return {
    message: body.message || message,
    conflict: statusCode === 409,
    // …
  };
}

// …

new SubscriptionServer({
  execute,
  subscribe,
  schema,
  onOperation(msg, params) {
    // eslint-disable-next-line no-param-reassign
    params.formatResponse = (value) => ({
      ...value,
      errors: value.errors && value.errors.map(formatError),
    });
    return params;
  },
  // …
},

// …
```

🤷‍♂️

**Comment by developdeez** [comment]
Was there ever a solution here. params.formatError and Response are undefined when I throw and error
