### ISSUE TITLE
Possibility to use ws as an endpoint for GraphiQL

### ISSUE THREAD

**Issue by vladshcherbin** [apollographql/subscriptions-transport-ws#183]
Is it possible to use `ws` as an `endpointUrl` for `graphiQl`

```js
router.get('/graphiql', graphiqlKoa({
  endpointURL: 'ws://localhost:5000/graphql'
}))
```

I tried this, but I have an error: `Fetch API cannot load ws://localhost:5000/graphql?. URL scheme must be "http" or "https" for CORS request`.

Ws on client is working.

**Comment by akaNightmare** [comment]
```js
router.get('/graphql', graphqlKoa())
router.get('/graphiql', graphiqlKoa({
  endpointURL: '/graphql'
}))
```

**Comment by VladShcherbin** [comment]
@akaNightmare probably `post` for first route and it will use http for requests. I want to use websockets for request, same as apollo-client can do.

**Comment by shtse8** [comment]
I noticed that my server is full websocket server, but graphiql cannot support endpoint for websocket.
