### ISSUE TITLE
ws errors don't match http errors

### ISSUE THREAD

**Issue by VladShcherbin** [apollographql/subscriptions-transport-ws#186]
I have a simple query:

```js
{
  permissions {
    title
    description
  }
}
```

On the server I didn't define `description` field. If I use *http* to execute query, I receive error on client and in props:

![screen shot 2017-06-20 at 1 42 27 am](https://user-images.githubusercontent.com/6711845/27308960-1125d9fc-555a-11e7-9bde-5fe01dd030ea.png)

If I use *ws* as a transport, I receive the data (permissions w/o description field), console warnings and no error in props:

![screen shot 2017-06-20 at 1 43 21 am](https://user-images.githubusercontent.com/6711845/27308983-282e96fc-555a-11e7-85f2-d3c4aa2cecce.png)

Client code:

 ```js
const wsInterface = new SubscriptionClient('ws://localhost:3000/graphql', { reconnect: true })
const httpInterface = createNetworkInterface({ uri: 'http://localhost:3000/graphql' })
const apolloClient = new ApolloClient({ networkInterface: wsInterface })
```

Is it working as intended and how do you receive errors using *ws*?

**Comment by mistic** [comment]
@VladShcherbin Can u give more information about the issue? I would like to see the entire props you're receiving? It should be working as intended.

**Comment by VladShcherbin** [comment]
@mistic Here is the whole code. There are 2 network interfaces (http and ws). Ws is used first:

```jsx
import React from 'react'
import ReactDOM from 'react-dom'
import { createNetworkInterface, gql, graphql, ApolloClient, ApolloProvider } from 'react-apollo'
import { SubscriptionClient } from 'subscriptions-transport-ws'

const httpNetworkInterface = createNetworkInterface({ uri: 'http://localhost:3000/graphql' })
const wsNetworkInterface = new SubscriptionClient('ws://localhost:5000/graphql', {
  reconnect: true
})
const apolloClient = new ApolloClient({ networkInterface: wsNetworkInterface })

const usersQuery = gql`query { users { username } }`

const TestComponent = (props) => {
  const { loading, error, users } = props.data

  console.log(1, loading)
  console.log(2, error)
  console.log(3, users)

  return (
    <p>test</p>
  )
}

const TestComponentWithData = graphql(usersQuery)(TestComponent)

ReactDOM.render((
  <ApolloProvider client={apolloClient}>
    <TestComponentWithData />
  </ApolloProvider>
), document.getElementById('app'))
```

The `usersQuery` is correct and there are 3 `console.log`s with the props. When everything is correct, the output is fine and is:

![screen shot 2017-07-07 at 6 17 55 am](https://user-images.githubusercontent.com/6711845/27942120-4956f744-62dd-11e7-9bf8-f7fe2d0886c2.png)

However, when you add an unknown field to the query:

```jsx
const usersQuery = gql`query { users { username nonExistField } }`
```

Now the output is:

![screen shot 2017-07-07 at 6 20 01 am](https://user-images.githubusercontent.com/6711845/27942143-5809db58-62dd-11e7-818d-42c1e5559195.png)

So, there is no error in props and even the users are received. Here are ws frames showing received error and then received users:

![screen shot 2017-07-07 at 6 20 40 am](https://user-images.githubusercontent.com/6711845/27942158-717c481e-62dd-11e7-8872-188e77c0dca8.png)

---

Now, if you switch to using httpNetworkInterface, you will receive an error in props:

![screen shot 2017-07-07 at 6 24 53 am](https://user-images.githubusercontent.com/6711845/27942180-9e65de26-62dd-11e7-9a0d-e72cbee1840b.png)

And you also won't receive any users later:

![screen shot 2017-07-07 at 6 24 37 am](https://user-images.githubusercontent.com/6711845/27942191-b41dceae-62dd-11e7-9545-13c49767882d.png)

So, as you can see, errors when using ws / http don't match and with ws users are even received though the query returned an error first.

**Comment by VladShcherbin** [comment]
https://github.com/apollographql/subscriptions-transport-ws/issues/182 is probably related as you don't even receive a graphql error over ws.

**Comment by VladShcherbin** [comment]
Using `graphql` function instead of `execute` solves the problem.

```jsx
const subscriptionServer = SubscriptionServer.create(
  {
    schema,
    execute: graphql,
    subscribe
  },
  {
    server: websocketServer,
    path: '/graphql'
  }
)
```

Moved to https://github.com/apollographql/subscriptions-transport-ws/issues/213
