### ISSUE TITLE
SubscriptionServer memory leap raise node crash

### ISSUE THREAD

**Issue by cncolder** [apollographql/subscriptions-transport-ws#189]
Nodejs@8.1.2

My react project have two pages. Page1 subscribe [a, b, c]. Page2 subscribe [a, b, c, d, e, f].

Those two page `subscribeToMore` in `componentDidMount` and unsubscribe in `componentWillUnmount`

When I leave page2 navigate to page1. The code logic is unsubscribe 6 times and subscribe 3 times.

In chrome devtool network tab. I saw websocket send 6 message `{id: "1", type: "stop"}` id(1-6). But only 3 complete `{type: "complete", id: "1", payload: null}` id(1, 5, 6).

Then node memory going to 1.5G in 1 minutes. And crash 1 minute later.

If I comment this line [/src/server.ts#L221](https://github.com/apollographql/subscriptions-transport-ws/blob/d85e71f62f72683d7edf53efd7ad4c84939b03e0/src/server.ts#L221). Node memory not leap but subscription not stop also.

**Comment by maktouch** [comment]
I can reproduce this. 

In my subscribe resolve, I just added logging 

```javascript
    subscribe: withFilter(() => pubsub.asyncIterator('hello'), (payload, variables) => {
        console.log('subscribe', {
            payload, variables
        });

        return true
    }),
```

- Start GraphQL server + websocket server
- Open browser to GraphiQL. 
- Enter Subscription query and press Play twice. 
- GraphQL server should console.log infinitely until it crashes.

**Comment by maktouch** [comment]
Huh. If I remove `withFilter` on my subscribe method, it doesn't do it anymore. 

@cncolder are you using graphql-redis-subscriptions by any chance?

**Comment by cncolder** [comment]
No @maktouch . I use `const { PubSub } = require('graphql-subscriptions')`.

I follow this until [https://github.com/graphql/graphql-js/blob/master/src/subscription/subscribe.js](https://github.com/graphql/graphql-js/blob/master/src/subscription/subscribe.js). But it's hard to understand there.

**Comment by maktouch** [comment]
Ok. I just swapped out graphql-redis-subscriptions with graphql-subscriptions and you're right, it still does the same.

**Comment by maktouch** [comment]
Ah, found it. Turns out it's a bug in graphql-subscriptions: https://github.com/apollographql/graphql-subscriptions/issues/81

**Comment by cncolder** [comment]
Yes. Seems I going to the wrong way.

**Comment by hems** [comment]
One possible solution is to create an asyncIterator for each document you need instead of filtering the document ?

For instance, instead of filter all "likes" by checking their "doc_id", you could create an async that has the "id" on it's key. Like you kinda do when composing redis keys?
````
      subscribe: function(option, args){
        return pubsub.asyncIterator('like_added:' + args.doc_id)
      }
````

**Comment by stubailo** [comment]
Can we confirm that this is fixed after https://github.com/apollographql/graphql-subscriptions/pull/84?

**Comment by cncolder** [comment]
90% fixed. I will keep watching it. This happening 3-5 times everyday in my dev server.

**Comment by seeden** [comment]
It is still an issue

**Comment by NeoPhi** [comment]
Does someone have a minimal reproduction repo with instructions on how to duplicate the problem?
