### ISSUE TITLE
pubsub variable on the readme not used anywhere?

### ISSUE THREAD

**Issue by hems** [apollographql/subscriptions-transport-ws#190]
I was implementing redis-subscriptions but then got a message from "SubscriptionServer" saying that "subscriptionManager" is deprecated.

So i came to the readme here and i realised that even thought there are instructions for creating the "pubsub" it's not shown where it's used and how to connect it to the SubscriptionServer, am i missing something?

**Comment by NeoPhi** [comment]
The PubSub is indirectly used to return an `AsyncIterator` in the `subscribe` resolver for the subscription. An example can be found at http://dev.apollodata.com/tools/graphql-subscriptions/subscriptions-to-schema.html

**Comment by hems** [comment]
yeah for a moment i forgot the AsyncIterator was the connection between the dots! Thank You
