### ISSUE TITLE
error on basic setup "Unable to find native implementation, or alternative implementation for Websocket"

### ISSUE THREAD

**Issue by dohomi** [apollographql/subscriptions-transport-ws#191]
Hello,
I receive after basic setup an error at my project. Following setup:

apollo-client: Version 1.6.0
subscriptions-transport-ws: Version 0.7.3

```
import 'isomorphic-fetch'
import { ApolloClient, createNetworkInterface } from 'apollo-client'
import { SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws'

const apolloUri = 'https://api.graph.cool/simple/v1/__ID__' 
const wsClient = new SubscriptionClient('wss://subscriptions.graph.cool/v1/__ID__', {
  reconnect: true
})

const networkInterface = createNetworkInterface({
  uri: apolloUri,
  transportBatching: true,
  opts: {
    credentials: 'same-origin'
  },
  ssrMode: process.SERVER_BUILD
})

const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
  networkInterface,
  wsClient
)

export const apolloClient = new ApolloClient({
  networkInterface: networkInterfaceWithSubscriptions,
  dataIdFromObject: r => r.id
})
```

```
Unable to find native implementation, or alternative implementation for WebSocket!

Error: Unable to find native implementation, or alternative implementation for WebSocket!
    at new SubscriptionClient (/data/vuejs/students-admin/node_modules/subscriptions-transport-ws/dist/client.js:31:19)```
Thanks

**Comment by sorenbs** [comment]
Just to clarify - you are running this in node, right?
What version of node are you using?

**Comment by dohomi** [comment]
I'm running it in my current NUXT project, Node 8.1 is in use

**Comment by sorenbs** [comment]
I have no experience with this, but you probably have to include a a websocket implementation such as https://github.com/websockets/ws

Let's wait for the Apollo folks to chime in :-)

**Comment by helfer** [comment]
Hey @dohomi, @sorenbs is right. This error is thrown [here](https://github.com/apollographql/subscriptions-transport-ws/blob/d85e71f62f72683d7edf53efd7ad4c84939b03e0/src/client.ts#L92). You can fix it by providing a websocket implementation to the client constructor as the third argument:

```
import ws from 'ws';

const wsClient = new SubscriptionClient('wss://subscriptions.graph.cool/v1/__ID__', {
  reconnect: true
}, ws)
```

**Comment by mistic** [comment]
@dohomi is this issue solved?

**Comment by dohomi** [comment]
Will close it here because I guess the issue belongs to NUXT, I can't get `ws`running in my application without an error

**Comment by saadbinsaeed** [comment]
Same problem even the ws package did not work for me :(

**Comment by kukiron** [comment]
The solution worked for me though, after adding **ws** package.

**Comment by csmit175** [comment]
this worked perfectly for me

**Comment by flintovich** [comment]
@helfer, Thanks, this helped for my case also

**Comment by cyrus-za** [comment]
I got the same error and even adding ws doesn't solve the issue for me. I am using nextjs, not nuxt but same thing basically.

**Comment by morajabi** [comment]
I added `ws` in next js and it worked. Thanks

**Comment by dmurawsky** [comment]
+1

**Comment by mghazanfar** [comment]
PS F:\work\bluerain-app-assets\packages\bluerain-app-assets> npm test

> @blueeast/bluerain-app-assets@0.0.0 test F:\work\bluerain-app-assets\packages\bluerain-app-assets
> jest


npm ERR! Test failed.  See above for more details.

This is what I got after this solution. Please help me. Why my tests are getting failed without giving any detail about each story???

**Comment by morajabi** [comment]
@mghazanfar Could you share more of your code or fill another issue with all the details?

**Comment by mghazanfar** [comment]
Sure
See in the below:

1- import { SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws/dist/client';
2- import WebSocket from 'ws';
3- const wsClient = new SubscriptionClient('ws://localhost:5000', {
	reconnect: true,
	connectionParams: {
		accessToken: 'jkasdhkjashd jkashdjk ashdas'
	}
}, WebSocket);
These three steps were actually required and After doing them I have already shared the problem in the post above.

**Comment by morajabi** [comment]
There are no `addGraphQLSubscriptions` in the main `subscriptions-transport-ws` package as of version `0.83` I guess.

**Comment by adnan1naeem** [comment]
I am having this problem by using apollo-link.as it  uses subscriptions-transport-ws under the hood in  its library.my problem was not resolved  after adding ws packages.any help ???

**Comment by Cuxs** [comment]
I've used create react app in my project and that error occurs when I try to build the app.
The ws package also produces an error, I've tried with socket.io client but it throws the same error.
Is there another websocket implementation rather than ws that I can use there?

**Comment by nehaMetricks** [comment]
I am using apollo-link-ws and facing the same issue. I have tried adding ws package and it does not resolve the error. Any help would be appreciated.

**Comment by jsangilve** [comment]
@nehaMetricks in case you didn't find a solution: 

```typescript
import * as ws from 'ws';
import { WebSocketLink } from 'apollo-link-ws';

const wsLink = new WebSocketLink({
  uri: `ws://localhost:3003/graphql`,
  options: {
    reconnect: true,
  },
  webSocketImpl: ws
});
```

**Comment by mralbertnguyen** [comment]
> @nehaMetricks in case you didn't find a solution:
> 
> ```ts
> import * as ws from 'ws';
> import { WebSocketLink } from 'apollo-link-ws';
> 
> const wsLink = new WebSocketLink({
>   uri: `ws://localhost:3003/graphql`,
>   options: {
>     reconnect: true,
>   },
>   webSocketImpl: ws
> });
> ```

Thank you so much , it was solved my problem

**Comment by imomin** [comment]
I tried above solution shared by @nehaMetricks now I am getting following error.
TypeError: this.wsImpl is not a constructor
    at SubscriptionClient.Yzoe.SubscriptionClient.connect

**Comment by gabeblack** [comment]
@imomin  `import WebSocket from 'ws';`

**Comment by thatgriffith** [comment]
For those of you who are still stuck after testing @jsangilve solution (like I was). There is a great solution here: https://github.com/apollographql/subscriptions-transport-ws/issues/333#issuecomment-359261024

**Comment by technoligest** [comment]
For anyone stumbling upon this now while trying to setup Nextjs, the real answer is here: https://github.com/apollographql/subscriptions-transport-ws/issues/333#issuecomment-359261024

The gist of it is that only client rendered pages can use the websocket link.
