### ISSUE TITLE
Can't match an onOperationComplete call to its onOperation call

### ISSUE THREAD

**Issue by phBalance** [apollographql/subscriptions-transport-ws#200]
I'm in the process of converting over my code from using http (via express) for queries to ws. It's handy using express, as it will capture performance metrics for each http request. Wanting to do something similar for the socket operations, unfortunately, doesn't seem to be possible to match the start and end events for an operation.

Basically, I want to record the operation start time through the onOperation callback and calculate the diff through the onOperationComplete callback. I can extract message.id from onOperation right now, but onOperationComplete doesn't provide anything other than the WebSocket. The opId (which seems to be the same) is easily available call the callpoint in SubscriptionServer.unsubscribe.

Am I missing a better way of doing this or would it be possible to add that parameter to the onOperationComplete callback?

**Comment by mistic** [comment]
@phBalance I think we could expose `onOperationComplete` with the following interface:

`onOperationComplete?: (webSocket: WebSocket, opId: string)`. Will it be enough for you?

**Comment by phBalance** [comment]
That's sufficient to match things up and works for me.

**Comment by mistic** [comment]
@phBalance my pull request #211 will solve this issue.
