### ISSUE TITLE
error TS7016: Could not find a declaration file for module 'subscriptions-transport-ws'

### ISSUE THREAD

**Issue by blocka** [apollographql/subscriptions-transport-ws#203]
I must be doing something really stupid.....

**Comment by mistic** [comment]
@blocka can u provide more information about your problem please?

**Comment by blocka** [comment]
What would you like to know?
I'll start with this:
![image](https://user-images.githubusercontent.com/43194/27893726-94140578-61d5-11e7-8ebf-b6762f16cfb8.png)

I temporarily "solved" the issue by providing a stub definition for it.

**Comment by mistic** [comment]
@blocka can u please make a test form me? Go to the package.json of subscriptions transport ws inside your node modules and on key `main` and `typings` Replace it with this:

"main": "./dist/index.js"
"typings": "./dist/index.ts.d"

Or with

"main": "./dist/index.js"
"typings": "./dist/index.ts.d"

Let me know if it worked

**Comment by blocka** [comment]
I don't see the difference between your two suggestions.

Right now they both say "dist/*". are you suggesting to change that to
"./dist/*"?

If that's what you meant, I just tried it and it doesn't solve anything....

**Comment by blocka** [comment]
strange i think it may be working now that I've restarted vscode...If I
continue to have issues I will reopen this issue.

**Comment by mistic** [comment]
@blocka sorry I wrote that through my phone, what I was trying to suggest you was to do that:

```javascript
"main": "./dist/index.js"
"typings": "./dist/index.ts.d"

Or with

"main": "dist/index"
"typings": "dist/index"
```

It is now working for you without the changes I have suggested? Can u please verify and get back to me so I can close the issue?

**Comment by blocka** [comment]
for now it seems to be working. You can close, and if I have more trouble I
will reopen

**Comment by mistic** [comment]
Just to assure @blocka. It is working without any change, as it is on master branch? :)

**Comment by blocka** [comment]
yes

**Comment by mistic** [comment]
Ok. I'll close this issue. Please open another if the problem persists.
