### ISSUE TITLE
Add SubscriptionServer query resolution function

### ISSUE THREAD

**Issue by VladShcherbin** [apollographql/subscriptions-transport-ws#213]
Currently, SubscriptionServer uses `execute` from `'graphql'` under the hood and in the docs.

If there is a syntax error in a query, it won't be caught because `execute` just executes the query, it doesn't check for syntax error. This is the [issue](https://github.com/apollographql/subscriptions-transport-ws/issues/186) I had when using default implementation.

`graphql` package has a function `graphql` [link](https://github.com/graphql/graphql-js/blob/master/src/graphql.js#L68) that is used to check for [syntax and validation errors](https://github.com/graphql/graphql-js/blob/master/src/graphql.js#L114) and only then runs `execute` function.

Apollo `graphql-server` has also its own [function](https://github.com/apollographql/graphql-server/blob/6d8047f5dd6001918c9c8b91657415fba6058fbc/packages/graphql-server-core/src/runQuery.ts#L62) that also checks for [syntax and validation errors](https://github.com/apollographql/graphql-server/blob/6d8047f5dd6001918c9c8b91657415fba6058fbc/packages/graphql-server-core/src/runQuery.ts#L101) and has additional options like `formatError `.

Current `subscriptions-transport-ws` implementation is incomplete because it doesn't have this checks. So, by default `graphql` method should be used instead of just `execute` or a custom function should be provided with this checks (optionally with options like `formatError`).

**Comment by VladShcherbin** [comment]
Related https://github.com/apollographql/subscriptions-transport-ws/issues/182

**Comment by mistic** [comment]
@VladShcherbin Can u check if #241 closes your issue?
