### ISSUE TITLE
Subscription endpoint in docker

### ISSUE THREAD

**Issue by liyucun** [apollographql/subscriptions-transport-ws#215]
Currently, i use the following endpoint for subscription:
```
  const wsGqlURL = `ws://localhost:${setting.port}/subscriptions`
  app.use(
    "/graphiql",
    graphiqlExpress({
      endpointURL: "/graphql",
      subscriptionsEndpoint: wsGqlURL,
      query: `...`,
    }),
  )
```
But when i run it with docker, I can not subscribe to my topic on `graphiql` or through the given link.   I wonder if we should use another web socket link for docker.

The subscription is working locally.

**Comment by mistic** [comment]
Hey @liyucun I don't know if I really understand your question, but isn't this likely to be a problem with your docker network configuration itself? Are your docker port `setting.port`open? Also try to not bind your server to 'localhost' please try to bind it to '0.0.0.0' for example.

Let me know if the problem is solved :)

**Comment by liyucun** [comment]
> isn't this likely to be a problem with your docker network configuration itself? Are your docker port setting.port open?

the network configuration and port is correct, and i can use both query and mutation. 
>  try to bind it to '0.0.0.0' for example.

Tried this one, but still doesn't work.

I just come up with more detail about my problem now. I use the same port for both `graphql` and `subscription-ws`, and this work if i just run the app by npm or yarn. However, when i run it in docker, there will be an error on my broswer:
```
WebSocket connection to 'ws://localhost:80/subscriptions' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```
I guess we need to specify one port for each of them(`graphql` and `websocket`), right?

**Comment by dotansimha** [comment]
@liyucun 
It looks like something wrong with your Docker configuration. 
Please make sure you expose your endpoint port outside your Docker container.
Also, please try to go inside your active container and use `curl` to try and fetch any GraphQL endpoint and see if you can.  If you can access your GraphQL endpoint from inside the container - it will verify that you don't expose the express port correctly.

**Comment by liyucun** [comment]
@dotansimha thanks for your reply. I just solved the problem, and it caused by a typo in my web socket url. ;(

Thanks again for you guys help! ;)
