### ISSUE TITLE
Remove postinstall section from package.json

### ISSUE THREAD

**Issue by cncolder** [apollographql/subscriptions-transport-ws#217]
Is there any reason run tsc compile after npm  install on user machine? Or this script is only make it easy for contributor?

I saw that typescript is devDependencies.

**Comment by mistic** [comment]
@cncolder the postinstall script makes this library able to be installed from a github branch which is useful in some situations :)

**Comment by cncolder** [comment]
Thanks. I understand now.

I worry this bcs postinstall take long time than before in ci/cd

**Comment by dotansimha** [comment]
@mistic do you think we can find an alternative way to install the package from the repo?

**Comment by mistic** [comment]
@dotansimha I think that's the best way to do it :( However I've implemented a solution just shipped with `0.8.1` that should handle the problem reported by @cncolder. @cncolder can u check out the new version and give some feedback? Can u close the ticket?

**Comment by cncolder** [comment]
ok now. thanks.
