### ISSUE TITLE
after upgrade 0.7.3 to 0.8.0 error message

### ISSUE THREAD

**Issue by dohomi** [apollographql/subscriptions-transport-ws#220]
Hello,
after I upgraded the package from 0.7.3 => 0.8.0 I receive following error in the console:
```
VM7914:37 WebSocket connection to 'wss://subscriptions.graph.cool/v1/xxx' failed: Connection closed before receiving a handshake response
```
This happens on every connection I try to establish
Any idea how to solve this?

**Comment by mistic** [comment]
Are u using `SubscriptionsServer`? Can u post here your Websocket frames?

**Comment by dohomi** [comment]
```
import 'isomorphic-fetch'
import { ApolloClient, createNetworkInterface } from 'apollo-client'
import { SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws'
import { getTokenFromStorage } from './auth-helpers'
const apolloUri = 'https://api.graph.cool/simple/v1/xx'
const wsUri = 'wss://subscriptions.graph.cool/v1/xx'

export default function () {
  const ssr = process.SERVER_BUILD
  const networkInterface = createNetworkInterface({
    uri: apolloUri,
    transportBatching: true,
    opts: {
      credentials: 'same-origin'
    }
  })

  let wsClient
  let networkConf
  // let initialState
  if (!ssr) {
    wsClient = new SubscriptionClient(wsUri, {
      reconnect: true
    })
  }

  if (wsClient) {
    networkConf = addGraphQLSubscriptions(
      networkInterface,
      wsClient
    )
  } else {
    networkConf = networkInterface
  }

  networkConf.use([{
    applyMiddleware (req, next) {
      if (!req.options.headers) {
        req.options.headers = {} // Create the header object if needed.
      }
      const token = getTokenFromStorage(req)
      req.options.headers.Authorization = `Bearer ${token}`
      next()
    }
  }])

  return new ApolloClient({
    networkInterface: networkConf,
    dataIdFromObject: r => r.id,
    ...(ssr ? {
      ssrMode: true
    } : {
      connectToDevTools: process.env.NODE_ENV !== 'production'
    })
  })
}

```

**Comment by mistic** [comment]
@dohomi Please post here your websocket frames information (the exchange of messages between your connect_init, the received connection_ack and your first keep alive message). Also are u able to connect and use it normally and this is only a warning message, or u are having troubles making the data communications?

**Comment by dohomi** [comment]
ah sorry.. this package is very new for me.. haven't dipped into it that much yet. I installed it last week and it simply worked, after upgrade it stopped working. The request always times out as a fatal error. here is the websocket frames information:
<img width="560" alt="screen shot 2017-07-11 at 00 23 00" src="https://user-images.githubusercontent.com/489221/28028513-5464c2ac-65cf-11e7-8113-c73b38cdf3de.png">

**Comment by dohomi** [comment]
In 0.7.3 it looks I think OK, there are many ```{type: "ka"}
type
:
"ka"``` frames. In 0.8.0 the type never getting called and after some time another Network request is being made, which also idles and times out without any response

**Comment by mistic** [comment]
@dohomi Can u please test a thing for me? please init your client with your timeout disable and report the results for me :) I think I found a bug in the server keep alive implementation ;)

**Comment by dohomi** [comment]
@mistic what exactly do you want me to do? I'm not sure about `client with timeout disable`?

**Comment by mistic** [comment]
@dohomi Increase your timeout to 30000 ms like this:

```javascript
if (!ssr) {
    wsClient = new SubscriptionClient(wsUri, {
      reconnect: true,
      timeout: 30000
    })
  }
```

Let me know the results

**Comment by dohomi** [comment]
Ah ok sorry, here is the result. currently the subscription still throws the same error but now it seems that something is happening.
<img width="433" alt="screen shot 2017-07-11 at 08 54 25" src="https://user-images.githubusercontent.com/489221/28046498-9e798610-6616-11e7-8f2e-fcdd5ed7947d.png">

**Comment by dohomi** [comment]
The subscription seems to get fired 2 times, the first seems to throw the error message:
<img width="452" alt="screen shot 2017-07-11 at 08 56 17" src="https://user-images.githubusercontent.com/489221/28046531-e002d28a-6616-11e7-947c-4feff71cfd8c.png">

**Comment by mistic** [comment]
@dohomi ok I've spotted a bug with the server version used by graphcool: they should sent the ka instantly after the connection_ack. You can reset your timeout back to 12s (before the a new version of the server is published, because after that u can put it again to 10s ). Are u still unable to receive your subscription data? Looking at your frames right now, I'm only see an ack and a keep alive, I'm not seeing any subscription request being sent.

**Comment by dohomi** [comment]
Does this look normal to you, I'm not sure why there are 2 starting connections. Is there anything I should do or will this be fixed at graph.cool side? It seems the connections are now being made.
<img width="412" alt="screen shot 2017-07-11 at 09 06 53" src="https://user-images.githubusercontent.com/489221/28046739-5dc6b046-6618-11e7-9a67-3fe2cc7cd79b.png">

**Comment by mistic** [comment]
@dohomi but are your subscriptions returning data to you? Aren't you somehow subscribing to times the subscriptions? 

Can u check another thing for me please? Please hook to this callbacks and tell me how much times they are called since u connect and you next 20/30s:

```javascript
wsClient.onDisconnected(() => {});

wsClient.onConnecting(() => {});

wsClient.onReconnecting(() => {});
```

**Comment by dohomi** [comment]
<img width="554" alt="screen shot 2017-07-11 at 09 27 23" src="https://user-images.githubusercontent.com/489221/28047223-33f41cc4-661b-11e7-92f4-2695986480fa.png">

**Comment by mistic** [comment]
@dohomi You can just ignore the warning :) I've found 1 bug and 1 option that can be available in the client to optimize the configuration. Thanks :) Could u only confirm that you are now able to receive subscriptions data?

**Comment by dohomi** [comment]
@mistic Thanks you very much for your help. I currently broke my app due not being able to connect with authentication. This has nothing to do with this issue but do you know how I possibly get the Cookie Token on the server side rendering with applyMiddleware?
```
networkConf.use([{
applyMiddleware(req,next){
==> req is empty even I set the token for authentication on server start
}
}])
```
I'm sure before I broke it, the subscription data was being sent, if now I'll post it again

**Comment by dohomi** [comment]
@mistic please ignore my applyMiddleware question.. I finally solved it. Yes I can confirm with a timeout of 30000 the subscription starts working again

**Comment by mistic** [comment]
@dohomi so with a timeout of 30000ms are u able to just retrieve the subscription with any error subscription start? I believe that graphcool is using an older version with default timeout of 30000 ms :)

**Comment by mistic** [comment]
@dohomi we just released a new version. Can u check and give some feedback if we can close this ticket?

**Comment by dohomi** [comment]
@mistic after updating the lib the console error is gone. But I'm not sure why the payload inside of the network tab is now always empty:
<img width="396" alt="screen shot 2017-07-12 at 08 07 30" src="https://user-images.githubusercontent.com/489221/28096149-2f7b9898-66d9-11e7-939d-d31088822966.png">

**Comment by dohomi** [comment]
@mistic ok after adding the 30s back everything works as expected. So I will leave it like that for now. Thanks for your instant help 👍

**Comment by marktani** [comment]
Also see https://github.com/graphcool/feature-requests/issues/309#issuecomment-314761299 for further discussion on this topic.
