### ISSUE TITLE
Handling offline status / machine sleep

### ISSUE THREAD

**Issue by viridia** [apollographql/subscriptions-transport-ws#226]
I've noticed that when I walk away from my machine for 30 minutes - long enough for it to go to sleep - that the network interface shuts down, the web socket disconnects, and the client starts spewing console messages about how it cannot reconnect. Eventually it gives up. When I come back to the computer, and wake it from sleep, there's no more connection and no way to reconnect without reloading the page. (This is on OS X Sierra BTW).

Now, I can listen for the browser online/offline events, but is there any way to tell the client to try reconnecting that doesn't involve losing all my active subscriptions?

**Comment by viridia** [comment]
Actually, thinking about this some more, there are bigger problems. Because SubscriptionClient doesn't expose a reconnect method, the only way I can re-establish the connection after the machine wakes from sleep is to construct a brand new SubscriptionClient. But that means any outstanding data that depends on the old client - observable queries, cached data and so on - has to be created anew.

Unless I misunderstand how this all works, it means that I have to basically throw away all of my application state and reload it. Architecturally this is quite a challenge, and I'm not sure how to handle it. It means that every component or data model has to listen for the subscription client connect / disconnect state changes and reload itself after a wake from sleep.

What I'd like instead is to just be able to suspend the web socket when I get a browser 'offline' event, and resume it when I get a browser online 'event'. I would at the same time want to invalidate all caches (since objects might have been updated while the app was disconnected from the server and not receiving subscriptions), and do a forced refresh of any outstanding queries. Or something.

**Comment by acro5piano** [comment]
Some browsers and OS does not fire `online` or `offline` event when backing from sleep.

Tested on Arch Linux / Thinkpad X240 / Chromium

**Comment by acro5piano** [comment]
I had the same issue, and ended up to run every n seconds `close` method with `false` which fires reconnect again.

```ts
const subscriptionClient = new SubscriptionClient('wss://graphql.server.app/graphql/subscriptions', {
  reconnect: true,
  lazy: true,
})

setInterval(() => {
  subscriptionClient.close(false)
}, 60 *1000)
```
