### ISSUE TITLE
Relative path for SubscriptionClient

### ISSUE THREAD

**Issue by mikeyGlitz** [apollographql/subscriptions-transport-ws#227]
Is there a way to use a relative path in order to initialize the `SubscriptionClient`?
Currently the documentation states that in order to initialize the `SubscriptionClient` I need to use the following:

```js
const wsClient = new SubscriptionClient('ws://localhost/subscriptions', {
// client config
});
```

Is there a way to do something like this?
```js
const wsClient = new Subscription('/subscriptions', { ... } );
```

**Comment by mistic** [comment]
@mikeyGlitz currently we don't have any other way to do it different from: `ws://localhost/subscriptions`.

**Comment by dotansimha** [comment]
@mikeyGlitz 
Please refer to: https://stackoverflow.com/questions/10406930/how-to-construct-a-websocket-uri-relative-to-the-page-uri 

This issue it to related directly to this package, and it's an issue with `WebSocket` implementation on your browser.

**Comment by mikeyGlitz** [comment]
That may work,  but i see an issue with certain domains. One of my clients hosts their site with a format that looks like "domain.com/myapp" where that URI is actually a proxy to the node app (why they didn't use a stub domain instead is beyond me).
In the one hand, I could just bind the WebSocket URI to an environment variable which webpack resolves, but that means setting up a separate build process just for production. 
The other way I thought about going about this was hosting configuration on the server side, but 
1. Graphql isn't accessible until after apollo client is set up
2. If i wait until I receive a response containing the configuration from the sever, in the case that I get an error from the sever,  my application won't load and be useless
