### ISSUE TITLE
Possible to mutate the context?

### ISSUE THREAD

**Issue by Torsten85** [apollographql/subscriptions-transport-ws#228]
Hi there,
I'm currently setting the context in the `onConnect` callback of the `SubscriptionServer`. Due to the fact that the connection is kept alive all the time (which is of course whats WebSockets are for), the context will be the same for the whole session. It would be great to have a way of mutating the context during this session. Simply changing the context object in a resolver has no effect because on every socket message, the context is rebuild from scratch.

The only solution for me at the moment is to overload the socket object and reinserting that in the `onOperation` callback back into the context... and this feels horribly wrong ;)

**Comment by swhamilton** [comment]
I also am curious of this. What's the best way to "reset" the connectionParams? I currently use the connection params as part of my authentication for subscriptions:

```
  wsClient = new SubscriptionClient('ws://localhost:9080/graphql', {
    reconnect: true,
    connectionParams: {
      authToken: token
    }
  });
```

But if I logout and try to login as another user, the connection never disconnects and therefore the client keeps those `connectionParams` around.

I did notice that `connectionParams` can return a function, but I'm not sure if this would solve my issue on the client.

One alternative I'm considering is using client middleware to pass the token as a variable for every subscription request. perhaps this is the better way to handle authorization.

```
wsClient = new SubscriptionClient(ws, {
    reconnect: true,
    connectionParams: {
      authToken: token
    }
  });
  wsClient.use([
    {
      applyMiddleware(opts, next, a, b, c) {
        opts.variables.token = token;
        next();
      }
    }
  ]);
  return wsClient;
```

Any thoughts?
