### ISSUE TITLE
Send token from client with each request

### ISSUE THREAD

**Issue by nikitamarcius** [apollographql/subscriptions-transport-ws#240]
I use JWT for authentication and it is necessary to send a token every time with each request from client  to server and return actual data. 

I use [Full WebSocket Transport](https://github.com/apollographql/subscriptions-transport-ws#full-websocket-transport). **connectionParams** send token only with first connection to server.

```
const client = new SubscriptionClient(GRAPHQL_ENDPOINT, {
    reconnect: true,
    connectionParams: function () { // send with first connection to server only
        return window.localStorage.getItem('public_key')
    },
}

// on the server side i check in:
 onConnect: (data) => {
            console.log(data) // here i need replay with each request, but it turns out only with the first connection 
        },
```

_I think that you can perform a mutation when routing and have actual data with callback. On the other hand, the client's capabilities must have such functionality under the hood. What are thoughts?_

**Comment by DxCx** [comment]
hey @nikitamarcius can you explain why you need it for each request?
when using http, each request is stateless.
but when using websocket, you need to authenticate once on connection,
and then you know who user authenticated is. so the context object can hold such information.

**Comment by nikitamarcius** [comment]
Hi @DxCx ! The client side of the application is not safe by default. I have a complex application with a differentiation of rights. If I wish, I can change the context data and gain access to the closed section. 
So that this does not happen, the token should be checked and the actual data returned.

As I already wrote above. The solution for me is within JS Framework  (vue.js my), write a plugin that will perform a mutation and return data with each routing

_I use same solution to check user activity._

**Comment by nikitamarcius** [comment]
some solution: https://github.com/apollographql/subscriptions-transport-ws/issues/171#issuecomment-316376468 #171
