### ISSUE TITLE
Subscription / websockets failing

### ISSUE THREAD

**Issue by ryanking1809** [apollographql/subscriptions-transport-ws#244]
Hi, I'm currently hooking this Hacker News clone ([just clone this repo](https://github.com/howtographql/react-apollo))  up to [graphcool](https://www.graph.cool/)

As per the conversation at https://github.com/howtographql/react-apollo/issues/2
I can get the app to work using the graphcool project id `cj5s6lcr2e1hz0160w8uapdgo` but the subscriptions fail using `cj5s3oafz8j4s0160czwp0jc1`

As far as I can tell the only difference is my projects are located in AP_NORTHEAST.
Graphcool have suggested it may have something to with app creating two subscriptions twice - but I'm not sure if that explains why the other project id works fine.

Any ideas what's going on here?

**Comment by giautm** [comment]
I read somewhere: graphcool using `subscriptions-transport-ws@0.5` not compary with current subscriptions-transport-ws's version

**Comment by ryanking1809** [comment]
The repo linked above uses `subscriptions-transport-ws@0.8.2`

**Comment by ryanking1809** [comment]
Ugh, the subscription url is different for asia pacific region...
