### ISSUE TITLE
Old IE support

### ISSUE THREAD

**Issue by windkomo** [apollographql/subscriptions-transport-ws#248]
Hi, is this compatible with IE8 and IE9 ? I know these browsers d not support websocket, but I think clients like sockjs-client use some sort of fallback (to AJAX polling or other) ?
Does subscriptions-transport-ws have the same type of feature ?

Thanks

**Comment by dobesv** [comment]
To answer your question: no, it does not.  It only supports websockets.

There has been a bit of investigation into a `sockjs`-based transport.  If there was such a thing it would probably be named `subscriptions-transport-sockjs` (I think).
