### ISSUE TITLE
Websocket connection "Subscription timed out - no response from server"; Android Build

### ISSUE THREAD

**Issue by haris-ramzan** [apollographql/subscriptions-transport-ws#249]
I've been getting an issue with making subscriptions on a react-native.I query my Asset on mobile app start to update them, and then subscribe to them. I then occasionally see "[Error: Subscription timed out - no response from server]".

versions are:
 `subscription-transport-ws: 0.5.5`,
`react-apollo: 1.4.8`,
`apollo-client: 1.8.0`,
`react-native: 0.44.0`,

 
The subscription works fine on Web application and IOS but I've tried on android with this client and failed with the "Subscription Timeout no response from server".

I thought it would help to increase the timeout from the default 60000 ms, but the problem still persists. Is there some error handling I'm missing or something else?

The implementation of my client in react-native.

```import ApolloClient, { createNetworkInterface } from 'apollo-client';
import { AsyncStorage } from 'react-native';
import { SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws';

const wsClient = new SubscriptionClient('wss://localhost:5000/', {
  reconnect: true,
  timeout:60000
});
const networkInterface = createNetworkInterface({
  uri: 'https://localhost/graphql'
});

const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
  networkInterface,
  wsClient
);
const client = new ApolloClient({
  dataIdFromObject: o => o.id,
  networkInterface: networkInterfaceWithSubscriptions

});
networkInterface.use([{
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {};  // Create the header object if needed.
    }
    // get the authentication token from local storage if it exists
    AsyncStorage.getItem('sessionToken').then((token) => {
      req.options.headers.Authorization = token ? `${token}` : null;
      next();
    }
    );
  }
}]);
export default client;
```
```
props.data.subscribeToMore({

      document: SubscriptionQuery,
      variables: { options:{ id: props.Id } },

      // this is where the magic happens.

      updateQuery: (previousResult, { subscriptionData }) => {
        const subId = subscriptionData.data.id;
        if (subId !== props.Id) {
          return previousResult;
        }

        const asset = subscriptionData.data.Asset;
        const result = Object.assign({}, previousResult);
        const node = Object.assign({}, previousResult.node);
        result.node = node;
        result.node.state = asset.asset.state;
        // console.log('previous Data :: ', previousResult);
        return result;
      },
      onError: (err) => {
          console.log(err);
      },
```

**Comment by haris-ramzan** [comment]
I have also use the latest version of `subscription-transport-ws: 0.8.2,` and the issue is still same.But no message occur "Error: Subscription timed out - no response from server". Help me out to get this issue..!

**Comment by muaaz-vf** [comment]
+1 Have anybody found solution?

**Comment by waleedarshad-vf** [comment]
+1 @haris-ramzan any solution work for you?

**Comment by muaaz-vf** [comment]
@haris-ramzan what did you try to resolve?

**Comment by perrosnk** [comment]
Are you experiencing this on older versions of android or all android versions? I have opened an issue here https://github.com/apollographql/subscriptions-transport-ws/issues/359
Has anyone found any solutions?

**Comment by jpgarcia** [comment]
Hi @haris-ramzan having the same issue here. Have you found any solution? if not, do you have a way to reproduce the issue in order to troubleshoot it?

**Comment by perrosnk** [comment]
@jpgarcia On which android version are you testing it?

**Comment by jpgarcia** [comment]
I've tried with multiple versions 22, 23, 24. In any case it's very difficult to reproduce the issue 😞
