### ISSUE TITLE
ERROR: No Schema Available

### ISSUE THREAD

**Issue by nikitamarcius** [apollographql/subscriptions-transport-ws#251]
There are no ideas why an error has appeared. Even last night everything worked. Today deleted the folder `node_modules + package-lock.json`, executed the command `npm i `and from that moment all my manipulations did not bring success. 
Connection of the client to the server is available, hybrid transport, grapiql on server works, but full-websockets-transport is not present. 

For npm packages responsible for graphql for the last 24 hours there were no updates.

I also tried to put earlier versions of my project saved on github, the same error, which were guaranteed to work.

I gathered a reduced demo that does not work with the client and server part:
https://github.com/nikitamarcius/test

Node: 8.2.1
"graphql": "^0.10.5",
"graphql-subscriptions": "^0.4.4",
 "subscriptions-transport-ws": "^0.8.2"
 "apollo-client": "^1.9.0",

**Comment by waleedarshad-vf** [comment]
@nikitamarcius  What was your version in package-lock.json file. you may be using older version in that package-lock.json file.

**Comment by waleedarshad-vf** [comment]
Share your package-lock.json here.

**Comment by nikitamarcius** [comment]
@waleedarshad-vf hi, so that there were no conflicts, I deleted it before installing the packages.

Solved: 
reinstall npm packages and projects start works well.

"graphql": "^0.10.5",
  "graphql-subscriptions": "^0.4.4",
 "subscriptions-transport-ws": "^0.8.2",
 "apollo-client": "^1.9.1", <-- seem problem was in this package
