### ISSUE TITLE
Client is not connected to websocket

### ISSUE THREAD

**Issue by muaaz-vf** [apollographql/subscriptions-transport-ws#253]
![client is not conected](https://user-images.githubusercontent.com/5028648/29666071-45758f9e-88f0-11e7-92b9-a6cbc5acef5c.png)

**Comment by waleedarshad-vf** [comment]
+1

**Comment by muaaz-vf** [comment]
Locally it is working fine on port  5000 but on heroku server it is not working fine

**Comment by mistic** [comment]
@muaaz-vf Can u share your configuration please?

Another question, are u connecting to the right port for `wss`?

**Comment by muaaz-vf** [comment]
@mistic take a look at this gist
https://gist.github.com/muaaz-vf/50276bd385d5757264b206970038f670
let me know if you want any other information 
I am using these versions


    "apollo-client": "^0.8.1",
    "apollo-server": "^0.3.3",
    "graphql": "^0.7.2",
    "graphql-anywhere": "^1.1.2",
    "graphql-server-express": "^0.4.4",",
    "react-apollo": "^0.9.0",
    "graphql-subscriptions": "^0.2.3",
    "subscriptions-transport-ws": "^0.3.1",
  }

**Comment by albertorestifo** [comment]
@muaaz-vf You need to place the suscription server creation inside the listen callback:

```js
httpServer.listen(WS_PORT, () => {
  console.log(`Websocket Server is now running  on https://dev.housefolios.com:${WS_PORT}`);
  new SubscriptionServer({ subscriptionManager }, httpServer);
});
```
