### ISSUE TITLE
Reuse express middleware on server side?

### ISSUE THREAD

**Issue by gilbert** [apollographql/subscriptions-transport-ws#254]
I have a complex middleware that I'm currently using to authenticate my graphql requests. It looks something like this:

```js
var server = express()

server.use( cookieAuth() )

server.use('/graphql',
  GS.graphqlExpress( req => ({
    schema: schema,
    context: { user: req.user || null }
  }))
)
server.listen(3000)
```

That all works great. However, now I'm trying to add graphql subscriptions, which involve websockets and this library's `SubscriptionServer`, all of which do not go through the original express pipeline.

Is there a way I can re-use my `cookieAuth()` middleware with `SubscriptionServer` so I don't have to rewrite my auth logic in different terms?

**Comment by gilbert** [comment]
I got it to work, though it's a bit of a hack:

```js
var ws = createServer(myExpressApp)

ws.listen(3003, () => {
  new SubscriptionServer({
    execute,
    subscribe,
    schema,
    onConnect(params, socket) {

      return new Promise((resolve, reject) => {
        cookieAuth(
          socket.upgradeReq, // req obj
          {}, // res object
          function next () {
            var dataToAddToGraphQLContext = { user_id: 123 }
            resolve(dataToAddToGraphQLContext)
          }
        )
      })
    }
  }, {
    server: ws,
    path: '/subscriptions',
  })
})
```

Basically, it manually calls the middleware as a promise, and the data that it resolves with is added to the GraphQL context.

Note that this only works because my middleware does not try to send anything back as a response (i.e. no `res.send`s).

**Comment by ndarilek** [comment]
Along similar lines, I'd like to use this server as a Connect middleware and plug it into existing pipelines.

I'm using [Nuxt.js](https://nuxtjs.org), which has a `nuxt.render` middleware that seems to catch all paths and pass them to Nuxt. I plug the standard HTTP Graphql endpoint and GraphiQL in earlier, so requests to /api and /graphiql are correctly intercepted. But this server seems to circumvent the pipeline entirely, so when a request to something like /subscriptions hits my server, it first goes through the Express pipeline, hits Nuxt, and Nuxt 404s it.

At the very least, I wish this server exposed a function into which I could plug a standard `req, res`. I've filed this issue with Nuxt and there hasn't been a resolution on their end, but without the ability to use this as a Connect-style middleware, I'm not sure how they _could_ make it compatible with the way things are set up now.

Thanks.
