### ISSUE TITLE
Update to accept promise returned from subscribe with graphql 0.11.x

### ISSUE THREAD

**Issue by Trakkasure** [apollographql/subscriptions-transport-ws#259]
The subscribe function from graphql returns a promise that resolves to an AsyncIterator.
This is different than was in 0.10.5, and thus breaks with an exception in server.ts line 431 with and exception: Cannot read property 'then' of undefined

Normally, this wouldn't be an issue, but the dependencies allow for 0.11.1 to be installed.
    "graphql": "^0.10.1"

When I cloned and installed this repo, it only installed 0.10.5. But, since I added subscriptions to my library after the fact, graphql didn't get downgraded or a warning to that effect didn't occur,  this became a serious pain.

How to reproduce:
Take any existing example and run with graphql 0.11.x and it will fail.

Also, the tests fail in 0.11.1

**Comment by Trakkasure** [comment]
If i would have seen this: https://github.com/graphql/graphql-js/releases/tag/v0.11.0
I would not have spend hours on this problem. :)

**Comment by groundmuffin** [comment]
Why the <subscriptions-transport-ws> package doesn't require the right version of subscribe/execute functions itself?

**Comment by zackify** [comment]
Ohhhh sounds like the issue i made is from this too!!! #269
