### ISSUE TITLE
onOperation documentation is incomplete

### ISSUE THREAD

**Issue by ana0** [apollographql/subscriptions-transport-ws#264]
The documentation for onOperation says

> onOperation?: (message: SubscribeMessage, params: SubscriptionOptions, webSocket: WebSocket) : optional method to create custom params that will be used when resolving this operation

But in order to actually add to the context, the resolved object must be wrapped in a magic context variable

This works:

```
  onOperation: (msg, params, socket) => {
    return new Promise((res, rej) => {
        const verifiedUser = verify(params.authToken);
        res({ context: { user: verifiedUser } });
    })
  },
```

This does not:

```
  onOperation: (msg, params, socket) => {
    return new Promise((res, rej) => {
        const verifiedUser = verify(params.authToken);
        res({ user: verifiedUser });
    })
  },
```

This is not intuitive and should probably be added to the documentation

**Comment by mistic** [comment]
@ana0 thanks your your report. We will take care of it, or you can always help us opening a pull request :)

**Comment by goldo** [comment]
I would also add that you need to pass the `params` back :
```
  onOperation: (msg, params, socket) => {
    return new Promise((res, rej) => {
        const verifiedUser = verify(params.authToken);
        res(Object.assign({}, params, { context: { user: verifiedUser } }));
    })
  },
```

**Comment by agborkowski** [comment]
be watch to override other context params
```
params.context = {...pramas.context, ...{ user: verify(params.authToken) } }
res(params);
```
