### ISSUE TITLE
client.subscribeToMore is not a function

### ISSUE THREAD

**Issue by mjasnikovs** [apollographql/subscriptions-transport-ws#265]
```javascript
const {SubscriptionClient, addGraphQLSubscriptions} = require('subscriptions-transport-ws')
const {ApolloClient, createNetworkInterface} = require('apollo-client')
const ws = require('ws')
const gql = require('graphql-tag')

const networkInterface = createNetworkInterface({
	uri: `http://${HOST}:${PORT}/graphql`
})

const wsClient = new SubscriptionClient(`ws://${HOST}:${PORT}/subscriptions`, {
	reconnect: true
}, ws)

const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
	networkInterface,
	wsClient
)

const client = new ApolloClient({
	networkInterface: networkInterfaceWithSubscriptions
})

	client.subscribeToMore({
		document: gql`
			subscription {
				userSubscription {
					id
					name
				}
			}
		`,
		variables: {
			token: userToken1
		},
		updateQuery: (prev, data) => {
			console.log(data)
		}
	})
```
Error: client.subscribeToMore is not a function

change it to subscribe

```javascript
	client.subscribe({
		document: gql`
			subscription {
				userSubscription {
					id
					name
				}
			}
		`,
		variables: {
			token: userToken1
		},
		updateQuery: (prev, data) => {
			console.log(data)
		}
	})
```

Error: Cannot read property 'kind' of undefined

Im ussing apollo client inside node

**Comment by Tobino** [comment]
Hello

I have made a [PR #266](https://github.com/apollographql/subscriptions-transport-ws/pull/266) to fix documentation. Change option `document` with `query`, it might work. If it doesn't, please let me know because it could an accumulation of different error. Thank you

Jérôme 

```js
	client.subscribe({
		query: gql`
			subscription {
				userSubscription {
					id
					name
				}
			}
		`,
		variables: {
			token: userToken1
		},
		updateQuery: (prev, data) => {
			console.log(data)
		}
	})
```

I currently using `wsClient.subscribe` but I am facing other issues...

**Comment by mjasnikovs** [comment]
Yeh, this is frustrating...

Looking at the source, it should look like this. Maybe?
```javascript
	wsClient.subscribe({
		query: gql`
			subscription {
				userSubscription {
					id
					name
				}
			}
		`,
		variables: {
			token: userToken1
		}
	},
	(err, result) => {
		console.log(err, result)
	})
```

**Comment by Tobino** [comment]
Same problem, `__typeName` is not present and even if it's added on subscription, cache is not updated automatically.

I tried to switch to `Full WebSocket Transport` with `client`, `query` and `mutation` works fine expect `subscription`.

I will try to look under the hood with apolloClient and methods subscription.

**Comment by Tobino** [comment]
Hello @mjasnikovs 

I just add a pull request with 2 examples for subscribe and subscribeToMore. wsClient was great to debug my graphQL server, but it's not suitable for production application.

Those examples add `__typeName` and Redux cache is updated automatically if an `id` is provided.

**Comment by perrosnk** [comment]
@Tobino please add a note that your example won't work with apollo-client 2.X version
