### ISSUE TITLE
TypeError: eventemitter3_1.EventEmitter is not a constructor

### ISSUE THREAD

**Issue by mjasnikovs** [apollographql/subscriptions-transport-ws#267]
![image](https://user-images.githubusercontent.com/12757881/30097247-5d017250-92e5-11e7-8b92-4e80fb6b81cf.png)

```javascript
client.js:47 Uncaught TypeError: eventemitter3_1.EventEmitter is not a constructor
    at new SubscriptionClient (client.js:47)
    at Object../src/index.js (index.js:33)
    at __webpack_require__ (bootstrap b03e71f0b0db94868ce6:669)
    at fn (bootstrap b03e71f0b0db94868ce6:87)
    at Object.0 (splashscreen.js:10)
    at __webpack_require__ (bootstrap b03e71f0b0db94868ce6:669)
    at bootstrap b03e71f0b0db94868ce6:715
    at bundle.js:719
```

To fix, had to manually install 
```
npm install --save eventemitter3@2.0.3
```

**Comment by mistic** [comment]
@mjasnikovs what's the version where this thing happened to you? Is it still happening now? Have u tried a clean `npm install` ?

**Comment by tujoworker** [comment]
Yes, this happens still on the latest version `0.9.1`. Clean install did not help by the way.

**Comment by mjasnikovs** [comment]
@mistic Just created a new project, same issue in 2018.
I googled error, and find my own answer :/

**Comment by wizbooth** [comment]
I have the same problem.

**Comment by miguelcaravantes** [comment]
https://github.com/apollographql/GitHunt-Angular/issues/100

**Comment by miguelcaravantes** [comment]
https://github.com/apollographql/subscriptions-transport-ws/issues/99

**Comment by rozsikristof** [comment]
Probably not relevant anymore 2 years later, but if anyone has the same problem I have an answer which worked for me. When you import the eventemitter3 you should do it like this:

**import { EventEmitter } from 'eventemitter3';**

not like this:

import EventEmitter from 'eventemitter3';
