### ISSUE TITLE
Different schema for different users

### ISSUE THREAD

**Issue by PetrSnobelt** [apollographql/subscriptions-transport-ws#270]
Hi, I`d like to use a different schema for different users. 
Based on their roles, they should have available only part of the full schema. 
But now I need to define schema when the server starts. 

I try to replace schema in onSubscribe and onExecute functions, but I still need to provide (now unused) schema param.

What is the correct way to use a different schema for different users?

Thank you

**Comment by DxCx** [comment]
hey @PetrSnobelt you can send some header about the client in connectionParams
then capture the connection request on the server, you should have the payload from client there which you can decide how to handle and return a different schema if needed.

**Comment by PetrSnobelt** [comment]
Yes, I do it this way (I change schema in onSubscribe and onExecute based on context), but When I call  SubscriptionServer.create I do not have information about user available and must provide schema parameter (otherwise it throw an exception, that I cannot provide onExecute)

**Comment by Nainterceptor** [comment]
Hello,

I guess that onSubscribe is onConnect and onExecute is onOperation, can you confirm @PetrSnobelt ?

May be good if first param may be a function like graphqlExpress (apollo-server-express), isn't it ?

I'm using this to send right schema according to user permissions.

**Comment by groundmuffin** [comment]
Hi, the same issue here.
Trying to create different versions of schema dependently of message params, but the schema is a mandatory param on instantiating the server instance and is static on the whole server lifecycle. Did you find some way to do this?

**Comment by PetrSnobelt** [comment]
@groundmuffin Overriding onSubscribe and onExecute works fine, but it is not elegant.
sample code - schema is a function which return schema based on permissions - in our case contextValue.props.pbxRoles

```
const subscriptionsServer = new SubscriptionServer(
    {
      schema: schema(server, []),
      execute: (oldSchema, document, rootValue, contextValue, variableValues, operationName) => {
        const schemaWithRoles = schema(server, contextValue.props.pbxRoles)
        return Graphql.execute(schemaWithRoles, document, rootValue, contextValue, variableValues, operationName)
      },
      subscribe: (oldSchema, document, rootValue, contextValue, variableValues, operationName) => {
        const schemaWithRoles = schema(server, contextValue.props.pbxRoles)
        return Graphql.subscribe(schemaWithRoles, document, rootValue, contextValue, variableValues, operationName)
      },
      keepAlive: 9000,
...
```
