### ISSUE TITLE
Log subscription response

### ISSUE THREAD

**Issue by PetrSnobelt** [apollographql/subscriptions-transport-ws#271]
Hello, 
is there any way how I can log subscription result to console? If possible with subscription name?

Thanks

**Comment by vlasenko** [comment]
@PetrSnobelt Please check
https://github.com/sysgears/apollo-logger
for that

**Comment by PetrSnobelt** [comment]
Thank you @vlasenko I create my own version based on that. 
Because I use https://www.npmjs.com/package/debug instead of console.log for debugging
