### ISSUE TITLE
0.9.0 requires apollo-client beta?

### ISSUE THREAD

**Issue by altschuler** [apollographql/subscriptions-transport-ws#276]
0.9.0 changes the signature of `SubscriptionClient` to be an apollo-link (as far as I understand?). This breaks compatability with Apollo Client<2.0.0 (which is only in beta at this moment) if we want to use full ws transport. Is this correct?

**Comment by strattadb** [comment]
I believe that's correct. From what I could see, `ApolloClient` before version 2 requires a network interface with functions (e.g. `query`) that have been removed since `0.9.0`.

**Comment by altschuler** [comment]
Cool, that's what I gathered as well. That means 0.9.0 is not really usable until Apollo Client 2 gets released.

Might be good to note that in the changelog :)

**Comment by tim-soft** [comment]
Yea, seems like a pretty breaking change

**Comment by mistic** [comment]
I’ll take care of the missing documentation soon guys
