### ISSUE TITLE
Update Readme for v0.9.0

### ISSUE THREAD

**Issue by nickofthyme** [apollographql/subscriptions-transport-ws#284]
Update Readme to reflect breaking changes from v0.9.0

- BREAKING CHANGE: Remove support for Subscription Manager PR #261 
- BREAKING CHANGE: Remove support for all deprecated API PR #272

**Comment by mistic** [comment]
@nickofthyme I'm working on this

**Comment by gustavofulton** [comment]
@mistic please update readme as soon as possible. Trying to integrate subscriptions on my ionic app but can't because the documentation is outdated. Thanks!

**Comment by perrosnk** [comment]
Any updates on this?

**Comment by Janung** [comment]
when?
