### ISSUE TITLE
Full WebSocket Transport - this.networkInterface.query is not a function

### ISSUE THREAD

**Issue by lgxpgx** [apollographql/subscriptions-transport-ws#287]
Hi, I can make the hybrid approach work but I want to use the full websocket transport.

```javascript
import { SubscriptionClient } from 'subscriptions-transport-ws'
import ApolloClient from 'apollo-client'
import gql from 'graphql-tag'

const client = new SubscriptionClient('ws://localhost:5000/graphql', { reconnect: true })
const apolloClient = new ApolloClient({ networkInterface: client })

apolloClient.query({
  query: gql`query { app }`
})
```

It gives me the error

```
Uncaught (in promise) Error: Network error: this.networkInterface.query is not a function
    at new ApolloError (ApolloError.js:34)
    at QueryManager.js:325
    at QueryManager.js:818
    at Array.forEach (<anonymous>)
    at QueryManager.js:815
    at Array.forEach (<anonymous>)
    at QueryManager.broadcastQueries (QueryManager.js:812)
    at QueryManager.js:281
    at <anonymous>
```

Thanks.

**Comment by mistic** [comment]
@lgxpgx I'm working on new documentation to address this problems, however just notes the following:

- if you are using subscriptions-transport-ws@0.9.x you should use apollo-client@2.x.x. On this version you should construct an apollo-link with the subscriptions-transport-ws client and use it to build the apollo client. 

- if you are using the apollo-client@1.X.X then you should use the subscriptions-transport-ws@0.8.3 and everything should works fine :)

Can u try this please?

**Comment by lgxpgx** [comment]
@mistic Using subscriptions-transport-ws@0.8.3 works. I've tried the new approach but couldn't make it work, so I'll use the old way for now. Thanks for the help.
