### ISSUE TITLE
No reconnection attempts if you turn network link off and on

### ISSUE THREAD

**Issue by thehappycoder** [apollographql/subscriptions-transport-ws#291]
I wanted to test if my `reconnected` handler works but couldn't by turning network off on my computer for `timeout * reconnectionAttempts` number of milliseconds. It didn't emit any `disconnected` nor reconnection events.

Is it a bug?

Is there other way to test reconnection path?

**Comment by bginsburg** [comment]
i noticed that the reconnected will only be called if you are using the KeepAlive option on the server side.

**Comment by Jp3rd** [comment]
I have the same issue and I notice it only emits disconnect/ reconnect if the server goes offline/online.
