### ISSUE TITLE
Updating authorization header [Question]

### ISSUE THREAD

**Issue by perrosnk** [apollographql/subscriptions-transport-ws#298]
I am trying to implement authentication in Graphql using firebase and websockets (on react native).

The client uses the firebase to authenticate and gets a token. It then sends the token to the server over a websocket client, which validates the user using the admin sdk.

I am facing two problems:

1. When the app boots up, it establishes a ws connection which by that time, it has no authorization header. The user gets a token after a while using firebase.
2. The token expires after some time, so after a while I need to update the authorization header in the websocket connection, and re-run the query, mutation or subscription which got rejected because of the expired token.

Is there a way to update the authorization header and re-run the query?

Do I need to close the previous connection and open a new one using the new token in the authorization header? How is this done?

I am using apollo-server, apollo-client, apollo-link, subscriptions-transport-ws.

**Comment by matiasniz** [comment]
Apollo Client 2.0.1? 
Español...
Yo utilizo para ese caso una estrategia de refreshToken, este se almacena en memoria en el servidor, o en una base de datos, y al momento de expirar el token, verifica el refresh token si sigue activo en la db, y si es asi le genera un nuevo token y se lo manda al cliente.

Si utilizas la version 2.0.1 como has pasado el token en el header para las subscripciones?

**Comment by perrosnk** [comment]
@matiasniz I don't speak Spanish unfortunately..
