### ISSUE TITLE
How to use subscriptions with Apollo Client 2.0?

### ISSUE THREAD

**Issue by nikolasburk** [apollographql/subscriptions-transport-ws#302]
Apollo Client 2.0 doesn't use the `NetworkInterface` any more and instead makes use of `Link`s. The [only documented way](http://dev.apollodata.com/react/subscriptions.html#subscriptions-client) of getting subscriptions to work however does use the `NetworkInterface`, so there's no documented way of getting subscriptions to work other. 

What does the setup process look like for subscriptions in the context of Apollo Client 2.0?

**Comment by jbaxleyiii** [comment]
👋 hey @nikolasburk! The update docs for subscriptions are [here](https://www.apollographql.com/docs/react/features/subscriptions.html#subscriptions-client) but in short, there is a link specifically dedicated to using this library [here](https://www.apollographql.com/docs/link/links/ws.html)
