### ISSUE TITLE
Where is addGraphQLSubscriptions

### ISSUE THREAD

**Issue by ticruz38** [apollographql/subscriptions-transport-ws#303]
Seems like this guy only exist in the readme.md, has it been deprecated?

**Comment by Froncz** [comment]
+1

**Comment by Froncz** [comment]
`import { split } from 'apollo-link';
import { HttpLink } from 'apollo-link-http';
import { WebSocketLink } from 'apollo-link-ws';
import { getMainDefinition } from 'apollo-utilities';

// Create an http link:
const httpLink = new HttpLink({
  uri: 'http://localhost:3000/graphql'
});

// Create a WebSocket link:
const wsLink = new WebSocketLink({
  uri: `ws://localhost:5000/`,
  options: {
    reconnect: true
  }
});

// using the ability to split links, you can send data to each link
// depending on what kind of operation is being sent
const link = split(
  // split based on operation type
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    return kind === 'OperationDefinition' && operation === 'subscription';
  },
  wsLink,
  httpLink,
);`

**Comment by bardiel** [comment]
Indeed. It's been long deprecated. And, as @Froncz just exampled, if you just want to use WebSockets for your Subscriptions, you shouldn't have to use this package directly, instead `apollo-link-ws`; by using the new API for `Link`s.

**Comment by ticruz38** [comment]
yeah I found out how to do it in apollo2.0 doc, it would be cool to update the readme though as it is completely outdated and lead to the wrong path
