### ISSUE TITLE
When using subscribe, in case of an error it will only show [object object]

### ISSUE THREAD

**Issue by itai-codefresh** [apollographql/subscriptions-transport-ws#305]
I have just now started using the subscriptions and so far it looks preety cool.

I came to a problem that graphiql will not show errors in case i have a wrong subscription query.
I checked the websockets frames and it seems like after the frame that contains the error, i am always getting another frame that a null object.

this is how my frames look:

![image](https://user-images.githubusercontent.com/10414627/33048942-339a2fbc-ce66-11e7-9f6a-0a964285b228.png)

![image](https://user-images.githubusercontent.com/10414627/33048959-637761e6-ce66-11e7-8449-869219c2efd8.png)

Any idea what i am doing wrong?

**Comment by Kivutar** [comment]
I confirm this bug.
