### ISSUE TITLE
GraphQL response extensions

### ISSUE THREAD

**Issue by thepwagner** [apollographql/subscriptions-transport-ws#317]
As a subscriptions-transport-ws user,
I want to receive GraphQL response extensions like Apollo `tracing`/`cacheControl`,
So that Apollo Engine can extract trace information and cache responses transported over WebSocket.

**Comment by jamiehill** [comment]
Not sure if there's further tickets on this subject, but having spent a fair bit of time getting Apollo Engine up and running, can't find a way of hooking into this module.

Can anyone direct me to instructions on doing this, or indeed, confirm that at present, is not possible?

**Comment by thepwagner** [comment]
Here's a workaround I used:

```
import { runQuery } from 'apollo-server-core';
SubscriptionServer.create(
     {	     {
       schema,
      execute: (querySchema, query, rootValue, context, variables, operationName, fieldResolver) =>
        runQuery({
          schema: querySchema,
          query,
          rootValue,
          context,
          variables,
          operationName,
          fieldResolver,
          tracing: true,
          cacheControl: true,
        }),
     }
```

It's pretty rough, but the idea is to stub in `runQuery()` to the `execute()` function.

Unfortunately Apollo Engine doesn't currently instrument WebSocket traffic, so even if WebSocket returns tracing/cache information, Engine won't consume it.
(related but migrated https://github.com/apollographql/apollo-engine-js/issues/33 )

**Comment by jamiehill** [comment]
Thanks for that @thepwagner, managed to arrive at a carbon copy of this earlier!

**Comment by thepwagner** [comment]
I don't think this is as relevant with https://github.com/apollographql/apollo-server/tree/version-2/packages/apollo-engine-reporting inlining reporting (making it transport-agnostic).
