### ISSUE TITLE
Add and example of client-server interaction in README

### ISSUE THREAD

**Issue by OlegIlyenko** [apollographql/subscriptions-transport-ws#32]
Thanks for putting this together! It's an awesome initiative! 🏆 

I find it always very helpful to have a concrete example of client-server interaction for these kind of protocols. (just a JSON message exchange example)

Also, just a minor thing: based on the information provided in the README, it was not immediately clear how `type` is encoded in the protocol. After looking in the source code I realized that it's just a property of a message itself. Maybe it's worth mentioning it or showing in in some more obvious way in the README?

**Comment by stubailo** [comment]
I completely agree! I'll try to update these docs tonight or tomorrow to be more clear, both in the `type` field and an example of a start-to-finish interaction.

**Comment by Urigo** [comment]
Updated the README in https://github.com/apollographql/subscriptions-transport-ws/commit/b144779dfece99d8ecdf76593c0535ba34c37493
