### ISSUE TITLE
Node compatibility

### ISSUE THREAD

**Issue by ZaninAndrea** [apollographql/subscriptions-transport-ws#321]
Is there a way to make the SubscriptionClient work in node?
I tried passing the `websocket` module as websocket implementation when creating a new SubscriptionClient, but with no luck.

Also why can I use the SubscriptionServer without issues, but when I try using the SubscriptionClient it complains that `Unable to find native implementation, or alternative implementation for WebSocket!`.

Thanks in advance for the help.

**Comment by NeoPhi** [comment]
This is the basic syntax for using the `SubscriptionClient` in node:
```
import WebSocket from 'ws';
import { SubscriptionClient } from 'subscriptions-transport-ws';
const client = new SubscriptionClient('wss://', {}, WebSocket);
```
Flesh out the URL and options as needed.
