### ISSUE TITLE
Sourcemaps link to files that are not published

### ISSUE THREAD

**Issue by pimterry** [apollographql/subscriptions-transport-ws#323]
The published JS output (e.g. `dist/protocol.js`) reference their sourcemaps (`dist/protocol.js.map`) which reference their original source (`../src/protocol.ts`).

The typescript files aren't published though, because `src/` is in `.npmignore`, so sourcemapping doesn't work, and many tools like webpack produce warnings on every build complaining about each subscriptions-transport-ws file, because they can't read the sourcemap.

It'd be nice to publish the source to npm, so these warnings go away.

**Comment by cazzer** [comment]
Still an issue nearly two years later...is there a different module we should be using?

**Comment by smeijer** [comment]
Can we please just publish the `ts` file as well? Or not publish the source maps either? The source maps are useless this way as they point to the incorrect (non existing) source files.
