### ISSUE TITLE
addGraphQLSubscriptions issue

### ISSUE THREAD

**Issue by luthfirrahmanb** [apollographql/subscriptions-transport-ws#324]
Hi guys i've got an error like this `TypeError: Object(...) is not a function`
and my code like this

`const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
    wsClient,
    networkInterface
)`

any ideas? i'm really confused

**Comment by naokikurosawa** [comment]
I tried to find out this because I have same problem.

`addGraphQLSubscriptions` was deprecated. And it was removed since v0.9.0.
README doc is stale for a long time! :-(

**Comment by NeoPhi** [comment]
Closing as duplicate of https://github.com/apollographql/subscriptions-transport-ws/issues/284
