### ISSUE TITLE
Compatibility with graphql 0.12

### ISSUE THREAD

**Issue by kbrandwijk** [apollographql/subscriptions-transport-ws#325]
According to the package.json, this package is only compatible with graphql <= 0.11. Is anything needed to make this compatible with 0.12. And if not, can the dependencies be updated?

**Comment by NeoPhi** [comment]
Hope to address this with https://github.com/apollographql/subscriptions-transport-ws/pull/327

**Comment by NeoPhi** [comment]
https://github.com/apollographql/subscriptions-transport-ws/releases/tag/v0.9.5 has been released with support for GraphQL 0.12.X.
