### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by kbrandwijk** [apollographql/subscriptions-transport-ws#328]
I'm trying to add proxy support to the websocket connection, but the `wsImpl` does not allow me to pass in a websocket instance. So I have no way to provide an `agent` option. I would like to be able to do:
```js
const subscriptionClient = new SubscriptionClient(
    wsEndpoint,
    { reconnect: true },
    new ws(wsEndpoint, { agent: new HttpsProxyAgent('http://proxyurl') }),
  )
```

**Comment by n1ru4l** [comment]
Maybe you could extend the WebSocket "class" and use `super` inside the constructor to apply your custom configuration as a workaround.

**Comment by kbrandwijk** [comment]
Thank you @n1ru4l I'll try that.
