### ISSUE TITLE
Where to instantiate data loaders?

### ISSUE THREAD

**Issue by mxstbr** [apollographql/subscriptions-transport-ws#330]
I'm using this package in combination with a bunch of DataLoaders. At the moment, I just do the following:

```JS
SubscriptionServer.create({
  onConnect: () => ({ loaders: createDataLoaders() })
})
```

I thought that would get me unique dataloaders per query, but it actually gets me unique dataloaders _per update_. (which makes sense in hindsight) The issue is that if the same record is updated twice while a user stays subscribed throughout, they'll get stale data the second time the record is updated because the DataLoader will just return the value from its cache.

Really, what I want for my dataloaders is for them to be created every time a record is changed to avoid stale reads. How do I do that? (it's not `onConnect`, but it's also not `onOperation` since that runs once per subscription, which is also not what I need)

**Comment by NeoPhi** [comment]
This is a design issue with graphql. Some possible workarounds are listed in: https://github.com/graphql/graphql-js/issues/894

**Comment by mxstbr** [comment]
Ugh, god dammit. Alright, nothing to see here folks—thank you @NeoPhi!

**Comment by ash0080** [comment]
any update?
