### ISSUE TITLE
[Firefox] SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by KaiWedekind** [apollographql/subscriptions-transport-ws#332]
I'm getting the following error in Firefox when I open /graphiql. I'm using Firefox version 52.5.3 (64-bit). I don't get that error in Chrome and Safari.

<img width="795" alt="screenshot at jan 10 17-52-59" src="https://user-images.githubusercontent.com/12070900/34784640-26aefff8-f62f-11e7-90c2-26ef1ea92ace.png">

Anyone here who can help me to fix that?

**Comment by quentinus95** [comment]
Hi!

I'm facing this issue too, only on Firefox (Quantum 60.0.1 (64 bits)).

**Comment by NeoPhi** [comment]
Do you have a sample repo that demonstrates this bug?

**Comment by poupapaa** [comment]
It's not a bug, it's a feature ;-)

See here for a fix: https://stackoverflow.com/a/12042843

**Comment by faisolriza** [comment]
this helps me so much as a user https://stackoverflow.com/a/63831245/14579016
