### ISSUE TITLE
Expose `tryReconnect` method of SubscriptionsClient

### ISSUE THREAD

**Issue by stalniy** [apollographql/subscriptions-transport-ws#340]
### Issue

Currently this method is private and I use a bit dirty solution (with `any` in TS) to call this method. It seems reasonable to expose it as public method.

### Why?

In scenarios where user may loose connection and be offline for several hours or days, I'd like to be able to reestablish connection with websocket as soon as device appears online again. To achieve this I can use HTML5 api

### Example

```js
window.addEventListener('online', () => client.tryReconnect())
```

**PS: ** `close` method doesn't work for me because it checks if `this.client` is `null`. In scenarios like this I expect `client` to be `null`

**Comment by ujwal-setlur** [comment]
Thanks, I was about to open this issue. Other use case is logout/login and the auth token has changed.
