### ISSUE TITLE
Get no. of connected clients to a subscription 

### ISSUE THREAD

**Issue by gijo-varghese** [apollographql/subscriptions-transport-ws#343]
I'm building a chat widget where the users will be subscribed to the following subscription. For each user, the 'user_id' will be different

`subscription {
  newUserMessage(user_id: 123) {
    id,
    content,
    type,
  }
}`

I want to find whether a user is online or not. So is there any way to find the number of clients connected to a particular subscription? Or is there a better way?

**Comment by gijo-varghese** [comment]
Or in other words I just want to know whether a user is online or not..

**Comment by gijo-varghese** [comment]
The only way I found is to use the hooks onConnect and onDisconnect that will have the cookies from headers. which I can use to increment user's count in Redis or something. So if the count is zero, he is offline. If its greater than one he is online. However, there is an issue. What if the server crashes or the new code is deployed. The onDisconnect will not be called and the users will be rerouted to another instance. From there it will again call onConnect which results in an incorrect count in redis.

**Comment by NeoPhi** [comment]
Right now there is no connection tracking as that will vary widely based on the server implementation used when distributed across multiple subscription servers. One idea for your approach would be to setup an interval that fires on a regular basis during `onConnect` to update a value in Redis that indicates that the user has an subscription. Should a server crash that interval would stop firing.
