### ISSUE TITLE
Send KeepAlives from client to server ?

### ISSUE THREAD

**Issue by dobesv** [apollographql/subscriptions-transport-ws#350]
It seems like nginx has separate timeouts on I/O in both directions, upload and download.  So if the client doesn't send keepalives, it will eventually be disconnected forcefully.

**Comment by bradleybeighton** [comment]
Is there a suggested solution for this? My Angular UI keeps getting disconnected from the server in live.

**Comment by dobesv** [comment]
Our solution was switching to HAProxy, we can set a really long I/O timeout and it doesn't kill all websocket connections on reconfiguration.

**Comment by intellix** [comment]
I'm doing it like this on the client:

```
setInterval(() => subscriptionClient.client.send('{"type":"ka"}'), 90 * 1000);
```

**Comment by Valdenirmezadri** [comment]
> I'm doing it like this on the client but we have a custom server that accepts `GQL_CONNECTION_KEEP_ALIVE` messages and does nothing with them:
> 
> ```ts
> setInterval(() => {
>   if (subscriptionClient.status === 1) {
>     subscriptionClient.client.send('{"type":"ka"}');
>   }
> }, 90 * 1000));
> ```

if the server not respond, then the subscriptions-transport-ws restart itself?
