### ISSUE TITLE
Not found addGraphQLSubscriptions

### ISSUE THREAD

**Issue by sklukin** [apollographql/subscriptions-transport-ws#353]
Not found `addGraphQLSubscriptions`, but doc contain this
https://github.com/apollographql/subscriptions-transport-ws#hybrid-websocket-transport
```
// Extend the network interface with the WebSocket
const networkInterfaceWithSubscriptions = addGraphQLSubscriptions(
    networkInterface,
    wsClient
);
```
What?

**Comment by serranoarevalo** [comment]
@sklukin  how did you solve this?

**Comment by sklukin** [comment]
Solved. Thanks

**Comment by ArnaudValensi** [comment]
@sklukin how did you solve this? I experience the same here.

**Comment by mxstbr** [comment]
Network Interfaces are no longer a thing as of Apollo Client v2, you'll have to use the `apollo-link-ws`!

**Comment by sklukin** [comment]
@ArnaudRinquin eee its old version and wrong docs. Have fun, bro

**Comment by ArnaudRinquin** [comment]
@sklukin I don't think you've mentioned the right Arnaud.
