### ISSUE TITLE
Observed immediate disconnect event when try connect

### ISSUE THREAD

**Issue by schavaLogi** [apollographql/subscriptions-transport-ws#354]
Observation: When connect the checkMaxConnectTimeout() triggers close() in 1.2 sec and emits disconnect event

version: "subscriptions-transport-ws": "^0.9.4"

When we try to connect I observed immediate disconnect event due to checkMaxConnectTimeout() in connect method. It waits for 's 1.2 sec and then trigger disconnect and then retry. 

In RN application connection never success due to this. In case if i disable to checkMaxConnectTimeout() we are getting connected.

**Comment by perrosnk** [comment]
How do you disable the checkMaxConnectTimeout()? 
I have opened an issue https://github.com/apollographql/subscriptions-transport-ws/issues/359, because in my case I get connected when using iOS or Android api >20, but fails on android api <20.

Have you tested on older versions of android?

**Comment by schavaLogi** [comment]
timeout increased to 30 sec to avoid disconnect

**Comment by perrosnk** [comment]
@schavaLogi isn't the [default](https://github.com/apollographql/subscriptions-transport-ws#constructorurl-options-websocketimpl) set to 30s?

**Comment by schavaLogi** [comment]
@perrosnk actully i overritten with custom as per our server ka packet 8sec initially that caused the issue some times. Yes default is 30sec.
