### ISSUE TITLE
[Auth] ApolloLink middleware not able to set context to server's onOperation

### ISSUE THREAD

**Issue by strblr** [apollographql/subscriptions-transport-ws#358]
Hi

I'm jumping into what seems a common issue : sending authentication token to the server through WebSocket, but not on connection (since the user is NOT authenticated on connection).

I've read a lot of threads about this topic here, and here are the workarounds I saw : 

- Option 1 : Refreshing the page after login, forcing a new fresh socket connection with auth token available.
- Option 2 : Restarting socket connection manually, and restoring the active subscriptions attached to it (more details here : https://github.com/apollographql/subscriptions-transport-ws/issues/171#issuecomment-307793837).
- Option 3 : Using a middleware to send the token alongside each operation (more details here : https://github.com/apollographql/subscriptions-transport-ws/issues/171#issuecomment-310594855), and maybe using some sort of cache client and server side to improve perfs.

I have a preference for the third option because of its simplicity. I'm trying to implement it using an ApolloLink middleware instead of a SubscriptionClient middleware. This kinda normalizes my link chain. I was inspired by this example : https://www.apollographql.com/docs/react/basics/network-layer.html.

Here is what I have (see authLink) : 

```
const errorLink = onError(({ graphQLErrors }) => {
  if(graphQLErrors)
    graphQLErrors.map(({ message }) => notify.error(message))
})

const stateLink = withClientState({
  cache,
  ...localState
})

const authLink = new ApolloLink((operation, forward) => {
  operation.setContext({
    headers: {
      authorization: localStorage.getItem('liveql-token') || null,
    }
  })
  return forward(operation)
})

const liveLink = new WebSocketLink({
  uri: `ws://localhost:${ SERVER_PORT }/api/liveql`,
  options: { reconnect: true }
})

// Creating the Apollo client

const client = new ApolloClient({
  link: ApolloLink.from([errorLink, stateLink, authLink, liveLink]),
  cache
})
```
Buuut on the server, I'm unable to get the token : 

```
const ws = createServer(express.static('public'))
ws.listen(PORT, () => {
  new SubscriptionServer({
    execute,
    subscribe,
    schema,
    onOperation: (message, params, webSocket) => {
        console.log(params)
        return params
    }
  }, {
    server: ws,
    path: '/api/liveql'
  })
})
```

This logs : 

```
{ query: '....... some query .......',
  variables: { shelf: 16 },
  operationName: null,
  context: {},
  formatResponse: undefined,
  formatError: undefined,
  callback: undefined }
```

`context` is just an empty object. Why is that et what would be a way to solve this ?

Thank you very much.

PS : All my ops, including queries and mutations, go through the websocket. That's a design choice.

**Comment by jamiehill** [comment]
Works ok for me, with the context being passed as a payload on the context:

```
new SubscriptionServer(
      {
        subscribe,
        execute,
        schema,
        onOperation: (message, params, webSocket) => {
          return {
            ...params,
            context: {
              ...message.payload.context, // picked up here
              ...context
            }
          }
        }
      },
      {
        path: '/graphql',
        server
      }
    )
```

**Comment by jamiehill** [comment]
I should also say, that I also had issue configuring using ApolloLink syntax.  Should set up your `Auth` link like so ...

```
  this.wsClient = new SubscriptionClient(uri, {
      cache: new InMemoryCache({
        addTypename: false
      }),
      reconnect: true
    })

    // add middleware to inject session
    this.wsClient.use([{
      applyMiddleware (opts, next) {
        opts.context = {
          token: __super_secret_token__
        }
        next()
      }
    }
    ])
```

**Comment by ostrebler** [comment]
Yep, I also used the payload, but with ApolloLink as I wished : 

```
const authLink = new ApolloLink(
  (operation, forward) =>
    forward(set(operation, 'token', localState.get('token')))
)
```

Server-side, it looks almost like you, only I use lodash's `set` : 
```
ws.listen(PORT, () => {
  new SubscriptionServer({
    execute,
    subscribe,
    schema,
    onOperation: ({ payload: { token } }, params, webSocket) =>
      set(params, 'context.currentUser',
        token && jwt.verify(token, '...') || null
      )
  }, {
    server: ws,
    path: '/api/liveql'
  })
})
```

Works fine.

**Comment by jamiehill** [comment]
Cool, will give that a try

**Comment by ParAnton** [comment]
This issue shows a good solution that worked for me
[https://github.com/apollographql/apollo-server/issues/1505](https://github.com/apollographql/apollo-server/issues/1505)
