### ISSUE TITLE
Websocket support in Android API < 20

### ISSUE THREAD

**Issue by perrosnk** [apollographql/subscriptions-transport-ws#359]
I am not able to connect to the server by using `apollo-link-ws` and `subscriptions-transport-ws` when running android api < 20. It works fine in newer versions and iOS though.
Are older versions not supported or am I doing something something wrong?

**Comment by perrosnk** [comment]
Has anyone tried to run an application in android API < 20? 
It would be very helpful to know if there is something wrong with my code or there is a bug in `subscriptions-transport-ws`.
@NeoPhi Do you have any ideas?

**Comment by perrosnk** [comment]
I have created a small example:

App.js

```javascript
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';
import apolloClient from './socket'


export default class App extends Component<{}> {
  componentDidMount() {
    apolloClient.createClient();
  }
  render() {
    return (
      <View style={styles.container}>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});
```

socket.js
```javascript
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { WebSocketLink } from 'apollo-link-ws';
import { SubscriptionClient } from 'subscriptions-transport-ws';



export default new class ApolloClientStore {
  client = null;

  createClient = async () => {
    console.log('createClient');
    const wsClient = new SubscriptionClient(`wss://api.midoin.com/graphql`, {
      reconnect: true,
      // lazy: true,
      connectionParams: () => ({ authToken: 'user.token' }),
    });

    wsClient.onConnected(() => console.log('onConnected'));
    wsClient.onReconnected(() => console.log('onReconnected'));
    wsClient.onConnecting(() => console.log('onConnecting'));
    wsClient.onReconnecting(() => console.log('onReconnecting'));
    wsClient.onDisconnected(() => console.log('onDisconnected'));

    const link = new WebSocketLink(wsClient);

    const client = new ApolloClient({
      link,
      cache: new InMemoryCache({
        // fragmentMatcher,
        dataIdFromObject: object => object.id,
      }),
      addTypeName: true,
    });
    this.client = client;
  };
}();
```

@evans Can you please take a look?

**Comment by perrosnk** [comment]
EDIT: I cannot connect to the server when it's using Let's encrypt protocol. The app does connect to servers not using this encryption

**Comment by perrosnk** [comment]
EDIT 2: I have opened an issue https://github.com/facebook/react-native/issues/18032 with react-native. It might be that android doesn't include Let's encrypt in the root set of trusted certificates. So a solution could be to use certificate pinning  in order to teach the app that the certificate is OK. There seems to be one available repo https://github.com/localz/react-native-pinch, for pinning, but I cant' see a way to use it with `subscriptions-transport-ws`. Could someone help?

**Comment by thiswhy** [comment]
I have the same problem,anyone had solved this problem? Thanks a lot someone can tell me~

**Comment by perrosnk** [comment]
@thiswhy https://github.com/facebook/react-native/issues/18032#issuecomment-369266431
