### ISSUE TITLE
Websocket closed after 1.5 mins on Android and iOS with React Native

### ISSUE THREAD

**Issue by schavaLogi** [apollographql/subscriptions-transport-ws#372]
- [x] has-reproduction
- [ ] feature
- [ ] docs
- [x] blocking
- [ ] good first issue

Is this a bug report?
Yes

Environment
"react-native": "0.52.0"
"subscriptions-transport-ws": "^0.9.4"

Platform: 
Android & iOS 

Steps to Reproduce:

Connect to WebSocket using SubscriptionClient and WebSocketLink. Wait for 1 ~ 2 mins and see that the socket got closed. All the pending operations are flushed out after re-connect

Android:  
ws.onerror() -> Invoked

iOS:
ws.onclose() -> Invoked

Logs:
client.js:335 SubscriptionClient flushUnsentMessagesQueue
10:02:28.321 redux-logger.js:1  action WS_CLIENT_CONNECTED @ 10:02:28.322
10:02:28.336 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=true
10:02:28.337 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:02:28.560 redux-logger.js:1  action WS_CLIENT_CONNECTED @ 10:02:28.560
10:02:28.577 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:02:28.577 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:02:36.499 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:02:36.541 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:02:36.993 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:02:36.993 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:02:44.492 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:02:44.493 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:02:44.607 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:02:44.608 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:02:52.894 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:02:52.894 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:02:52.903 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:02:52.904 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:00.460 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:00.460 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:00.578 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:00.578 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:08.359 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:08.360 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:08.559 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:08.559 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:16.976 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:16.976 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:16.988 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:16.989 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:24.418 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:24.418 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:24.582 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:24.582 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:32.423 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:32.424 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:32.568 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:32.568 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:40.542 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:40.542 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:40.572 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:40.572 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:48.443 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:48.443 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:48.572 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:48.572 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:57.210 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:57.211 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:57.224 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:03:57.224 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:03:57.385 client.js:382 SubscriptionClient onerror
10:03:57.386 client.js:376 SubscriptionClient onclose _this.closedByUser =false
10:03:57.386 client.js:62 SubscriptionClient close  isForced =false  closedByUser=false
10:03:57.387 client.js:66 SubscriptionClient close final values isForced =false  closedByUser=false
10:03:57.389 client.js:316 SubscriptionClient tryReconnect started
10:03:57.390 client.js:322 SubscriptionClient tryReconnect this.reconnecting=false
10:03:57.403 client.js:382 SubscriptionClient onerror
10:03:57.403 client.js:376 SubscriptionClient onclose _this.closedByUser =false
10:03:57.403 client.js:62 SubscriptionClient close  isForced =false  closedByUser=false
10:03:57.404 client.js:66 SubscriptionClient close final values isForced =false  closedByUser=false
10:03:57.414 client.js:382 SubscriptionClient onerror
10:03:57.414 client.js:376 SubscriptionClient onclose _this.closedByUser =false
10:03:57.414 client.js:62 SubscriptionClient close  isForced =false  closedByUser=false
10:03:57.414 client.js:66 SubscriptionClient close final values isForced =false  closedByUser=false
10:03:57.423 client.js:382 SubscriptionClient onerror
10:03:57.423 client.js:376 SubscriptionClient onclose _this.closedByUser =false
10:03:57.423 client.js:62 SubscriptionClient close  isForced =false  closedByUser=false
10:03:57.424 client.js:66 SubscriptionClient close final values isForced =false  closedByUser=false
10:03:57.433 client.js:382 SubscriptionClient onerror
10:03:57.433 client.js:376 SubscriptionClient onclose _this.closedByUser =false
10:03:57.433 client.js:62 SubscriptionClient close  isForced =false  closedByUser=false
10:03:57.434 client.js:66 SubscriptionClient close final values isForced =false  closedByUser=false
10:03:57.459 client.js:382 SubscriptionClient onerror
10:03:57.460 client.js:376 SubscriptionClient onclose _this.closedByUser =false
10:03:57.460 client.js:62 SubscriptionClient close  isForced =false  closedByUser=false
10:03:57.460 client.js:66 SubscriptionClient close final values isForced =false  closedByUser=false
10:03:57.471 client.js:382 SubscriptionClient onerror
10:03:57.471 client.js:376 SubscriptionClient onclose _this.closedByUser =false
10:03:57.471 client.js:62 SubscriptionClient close  isForced =false  closedByUser=false
10:03:57.472 client.js:66 SubscriptionClient close final values isForced =false  closedByUser=false
10:03:57.981 client.js:358 SubscriptionClient _this.status !== _this.wsImpl.OPEN
10:03:57.981 client.js:62 SubscriptionClient close  isForced =false  closedByUser=true
10:03:57.981 client.js:66 SubscriptionClient close final values isForced =false  closedByUser=true
10:03:58.006 client.js:316 SubscriptionClient tryReconnect started
10:03:58.007 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:58.043 client.js:376 SubscriptionClient onclose _this.closedByUser =true
10:03:58.052 client.js:358 SubscriptionClient _this.status !== _this.wsImpl.OPEN
10:03:58.052 client.js:62 SubscriptionClient close  isForced =false  closedByUser=true
10:03:58.053 client.js:66 SubscriptionClient close final values isForced =false  closedByUser=true
10:03:58.069 client.js:316 SubscriptionClient tryReconnect started
10:03:58.070 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:58.126 client.js:358 SubscriptionClient _this.status !== _this.wsImpl.OPEN
10:03:58.126 client.js:62 SubscriptionClient close  isForced =false  closedByUser=true
10:03:58.126 client.js:66 SubscriptionClient close final values isForced =false  closedByUser=true
10:03:58.142 client.js:316 SubscriptionClient tryReconnect started
10:03:58.143 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:58.169 client.js:358 SubscriptionClient _this.status !== _this.wsImpl.OPEN
10:03:58.169 client.js:62 SubscriptionClient close  isForced =false  closedByUser=true
10:03:58.169 client.js:66 SubscriptionClient close final values isForced =false  closedByUser=true
10:03:58.171 redux-logger.js:1  action WS_CLIENT_RECONNECTING @ 10:03:58.171
10:03:58.177 redux-logger.js:1  action WSS_GET_ENVIRONMENT_INFO @ 10:03:58.177
10:03:58.184 redux-logger.js:1  action GET_ENVIRONMENT_SUCCESS @ 10:03:58.185
10:03:58.188 client.js:316 SubscriptionClient tryReconnect started
10:03:58.188 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:58.869 client.js:358 SubscriptionClient _this.status !== _this.wsImpl.OPEN
10:03:58.869 client.js:62 SubscriptionClient close  isForced =false  closedByUser=true
10:03:58.870 client.js:66 SubscriptionClient close final values isForced =false  closedByUser=true
10:03:58.885 client.js:316 SubscriptionClient tryReconnect started
10:03:58.886 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.001 redux-logger.js:1  action WS_CLIENT_RECONNECTING @ 10:03:59.001
10:03:59.006 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.006 client.js:335 SubscriptionClient flushUnsentMessagesQueue
10:03:59.006 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.007 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.007 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.007 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.007 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.008 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.008 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.008 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.009 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.009 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.009 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.339 redux-logger.js:1  action WS_CLIENT_RECONNECTING @ 10:03:59.339
10:03:59.343 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.343 client.js:335 SubscriptionClient flushUnsentMessagesQueue
10:03:59.343 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.355 redux-logger.js:1  action WS_CLIENT_RECONNECTING @ 10:03:59.356
10:03:59.359 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:03:59.359 client.js:335 SubscriptionClient flushUnsentMessagesQueue
10:03:59.359 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:04:00.221 redux-logger.js:1  action WS_CLIENT_RECONNECTING @ 10:04:00.222
10:04:00.226 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:04:00.226 client.js:335 SubscriptionClient flushUnsentMessagesQueue
10:04:00.227 client.js:302 SubscriptionClient wsImpl.CONNECTING
10:04:00.477 redux-logger.js:1  action WS_CLIENT_RECONNECTING @ 10:04:00.477
10:04:00.480 client.js:335 SubscriptionClient flushUnsentMessagesQueue
10:04:00.754 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:04:00.755 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:04:00.994 client.js:335 SubscriptionClient flushUnsentMessagesQueue
10:04:01.005 client.js:335 SubscriptionClient flushUnsentMessagesQueue
10:04:01.019 client.js:335 SubscriptionClient flushUnsentMessagesQueue
10:04:02.118 redux-logger.js:1  action WS_CLIENT_CONNECTED @ 10:04:02.118
10:04:02.133 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:04:02.133 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:04:02.151 redux-logger.js:1  action WS_CLIENT_CONNECTED @ 10:04:02.152
10:04:02.163 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:04:02.164 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true
10:04:02.520 redux-logger.js:1  action WS_CLIENT_CONNECTED @ 10:04:02.520
10:04:02.536 client.js:437 SubscriptionClient GQL_CONNECTION_KEEP_ALIVE  firstKA=false
10:04:02.536 client.js:343 SubscriptionClient checkConnection this.wasKeepAliveReceived =true

**Comment by Access2emma** [comment]
Has this issue been fixed?

**Comment by schavaLogi** [comment]
Hey, we found a solution for this. we changed our server Loadbalancer idle timeout so that it will disconnect based on idleTimeOut.   as there are no packets between client and server it's closed connection
