### ISSUE TITLE
Reconnect after a cookie update

### ISSUE THREAD

**Issue by gijo-varghese** [apollographql/subscriptions-transport-ws#378]
I've to change user's id in the cookie in a special case. Is it possible to reconnect to the server using a trigger? I found `close() => void`. But no option to connect again

I use `wss.wsServer.clients.forEach()` in server to get list of users connected. Currently, if a cookie is changed, the server won't get that

**Comment by NeoPhi** [comment]
Use `close(false, false)` in the client to reconnect.

**Comment by gijo-varghese** [comment]
@NeoPhi how can I reconnect/close from a vuejs component?

**Comment by NeoPhi** [comment]
You will have to get a reference to the ws client you created and call that method on it. As this is not part of the standard API there is no direct support for it.

**Comment by gijo-varghese** [comment]
@NeoPhi ok. Is that the best method to alert server if a cookie is reset? Any other options?

**Comment by gijo-varghese** [comment]
@NeoPhi after reconnecting subscriptions aren't working

**Comment by jpwilliams** [comment]
@gijo-varghese How are the subscriptions not working?

Are they not being remade or is an error being thrown?

**Comment by ujwal-setlur** [comment]
@NeoPhi, close(false, false) does not work. Subscription is not refreshed. One has to use

close (true, true);
tryReconnect();

That works. Unfortunately, tryReconnect() is not a public API. It should be.

**Comment by ujwal-setlur** [comment]
Actually, I was wrong. 

```
close(false, false);
```

does work after all. I just have to wait a bit for the connection to be re-established before I attempt a subscription.

**Comment by frederikhors** [comment]
@gijo-varghese, can I ask you how to send cookie with this as I can use it in onConnect hook? How to send cookies like in HTTP?

**Comment by gijo-varghese** [comment]
@frederikhors I manually sent cookie data through ws, and I'm moving back to SocketIO. This thing is very buggy
