### ISSUE TITLE
Should @types/graphql be a peer dependency?

### ISSUE THREAD

**Issue by pkeuter** [apollographql/subscriptions-transport-ws#397]
Currently graphql itself is a peer dependency. When using newer typescript definitions (0.13.0), conflicts will occur because it uses it's own definitions for GraphQL (0.11.3). Shouldn't this also be a peer dependency?

**Comment by NeoPhi** [comment]
The library currently supports `"graphql": "^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.1"` so we don't want to dictate which type definition, if any, is required to use it.

**Comment by agborkowski** [comment]
downgrade to     "@types/graphql": "^0.12.7", help a lot and fix issue with:
https://github.com/apollographql/subscriptions-transport-ws/issues/398
https://github.com/apollographql/graphql-subscriptions/issues/100
https://github.com/apollographql/apollo-server/issues/947

**Comment by NeoPhi** [comment]
Anyone aware of how other projects are handling this?

**Comment by NeoPhi** [comment]
Please give https://github.com/apollographql/subscriptions-transport-ws/releases/tag/v0.9.9 a try and see if that resolves this issue.
