### ISSUE TITLE
Conflict with new graphql @types

### ISSUE THREAD

**Issue by 19majkel94** [apollographql/subscriptions-transport-ws#398]
The new `@types/graphql` 0.13 introduce some breaking changes in types. 
So when I try to create subscription server:
```ts
import { SubscriptionServer } from "subscriptions-transport-ws";
import { execute, subscribe, GraphQLSchema } from "graphql";

// ...

const subscriptionServer = SubscriptionServer.create(
  { schema, execute, subscribe },
  { server: websocketServer, path: "/graphql" },
);
```

I got this error:
```
error TS2345: Argument of type '{ schema: GraphQLSchema; execute: { (args: ExecutionArgs): MaybePromise<ExecutionResult>; (schema...' is not assignable to parameter of type 'ServerOptions'.
  Types of property 'execute' are incompatible.
    Type '{ (args: ExecutionArgs): MaybePromise<ExecutionResult>; (schema: GraphQLSchema, document: Documen...' is not assignable to type 'ExecuteFunction | undefined'.
      Type '{ (args: ExecutionArgs): MaybePromise<ExecutionResult>; (schema: GraphQLSchema, document: Documen...' is not assignable to type 'ExecuteFunction'.
```
I think that it's not related to #397 as its about custom type:
```ts
export declare type ExecuteFunction = (schema: GraphQLSchema, document: DocumentNode, rootValue?: any, contextValue?: any, variableValues?: {
    [key: string]: any;
}, operationName?: string, fieldResolver?: GraphQLFieldResolver<any, any>) => Promise<ExecutionResult> | AsyncIterator<ExecutionResult>;
```

**Comment by NeoPhi** [comment]
Will have to look at `@types/graphql@0.13` to see the changes. Seems odd that type also dropped `extensions?` from `ExecutionResult`.

**Comment by darkbasic** [comment]
It's very annoying especially because it doesn't warn you about using an incompatible graphql version.

**Comment by ericmai624** [comment]
Hi,

I'm facing the same issue and want to see if anyone have any recommendations how to fix this.

It seems that `@types/graphql` added `graphqlSync` which is expecting `ExecutionResult` instead of `Promise<ExecutionResult>`.

Adding `ExecutionResult` to return values of `ExecuteFunction` seems to resolve the conflict.

Any suggestions?

**Comment by NeoPhi** [comment]
Anyone aware of how other projects are handling this?

**Comment by awwong1** [comment]
Figured I'd just make the changes and open up a PR. Added `Promise<ExecutionResult>` as a possible type for `ServerOptions.execute` and wrapped this inside a `Promise.resolve` in the `loadExecutor` function.

Also snuck in Node 8.X into travis.yml

**Comment by NeoPhi** [comment]
Please give https://github.com/apollographql/subscriptions-transport-ws/releases/tag/v0.9.9 and see if that resolves this issue.

**Comment by awwong1** [comment]
@NeoPhi Issue no longer appears on 0.9.9
