### ISSUE TITLE
QoS Issues and History Feature!

### ISSUE THREAD

**Issue by dcflow** [apollographql/subscriptions-transport-ws#402]
Hey guys,

One of the first production issues we face when implementing the `ws` is QoS and keeping the data in sync when the internet connection goes off for a period of time. Is it worth it to add a feature to the lib so when it reconnects it queries the list of data created from the moment we lost the connection up to the point of `ws` re-connection. 
If someone plans to add `subscriptions` to their app I'm sure in almost all the cases they will run into this problem. 

Thank You!

**Comment by NeoPhi** [comment]
This falls under the general problem of data syncing which based on the semantics of your schema does not have a general solution. Some of the questions that come to mind for any approach include: How long can a client be offline and still replay lost traffic? Handling an unsubscribe versus an unclean disconnect? Is the client still allowed to make the same subscription?

**Comment by dcflow** [comment]
Hey @NeoPhi ,
Thank you for your response.
I know there are some underlying issues that need to be solved .. but still everyone is going to try to fix them by writing some boilerplate code that I'm sure it will be so similar that can be abstracted away.
