### ISSUE TITLE
Cannot use GraphQLSchema [object Object] from another module or realm.

### ISSUE THREAD

**Issue by elie222** [apollographql/subscriptions-transport-ws#411]
I'm trying to get this package working with graphiql, but with a simple example I get this error:

```json
{"type":"error","id":"1","payload":{"message":"Cannot use GraphQLSchema \"[object Object]\" from another module or realm.\n\nEnsure that there is only one instance of \"graphql\" in the node_modules\ndirectory. If different versions of \"graphql\" are the dependencies of other\nrelied on modules, use \"resolutions\" to ensure only one version is installed.\n\nhttps://yarnpkg.com/en/docs/selective-version-resolutions\n\nDuplicate \"graphql\" modules cannot be used at the same time since different\nversions may have different capabilities and behavior. The data from one\nversion used in the function from another could produce confusing and\nspurious results."}}
```

Packages used:

```json
"dependencies": {
    "apollo-server-express": "^1.3.6",
    "body-parser": "^1.18.2",
    "cors": "^2.8.4",
    "dotenv": "^5.0.1",
    "express": "^4.16.3",
    "graphql": "^0.13.2",
    "graphql-tools": "^3.0.0",
    "graphql-type-json": "^0.2.1",
    "mongodb": "^3.0.7",
    "mongoose": "^5.0.16",
    "promise-retry": "^1.1.1",
    "web3": "^1.0.0-beta.34"
  },
```

I've tried this to no avail either:
https://github.com/graphcool/graphql-yoga/issues/162#issuecomment-367368045

**Comment by NeoPhi** [comment]
What is the output of running `npm ls | grep graphql` in your project?

**Comment by elie222** [comment]
```sh
⚡ npm ls | grep graphql
│ │ │ └── graphql-extensions@0.0.10 deduped
│ │ │ └── graphql-extensions@0.0.10 deduped
│ │ └─┬ graphql-extensions@0.0.10
├─┬ graphql@0.13.2
├─┬ graphql-tools@2.24.0 invalid
├── graphql-type-json@0.2.1
npm ERR! extraneous: node-pre-gyp /....../node_modules/node-pre-gyp
npm ERR! error in /....../node_modules/node-pre-gyp: ENOENT: no such file or directory, open '/....../node_modules/node-pre-gyp/package.json'
npm ERR! invalid: graphql-tools@2.24.0 /....../node_modules/graphql-tools
npm ERR! extraneous: apollo-link@1.2.2 /....../node_modules/apollo-link
npm ERR! extraneous: apollo-utilities@1.0.12 /....../node_modules/apollo-utilities
npm ERR! extraneous: deprecated-decorator@0.1.6 /....../node_modules/deprecated-decorator
```

**Comment by NeoPhi** [comment]
I would resolve the `npm  ERR!` to see if that fixes the issue. Might need to remove your existing node_modules and reinstall.

**Comment by elie222** [comment]
Thanks. That node-gyp stuff has been mad annoying recently.

**Comment by crupayan0** [comment]
i have the same error and "npm ls | grep graphql" did not show any errors. How do i resolve the issue?

        project-with-node-1/error

**Comment by crupayan0** [comment]
https://gist.github.com/crupayan0/9700dc8dc381757f07230781542ed249

**Comment by crupayan0** [comment]
<script src="https://gist.github.com/crupayan0/9700dc8dc381757f07230781542ed249.js"></script>

**Comment by crupayan0** [comment]
https://gist.github.com/crupayan0/9700dc8dc381757f07230781542ed249

**Comment by crupayan0** [comment]
project-with-node-1/error

**Comment by e2goon** [comment]
![image](https://user-images.githubusercontent.com/45934/81580773-d4328d80-93e8-11ea-9ea0-3a0d14c695eb.png)

![image](https://user-images.githubusercontent.com/45934/81580810-ddbbf580-93e8-11ea-865b-a3dd7e4ab896.png)

**Comment by sakshisharma155** [comment]
I have an error :- "message": "Cannot use GraphQLSchema \"[object GraphQLSchema]\" from another module or realm.\n\nEnsure that there is only one instance of \"graphql\" in the node_modules\ndirectory. If different versions of \"graphql\" are the dependencies of other\nrelied on modules, use \"resolutions\" to ensure only one version is installed.\n\nhttps://yarnpkg.com/en/docs/selective-version-resolutions\n\nDuplicate \"graphql\" modules cannot be used at the same time since different\nversions may have different capabilities and behavior. The data from one\nversion used in the function from another could produce confusing and\nspurious results." 

can u please let me know what the actual error is

**Comment by 103cuong** [comment]
The same issue.
My dependencies:
```json
"dependencies": {
    "@types/lodash": "^4.14.149",
    "apollo-link-ws": "^1.0.20",
    "apollo-utilities": "^1.3.4",
    "body-parser": "^1.19.0",
    "bson": "^4.0.4",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "graphql": "^15.0.0",
    "graphql-playground-middleware-express": "^1.7.18",
    "graphql-subscriptions": "^1.1.0",
    "graphql-tools": "^6.0.15",
    "graphql-upload": "^11.0.0",
    "grpc-graphql-sdk": "^0.1.0",
    "helmet": "^3.22.0",
    "ioredis": "^4.17.3",
    "jackson-js": "^1.1.0",
    "lodash": "^4.17.15",
    "serialize-javascript": "^4.0.0",
    "serializr": "^2.0.3",
    "subscriptions-transport-ws": "^0.9.17",
    "surrial": "^2.0.2",
    "ws": "^7.3.1",
    "zeebe-node": "^0.23.0-alpha.4"
  }
```

**Comment by aimamisa** [comment]
In my case, realized I was using graphql v15.x.x in my application package.json while graphql-yoga was using graphql v14.x.x. Deleted the v15.x.x and replaced it with v14.x.x works. That created a single graphql v14.x.x to be used.

Hope this helps.
