### ISSUE TITLE
index is not exporting MessageTypes

### ISSUE THREAD

**Issue by sneko** [apollographql/subscriptions-transport-ws#412]
Hi,

I try to use this line in a .ts file:
`import { SubscriptionClient, MessageTypes } from 'subscriptions-transport-ws'`

But it tells me that MessageTypes is not exported by index.

I tried with versions 0.9.5 and 0.9.9

Thanks

**Comment by kafkahw** [comment]
I'm facing the same issue here as well. I think it can be easily fixed by update the export statement for message-types [here](https://github.com/apollographql/subscriptions-transport-ws/blob/190fd674ddf13a1d8b32b25193e207d3814da9b5/src/index.ts#L3)

from
```js
export * from './message-types';
```
to 
```js
export { default as MessageTypes } from './message-types';
```

**Comment by alfaproject** [comment]
Just stumbled upon this issue as well ):

**Comment by austin-beer** [comment]
I would like to see this issue fixed as well!
