### ISSUE TITLE
Cannot read property kind of undefined

### ISSUE THREAD

**Issue by raghuprathap** [apollographql/subscriptions-transport-ws#414]
[Code gist](https://gist.github.com/raghuprathap/fd5415d0e696c1f6174d518777f11b13)
[Code Repo](https://github.com/sagarpatke/apollo-graphql-subscription-issue)
- [x] has-reproduction
- [x] blocking

**Comment by NeoPhi** [comment]
As noted by the React prop checking output:
```
index.js:2178 Warning: Failed prop type: The prop `subscription` is marked as required in `Subscription`, but its value is `undefined`.
    in Subscription (at Books.js:71)
    in Books (at index.js:50)
    in ApolloProvider (at index.js:49)
```
