### ISSUE TITLE
unsubscribeAll should allow for closed connections and not send GQL_STOP

### ISSUE THREAD

**Issue by ujwal-setlur** [apollographql/subscriptions-transport-ws#417]
I have a need to unsubscribe to all subscriptions when the remote end closes the connection. This is because I navigate to another page, and when the link comes back up, I don't want any stale subscriptions to be re-initiated. I want to start afresh.

Currently, ```unsubscribeAll()``` will try to send a ```GQL_STOP``` to the server, but if the connection is closed, an error is thrown. See the code here:

```javascript

  public unsubscribeAll() {
    Object.keys(this.operations).forEach( subId => {
      this.unsubscribe(subId);
    });
  }

private unsubscribe(opId: string) {
    if (this.operations[opId]) {
      delete this.operations[opId];
      this.setInactivityTimeout();
      this.sendMessage(opId, MessageTypes.GQL_STOP, undefined);
    }
```

We need to have a silent ```unsubscribeAll(silent = true)``` which will just remove the operation, but not actually send a message. I will open a PR on this. Hopefully, this makes sense. If not, I am open to suggestions.

**Comment by ujwal-setlur** [comment]
This is a workaround until then:

```javascript
    // unsubscribe from all our subscriptions
    // do this in a while loop as each unsubscription will throw an error since socket is closed
    let done = false;
    while (!done) {
      try {
        link.subscriptionClient.unsubscribeAll();
        // if we get here, no exception was thrown, and we are done
        done = true;
      } catch (error) {
        // do nothing, keep going until we get no errors
        continue;
      }
    }
```

**Comment by NeoPhi** [comment]
@ujwal-setlur Did you get a chance to add the PR?

**Comment by ujwal-setlur** [comment]
@NeoPhi, Nope, not yet. I was waiting for comment on my suggestion. Sounds like you are in general agreement. I will generate a PR.

**Comment by xaviertholot** [comment]
is there any update on this ? seems like an issue as well if a client refresh a webpage and re-connects...

**Comment by ujwal-setlur** [comment]
I will try to generate a PR this weekend
