### ISSUE TITLE
When no payload is sent on GQL_DATA, error is thrown

### ISSUE THREAD

**Issue by simPod** [apollographql/subscriptions-transport-ws#422]
When no payload is sent on `GQL_DATA` message type, I'm getting

> Uncaught TypeError: Cannot read property 'errors' of undefined

![image](https://user-images.githubusercontent.com/327717/40850655-8355ccae-65c5-11e8-808c-276106939a60.png)

![image](https://user-images.githubusercontent.com/327717/40850665-889b0968-65c5-11e8-8172-04302b35246a.png)

I believe it concerns this line: https://github.com/apollographql/subscriptions-transport-ws/blob/604a458078de4806c4b2e2e70006acb4aad1a6a9/src/client.ts#L608

Is the payload mandatory or is it a bug?

**Comment by NeoPhi** [comment]
For a `GQL_DATA` message the payload is required. Additional details can be found at: https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_data
