### ISSUE TITLE
Update WS library to ^5.2.0

### ISSUE THREAD

**Issue by dwalintukan** [apollographql/subscriptions-transport-ws#424]
Please update the WS library to the newest version of 5.2.0. There are some issues with Windows users with the older version of WS 3.3.3. Thank you.

**Comment by dwalintukan** [comment]
@datoml thanks. I have just used the shrinkwrap feature for now. thankfully there are no changes that need to be done in the code.

**Comment by datoml** [comment]
Good to hear :). Good luck with your project.
