### ISSUE TITLE
Execute function is never called

### ISSUE THREAD

**Issue by Shahor** [apollographql/subscriptions-transport-ws#425]
Hello,

I basically started the conversation [in this issue](https://github.com/davidyaha/graphql-redis-subscriptions/issues/120) but I'm coming here for help as well.

I'm trying to manipulate the `execute` function given to the `SubscriptionServer` but so far I haven't managed to make it run as wanted.

Consider the following:

```js
import { execute, subscribe } from 'graphql'

const graphqlSubscriptionServer = SubscriptionServer.create({
        schema,
        execute: function handleExecution(...args) {
            debugger // Never gets called
            return execute(...args)
        },
        subscribe
}, { ... })
```

I just can't get stopped in this debugger when I publish data in my PubSub, although my subscriptions get properly executed.
So the question is: Who is executing those, calling the graphql `execute` function?

Reading [this line](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L342) I originally thought that it was because of the fact that I gave a `subscribe` function in the options, so I actually rewrote this as follows: 

```js
import { execute, subscribe } from 'graphql'

function isASubscriptionOperation(document, operationName) {
  const operationAST = getOperationAST(document, operationName)

  return !!operationAST && operationAST.operation === 'subscription'
}
const graphqlSubscriptionServer = SubscriptionServer.create({
        schema,
        execute: function handleExecution(...args) {
          const document = args[1]
          const operationName = args[5]

          if (isASubscriptionOperation(document, operationName)) {
            return subscribe(...args)
          }

          return execute(...args)
        },
}, { ... })
```

And although the `subscribe` case gets called, the `execute` one never gets called.

I then looked into the `subscribe` function given by the `graphql` package and it seems that they [internally call `execute` from internal import](https://github.com/graphql/graphql-js/blob/master/src/subscription/subscribe.js#L151) themselves, and from that it looked that I had no way of overriding the `execute` function, as the `subscriptions-transport-ws` suggests we can.

Is there something I'm missing about this?
Can someone give me pointers as to how I can do this?

Cheers

**Comment by NeoPhi** [comment]
The `execute` passed in is used for handling queries sent over the WebSocket and is called directly. To override the `execute` that is ultimately called during a subscription event you would need to supply your own implementation of the `subscribe` function. For the basic structure of how that method operates see: https://github.com/graphql/graphql-js/blob/master/src/subscription/subscribe.js
