### ISSUE TITLE
this.wsImpl is not a constructor in subscriptionCLient.connect

### ISSUE THREAD

**Issue by anikethsaha** [apollographql/subscriptions-transport-ws#426]
I am using the apollo-link paakages as I am using reacct-apollo v2 + 
I am to pass explicitly pass the websoket argument as a 3rd  argument as it was unable to get the native websocket 
Now I am getting this error
 

> this.client = new this.wsImpl(this.url, protocol_1.GRAPHQL_WS);
>                       ^
> TypeError: this.wsImpl is not a constructor

My apollo-client code
```
import { split } from 'apollo-link';
import { HttpLink } from 'apollo-link-http';
import { WebSocketLink } from 'apollo-link-ws';
import { getMainDefinition } from 'apollo-utilities';
import { ApolloClient } from 'apollo-client'
import { InMemoryCache } from 'apollo-cache-inmemory';
import { SubscriptionClient } from "subscriptions-transport-ws";
import { ws } from './websocketClient.js'

// Create an http link:
const httpLink = new HttpLink({
  uri: 'http://localhost:3000/graphql'
});
const GRAPHQL_ENDPOINT = "ws://localhost:3000/subscriptions";

const wsClient = new SubscriptionClient(GRAPHQL_ENDPOINT, {
  reconnect: true
},ws); // or ws from ws package

const wsLink = new WebSocketLink(wsClient);
const link = split(

  ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    return kind === 'OperationDefinition' && operation === 'subscription';
  },
  wsLink,
  httpLink
);
const cache = new InMemoryCache();
export const client = new ApolloClient({
  link,
  cache
});

```

my websoket 
```
`const WebSocket = require('isomorphic-ws')
export const ws = new WebSocket('ws://localhost:3000/', {
  origin: 'http://localhost:3000/graphql'
});`
```

**Comment by NeoPhi** [comment]
You need to pass in a WebSocket constructor that conforms to https://developer.mozilla.org/en-US/docs/Web/API/WebSocket, not an already instantiated instance.

**Comment by anikethsaha** [comment]
Ok so @NeoPhi is it something like this?
```
const wsClient = new SubscriptionClient(GRAPHQL_ENDPOINT, {
  reconnect: true
},new WebSocket('ws://localhost:3000/', {
  origin: 'http://localhost:3000/graphql'
})); 
```
Please correct me if I am wrong..

**Comment by TheCreatorzOne** [comment]
> Ok so @NeoPhi is it something like this?
> 
> ```
> const wsClient = new SubscriptionClient(GRAPHQL_ENDPOINT, {
>   reconnect: true
> },new WebSocket('ws://localhost:3000/', {
>   origin: 'http://localhost:3000/graphql'
> })); 
> ```
> Please correct me if I am wrong..

Did yoou ever fix this? running into the same issue...

**Comment by mluis** [comment]
+1 on this
