### ISSUE TITLE
using lodash instead of lodash.assign, etc. will actually enable smaller webpack builds

### ISSUE THREAD

**Issue by jedwards1211** [apollographql/subscriptions-transport-ws#430]
the lodash modular build packages like `lodash.assign` etc. are actually larger than you would expect, unable to share code with each other, and waste space in a webpack bundle.

It will save more space in webpack bundles to just
```
import {assign} from 'lodash'
```
and use `babel-plugin-lodash`/`lodash-webpack-plugin` to convert this to
```
import _assign from 'lodash/assign'
```

**Comment by NeoPhi** [comment]
Included in https://github.com/apollographql/subscriptions-transport-ws/releases/tag/v0.9.12
