### ISSUE TITLE
Subscriptions returning null after stitching

### ISSUE THREAD

**Issue by jfmlima** [apollographql/subscriptions-transport-ws#440]
So I have a service that has a subscription and if I access its graphiql endpoint directly it works perfectly. 
The issue I'm having is when stitching this into a gateway service that is exposed.
As suggested in other issues I'm using split link 
```js 
    const serviceLink = new HttpLink({ uri: url.href, fetch });
    const wsLink = new WebSocketLink({
      uri: `ws://${url.host}`,
      options: {
        reconnect: true,
      },
      webSocketImpl: ws,
    });

    const link = split(
      // split based on operation type
      ({ query }) => {
        const { kind, operation } = getMainDefinition(query);
        return kind === 'OperationDefinition' && operation === 'subscription';
      },
      wsLink,
      serviceLink,
    );
```

I'm creating a SubscriptionServer in both services  although I'm not sure if this is the right approach.
The problem is that when I test in the graphiql endpoint of the gateway service I always get null as response after a quick show of the normal subscription message.

Gateway:
![image](https://user-images.githubusercontent.com/5619521/42335141-aedcd622-807f-11e8-9c38-b10c488920d1.png)

Service: 
![image](https://user-images.githubusercontent.com/5619521/42335337-58c52be4-8080-11e8-8268-7e658f1b6290.png)

Has anyone experienced this issue while stitching and using subscriptions or is there anything that I'm missing?

```js
    "apollo-client": "^1.2.2",
    "apollo-link": "^1.2.2",
    "apollo-link-context": "^1.0.7",
    "apollo-link-http": "^1.5.1",
    "apollo-link-ws": "^1.0.8",
    "apollo-server-express": "^1.3.2",
    "apollo-utilities": "^1.0.16",
    "graphql-subscriptions": "^0.5.8",
    "graphql-tools": "^2.21.0",
    "subscriptions-transport-ws": "^0.9.12",
```

**Comment by raeesaa** [comment]
Even I am facing similar issue with stitching. I get `null` in response in case either `onConnect` method of subscription server or subscription resolver throws an error. In other cases, I am getting expected data.

@Jflima92 Did you manage to fix this issue?

**Comment by Jflima92** [comment]
@raeesaa unfortunately no

**Comment by rapzo** [comment]
How come your `apollo-client` is still v1.x? Just a wild guess...

**Comment by raeesaa** [comment]
@rapzo I am using apollo-client `2.2.0` and still getting this issue.

**Comment by hansololai** [comment]
@raeesaa could you post the resolvers that you setup for the mutation. I am guess inside the resolve function, after the activility is added, you'll need to find the channel, the do a broadcasting with the data.  In my case
`        pubsub.publish('activityAdded', {
          activityAdded: result,
        });`
If you simply run a mutaion
`Mutation{
activityAdded(input: {Foo:Bar})
}`
(depends on how you define it. This is what I did)
 
This usually means the mutaion does not have to return anything. (maybe just have to return status code). If you run mutation
`Mutation{
activityAdded(input: {Foo:Bar}){
id
}
}`. it means the mutation will have to return a {id}.
This returned object should be the one that's getting published in your mutation resolver.

**Comment by apoggi-carecloud** [comment]
@jfmlima was this ever resolved? If so, what was your solution?
