### ISSUE TITLE
Set custom headers in HTTP Upgrade

### ISSUE THREAD

**Issue by wawhal** [apollographql/subscriptions-transport-ws#446]
Does this library allow me to set HTTP headers not as connection parameters but during the HTTP upgrade request? For some reasons, I do not want to set my headers in the connection params.

**Comment by wawhal** [comment]
Seems like there is no way to do this. Closing the issue.

**Comment by rhyek** [comment]
See https://github.com/apollographql/subscriptions-transport-ws/issues/662#issuecomment-685464873
