### ISSUE TITLE
Need clear auth workflow.

### ISSUE THREAD

**Issue by mrdulin** [apollographql/subscriptions-transport-ws#455]
My think about auth workflow is: 

1. Not login - the websocket client should not connect to websocket server, but can be configured with uri and options
2. when user loginned, maybe in the callback of `authService.login()` method, invoke `wsClient.connect(jwt)` manually to connect and pass `jwt` to websocket server .

I did some search, Here is my solution: 

```ts
const wsClient = new SubscriptionClient(WS_URI, {
      lazy: true, // what for ?
      connectionParams: () => {
        return {
          token: authService.getJwt()
        };
      },
      reconnect: true,
      reconnectionAttempts: 60,
      connectionCallback: (error: Error[]) => {
        if (error) {
          console.log(error);
        }
        console.log('connectionCallback');
      },
      inactivityTimeout: 60 * 1000
    });

    const wsLink = new WebSocketLink(wsClient);
```

But I am not sure this solution is correct or not. When `jwt` is empty which means user does not login. The websocket client will retry connect to websocket server. Is this correct? What if the retry times is used up then user logins, the websocket client will never try to connect websocket server.

**Comment by viktor-ku** [comment]
I'd like to have more information about clear auth workflow too
