### ISSUE TITLE
How to handle AppState changes in react native? [QUESTION]

### ISSUE THREAD

**Issue by perrosnk** [apollographql/subscriptions-transport-ws#457]
How do you handle AppState changes in react native?

I am facing some problems (mostly with subscriptions) in iOS and Android, as the ws connection is lost when the app is in the background.

**Comment by schavaLogi** [comment]
Listen to AppState changes and close connection and create a new connection. 
In case if you would like to add offline support please use apollo-link-queue to close & open gate based on connection status.

I am using onReconnecting, onReconnected, onDisconnected to open/close gate.
