### ISSUE TITLE
Pending Operations sent again when reconnecting. This will be problem when used for mutations, query along with subscriptions.

### ISSUE THREAD

**Issue by schavaLogi** [apollographql/subscriptions-transport-ws#458]
- [ X] has-reproduction
- [X ] feature
When we use this for mutations, query along with subscriptions the current bahaviour causing the duplicate updations in DB as mutation triggered and reached server but response yet to receive and socket disconnects and when we reConnecting we send all pending requests once connected.

This behaviour cause duplications. We should provide a way through middleware to detect the unsent & pending

**Reporductions Steps:**
1. Make sure connection is up and trigger Mutation or Query 
2. Before Reaching response - disconnect triggered due to KA packet loss as timeout is 8 sec
3. Auto Reconnects and triggers the pending Mutation or Query ( Mutations cause issue as the previous request already reached to server)

Reference Code:
if (!this.reconnecting) {
            Object.keys(this.operations).forEach(function (key) { _--> Even Pending operations added to queue & will be triggered when connected_
                _this.unsentMessagesQueue.push(_this.buildMessage(key, message_types_1.default.GQL_START, _this.operations[key].options));
            });
            this.reconnecting = true;
        }

**Comment by xaviertholot** [comment]
I think I'm encountering the same issue, when I reconnect I receive one message per subscriber and the is one subscriber per connection...
Is there an implementation issue or a bug ?
