### ISSUE TITLE
Split the project in server and client libs

### ISSUE THREAD

**Issue by schrepfler** [apollographql/subscriptions-transport-ws#46]
Unsure why the subscriptions bundles both client and server libs. Perhaps splitting it to two projects would be better for re-usability?

**Comment by helfer** [comment]
@schrepfler I agree, we could definitely us a PR that turns this into a monorepo like we did for graphql-server. So if you have time... :wink:

**Comment by schrepfler** [comment]
I'm just a Java/Scala dev! Even you JS geeks fatigue with all the tools and module systems that you have :D

**Comment by helfer** [comment]
@schrepfler haha, very well! I'll leave it up for grabs to anyone who has the time and interest to do it!

**Comment by Urigo** [comment]
@schrepfler , the client and server packages are now two different files, since this PR: https://github.com/apollographql/subscriptions-transport-ws/pull/53
Thanks!

**Comment by wtgtybhertgeghgtwtg** [comment]
How about splitting it into client and server packages?
