### ISSUE TITLE
Can't force close the connection with reconnect set to true

### ISSUE THREAD

**Issue by davidBanai** [apollographql/subscriptions-transport-ws#467]
When reconnect is set to true and there is an error, (our assumption is that) the connection is closed 
 automatically (https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/client.ts#L146) and then reopened again after a certain backoff time (https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/client.ts#L502). 

The problem is that esentially in this case you can't really use force close on the socket (for example when you want to perform a logout and clear everything) because the client is already cleared (https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/client.ts#L148). Let's say there is this error but it's presence shouldn't disallow you to force close the socket even if you have reconnect set to true - at least this is how we think it should behave.

**Comment by zorji** [comment]
I have the same issue.

The current work around is force `reconnect` to `false` right before I call `close()`

```
    this.subscriptionClient.unsubscribeAll()
    // @ts-ignore
    this.subscriptionClient.reconnect = false
    this.subscriptionClient.close(true, true)
```
