### ISSUE TITLE
keepAlive and performance problems?

### ISSUE THREAD

**Issue by frederikhors** [apollographql/subscriptions-transport-ws#468]
Do you see any server performance problem using the `keepAlive: ANY_NUMBER_IN_MS`?

Default is disabled, why? What happens when disabled?

And why Heroku still needs a keepAlive?

**Comment by perrosnk** [comment]
+1
I have the same question! What happens when you don't set any keepAlive?
How the server and the client behaves differently?

**Comment by gklijs** [comment]
I at least noticed with the clojurescript re-graph client if I don't have a keepAlive on the server it's reconnecting about every 5 minutes. So it does seem wise to have them. Some graphql server implementations have them on by default.
