### ISSUE TITLE
can subscriptions be finite? (server initiated GQL_COMPLETE)

### ISSUE THREAD

**Issue by osi** [apollographql/subscriptions-transport-ws#471]
/label question

When reading the [protocol](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_complete) docs,  it states:

> GQL_COMPLETE
>Server sends this message to indicate that a GraphQL operation is done, and no more data will arrive for the specific operation.

Which makes it sound like any operation done over the websocket protocol can be finite on the server side (including subscriptions)

This jives with the [implementation](https://github.com/apollographql/subscriptions-transport-ws/blob/52758bfba6190169a28078ecbafd2e457a2ff7a8/src/server.ts#L389) which will send a complete message after the execution iterable is exhausted.

However, in the [connected phase](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#connected-phase) portion of the protocol doc, it only describes an infinite subscription (which would need to be explicitly cancelled to stop).

If the intent is to allow finite subscriptions (which the code seems to suggest), I'll submit a PR that improves the protocol documentation.

**Comment by jbaxleyiii** [comment]
@osi this is a great question! Yes finite subscriptions are definitely part of the protocol and what we want to support!

**Comment by osi** [comment]
awesome! i’ll work on a PR to help clarify the protocol documentation. 

-- 
(peter.royal|osi)@pobox.com - http://fotap.org/~osi

**Comment by jbaxleyiii** [comment]
@osi you're amazing!
