### ISSUE TITLE
How to implement the onReconnect method?

### ISSUE THREAD

**Issue by ChristopherParo** [apollographql/subscriptions-transport-ws#475]
I apologize if this is a repeat question.

I am having an issue trying to find an example where you set up the onReconnect. I don't quiet understand where I need to set this up so I can run a query as soon as the socket reconnects. Any example links would be extremely helpful.

**Comment by Tobino** [comment]
Hi,

You can find an example of implementation with onDisconnected event on this link.
https://github.com/Akryum/vue-apollo/issues/149

You can then use apollo client to refetch some data for your application.
