### ISSUE TITLE
Error : Missing schema information, when schema is provided statically with onOperation

### ISSUE THREAD

**Issue by ubbop42** [apollographql/subscriptions-transport-ws#476]
new SubscriptionServer({
    schema,
    execute,
    subscribe,
    onOperation: message => {

As u can see im giving the schema, but 
  "error": {
    "message": "Missing schema information. The GraphQL schema should be provided either statically in the `SubscriptionServer` constructor or as a property on the object returned from onOperation!"
  }
is thrown

It works when there is no onOperation method

**Comment by boboci9** [comment]
Hi, any news on this?

**Comment by alhuar** [comment]
Hello, I'm having the exact same issue, even passing the schema to the SubscriptionServer constructor. Any updates on this issue?

Here's the subscriptionServer code:
`  const subscriptionServer = SubscriptionServer.create({
    schema,
    execute,
    subscribe,
    onConnect: (connectionParams) => {
      const token = get(connectionParams, 'token')
      if (token) {
        const jwt = require('jwt-simple')
        const decoded = jwt.decode(token, process.env.AUTH_SECRET_KEY)
        const user = get(decoded, 'user')
        return { user, token }
      }
      throw new AuthenticationError('ws 401')
    },
    onOperation: (message, params, webSocket) => {
      const context = get(params, 'context')
      const user = get(context, 'user')
      const operationName = get(message, 'payload.operationName') || get(params, 'operationName')
      checkMaintenanceMode(user, operationName, null)
      const query = get(message, 'payload.query') || get(params, 'query')
      console.log('OPERATIONNAME:', operationName)
      if (!isProduction && operationName === 'IntrospectionQuery') return // playground
      const variables = get(message, 'payload.variables') || get(params, 'variables')
      const brandId = get(variables, 'brandId')
      console.log({operationName, user})
      hasPermissions(operationName, query, variables, user, brandId, null, null, 'subscription')
      return {...context, brandId, schema}
    }
  }, {
    server: httpServer,
    path: '/subscriptions',
  })`

Schema: 
`const schema = new GraphQLSchema({
  query: RootQuery,
  types: types,
  mutation: RootMutation,
  subscription: RootSubscription

})
`

**Comment by DCosti** [comment]
> Hello, I'm having the exact same issue, even passing the schema to the SubscriptionServer constructor. Any updates on this issue?
> 
> Here's the subscriptionServer code:
> 
> ```
> const subscriptionServer = SubscriptionServer.create({
>     schema,
>     execute,
>     subscribe,
>     onConnect: (connectionParams) => {
>       const token = get(connectionParams, 'token')
>       if (token) {
>         const jwt = require('jwt-simple')
>         const decoded = jwt.decode(token, process.env.AUTH_SECRET_KEY)
>         const user = get(decoded, 'user')
>         return { user, token }
>       }
>       throw new AuthenticationError('ws 401')
>     },
>     onOperation: (message, params, webSocket) => {
>       const context = get(params, 'context')
>       const user = get(context, 'user')
>       const operationName = get(message, 'payload.operationName') || get(params, 'operationName')
>       checkMaintenanceMode(user, operationName, null)
>       const query = get(message, 'payload.query') || get(params, 'query')
>  
>       const variables = get(message, 'payload.variables') || get(params, 'variables')
>       const brandId = get(variables, 'brandId')
>       console.log({operationName, user})
>       hasPermissions(operationName, query, variables, user, brandId, null, null, 'subscription')
>       return {...context, brandId}
>     }
>   }, {
>     server: httpServer,
>     path: '/subscriptions',
>   })
> ```
> 
> Schema:
> 
> ```
> const schema = new GraphQLSchema({
>   query: RootQuery,
>   types: types,
>   mutation: RootMutation,
>   subscription: RootSubscription
> })
> ```

Hi! Try to return schema in onOperation: `return {schema, context: {...context, brandId}}`. Worked for me!:)
