### ISSUE TITLE
onOperationComplete. Is there a way to know which subscription is completed

### ISSUE THREAD

**Issue by ubbop42** [apollographql/subscriptions-transport-ws#479]
onOperationComplete. Is there a way to know which subscription is completed.
So i can release system resources

**Comment by slowr** [comment]
As stated in [PROTOCOL](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md); GQL_COMPLETE includes the OperationId that corresponds to that specific subscription.

**Comment by ambientlight** [comment]
to expand:
`operationId` is passed as second parameter to onOperationComplete, to reference it in your resolver logic, we can capture it during `onOperation`:

```js
SubscriptionServer.create({
  ...
  onOperation: (message, params, webSocket) => {
      if(message.type == 'start'){
        params.context.opId = message.id
      }

      return params
    }
}
```

then the `params.context` is passed as third parameter to your resolver's `subscribe` and `resolve`
