### ISSUE TITLE
Returns 400 Bad Request when connecting to GraphQL for subscriptions

### ISSUE THREAD

**Issue by desmond-phonegap** [apollographql/subscriptions-transport-ws#482]
GraphQL server implemented returns **400 Bad Request** when listening to the web socket port for subscription.

Exress application with port 3000 runs perfectly and I am able to query and mutate without issues. 
Since i could not subscribe I am not able to get the updates.

Below is the server code 

```

const graphQLServer = express();

const ws = createServer(graphQLServer);

graphQLServer.use('/graphql', bodyParser.json(), graphqlExpress({ schema }));

const GRAPHQL_PORT = 3000;
const PORT = 3001;

graphQLServer.use('/graphiql',
  graphiqlExpress(
    {
      endpointURL: '/graphql',
      subscriptionsEndpoint: `ws://localhost:${PORT}/sibscriptions`
    })
);


graphQLServer.listen(GRAPHQL_PORT, () =>
  console.log(
    `GraphiQL is now running on http://localhost:${GRAPHQL_PORT}/graphiql`
  )
);


ws.listen(PORT, () => {
  console.log(`GRAPHQL server is now running on on http://localhost:${PORT}`);
  new SubscriptionServer({
    execute,
    subscribe,
    schema
  }, {
      server: ws,
      path: '/subscriptions',
    });
`});`
```

Error
![image](https://user-images.githubusercontent.com/12242790/47786521-fb65c480-dd46-11e8-9c0e-197e1920ddb6.png)

**Comment by slowr** [comment]
You have a small typo in your code that might be causing trouble:
`ws://localhost:${PORT}/sibscriptions`
