### ISSUE TITLE
keepAlive doesnt seem to work?

### ISSUE THREAD

**Issue by farzd** [apollographql/subscriptions-transport-ws#490]
```
 "subscriptions-transport-ws": "^0.9.14"
```

I'm using ``` keepAlive: 10000``` for my Server, 
I'm also using ``` https://github.com/davidyaha/graphql-redis-subscriptions ``` for my pub/sub, this uses ```ioredis``` which has its own keepAlive config option, i've set this to ``` keepAlive: 10000``` as well. Not sure if this would be related, anymore theres plenty more options https://github.com/luin/ioredis

My Apollo client 
```
  const wsLink = new WebSocketLink({
    uri: `${server.subscriptionsEndPoint}?req=${JWTtoken}`,
    options: {
      reconnect: true,
      timeout: 30000,
      inactivityTimeout: 0
    }
  })

```
I'm using this with react-native - expo specifically / iOS . Firstly, the connection times out after 6 minutes. onDisconnect is called. Another frustration is that if i lock the phone or simulator after making the connection, it disconnects me [app goes to background]. Upon unlocking the phone [app to foreground] it connects again.

What is the expected behaviour for keepAlive, should it just send signals intermittently to keep the connection alive so i should not see any disconnects ? 

Having this issue locally and in production [using Elastic Cache- redis with AWS]

**Comment by farzd** [comment]
Upon further inspection, it appears the keepAlive ping is working
however as soon as my lock my phone the first time, it disconnects.
Unlocking connects again, not sure if this is React-native behaviour?

![image](https://user-images.githubusercontent.com/1423413/48481006-fc492c80-e803-11e8-919b-a0d2cb401375.png)

**Comment by perrosnk** [comment]
+1 I am having the exact same issue. If you find a solution please let me know @farzd !

**Comment by perrosnk** [comment]
Any updates on this @farzd ?

**Comment by farzd** [comment]
@perrosnk see here
https://github.com/expo/expo/issues/2946

turns out mobile's disconnect the socket connection when idle / app in background to save the battery. Theres no way around it for me, so i've resorted to polling. If your idea is different perhaps you could connect again when phone comes to foreground

**Comment by danielehrhardt** [comment]
> @perrosnk see here
> [expo/expo#2946](https://github.com/expo/expo/issues/2946)
> 
> turns out mobile's disconnect the socket connection when idle / app in background to save the battery. Theres no way around it for me, so i've resorted to polling. If your idea is different perhaps you could connect again when phone comes to foreground

What is your workaround?
