### ISSUE TITLE
`WebSocket.onclose`'s reasons for disconnection are not passed to users

### ISSUE THREAD

**Issue by slawomir-brzezinski-at-clarksons** [apollographql/subscriptions-transport-ws#505]
Hi. We're trying to diagnose the reasons for disconnections, but this library seems to not be passing the original browser event (which includes the useful [standard properties like `reason`, `code`, `wasClean`](https://www.w3.org/TR/websockets/#closeevent)) to the subscribers of apollo's `onDisconnected`.

The code where the event is lost is [here](https://github.com/apollographql/subscriptions-transport-ws/blob/a0f02f51a8e628a734fd5b9b233ab0a83471e222/src/client.ts#L562).

Is this something you can [fix/accept a PR]?

**Comment by perrosnk** [comment]
+1

**Comment by lim-enhui** [comment]
subscription requires additional configuration. It runs on https server.. i am still figuring out to generate a key and certificate that is recognize for google cloud deploy... i hope someone can give a guide on the things needs to be done to deploy on to servers.
