### ISSUE TITLE
Tokens not sending a first

### ISSUE THREAD

**Issue by developdeez** [apollographql/subscriptions-transport-ws#507]
I'm working on a notifications bar that shows after client login. It subscribes to new alerts.

My trouble is, since adding auth to the ws link, I keep seeing missing token errors. It sppears it runs too soon. My http link populates the localstorage with the token after login but I think I need a way to make the onConnect run after.

MY call is below:

```
const wsLink = new WebSocketLink({
  uri: wsurl,
  options: {
    reconnect: true,
    connectionParams: {
      token: localStorage.getItem("token"),
      refreshToken: localStorage.getItem("refreshToken")
    }
  }
});
```

**Comment by revskill10** [comment]
Could you try adding `lazy: true` to the `options` ?

**Comment by Dartv** [comment]
Making `connectionParams` a function can also help

**Comment by WangShuXian6** [comment]
>您可以使用 ```get```语法，这样就可以始终获取最新的```token```变量值 
>同时需要 ```lazy: true```
```ts
const wsLink = new WebSocketLink({
  uri: CLIENT_CONFIG.websocketUrl,
  options: {
    lazy: true,
    reconnect: true,
    connectionParams: {
      get authorization() {
        return user.getAuthorization();
      },
    },
    connectionCallback: (error) => {
      //@ts-ignore
      if (error?.message === "Authentication Failure!") {
        //@ts-ignore
        //wsLink.subscriptionClient.close(false, false);
      }
    },
  },
});
```
