### ISSUE TITLE
Client hooks for onConnect and onDisconnect?

### ISSUE THREAD

**Issue by kesne** [apollographql/subscriptions-transport-ws#51]
Knowing when the websocket connection connects and disconnects could be important to showing certain UIs to users. Do you think it would be reasonable to add an `onConnect` and `onDisconnect` hook to the client constructor so that you can roughly determine the connection state?

FWIW I implemented a super simple version of this (along with a keepAlive timeout) in my fork: https://github.com/apollostack/subscriptions-transport-ws/compare/master...kesne:master

**Comment by NeoPhi** [comment]
I suspect a more flexible long term approach would be to make the Client an event emitter so that if there are additional events of interest in the future there is a standardized way of handling them.

**Comment by kesne** [comment]
@NeoPhi That's a good point. I updated my fork to use an eventemitter instead. Is this worth putting into a PR to try to get it landed?

https://github.com/apollostack/subscriptions-transport-ws/compare/master...kesne:master

**Comment by Urigo** [comment]
see discussion here - https://github.com/apollostack/graphql-subscriptions/pull/27

**Comment by mpowaga** [comment]
This is also very much needed if you want to maintain live connection to the server. When connection drops you want to reload the page or invalidate local cache (e.g. when new version is deployed).

**Comment by Urigo** [comment]
We implemented it in this PR: https://github.com/apollographql/subscriptions-transport-ws/pull/53 , and we will release it soon!

**Comment by Urigo** [comment]
released
