### ISSUE TITLE
Please update the documentation in a timely manner

### ISSUE THREAD

**Issue by yangchongduo** [apollographql/subscriptions-transport-ws#510]
"export 'createNetworkInterface' was not found in 'apollo-client'
  "apollo-client": "2.2.0",

**Comment by yangit** [comment]
Same issue.
Did you found a solution?

**Comment by danfernand** [comment]
hi all found the migration guide - https://github.com/apollographql/apollo-client/blob/c3561e73957799bbf0d7f87c4a3ebcfee6f40e3a/docs/source/recipes/2.0-migration.md#network-middleware-and-afterware

I would expect apollo-link-ws
