### ISSUE TITLE
Pass in a koa server?

### ISSUE THREAD

**Issue by myyellowshoe** [apollographql/subscriptions-transport-ws#52]
From the docs I can see the subscriptionServer takes the standard node http node server.
I'd like to use a koa 2 server instead. Is that possible?

**Comment by helfer** [comment]
@myyellowshoe I don't actually know. Maybe you can try it and let us know? 🙂

**Comment by Martin-Ting** [comment]
I'm not too familiar with koa but you might be able to do something like this to get the node http server: 
```
const app = require('koa')();
const http = require('http');
app.use(...);
var server = http.createServer(app.callback());
server.listen(8080);
```
and pass `http` into the subscriptionServer.

**Comment by NeoPhi** [comment]
It would be great to add this setup to the documentation. Hapi uses a similar pattern.

**Comment by kouak** [comment]
With koa2, this works fine :
```Javascript
const app = new Koa();
app.use(...);

const server = app.listen(8080);

new SubscriptionServer({
  subscriptionManager,
  ...
}, {
  path: '/subscriptions',
  server,
});
```

Note the heading ```/``` in the path. Could not get it to work without it.

**Comment by myyellowshoe** [comment]
Cool I'll have to try it out!

**Comment by Urigo** [comment]
Should work now (since we allow any server to pass to `WebSocket.Server` instance).

**Comment by myyellowshoe** [comment]
@kouak Perfect. Worked like a charm.
