### ISSUE TITLE
How to integrate with graphql-request?

### ISSUE THREAD

**Issue by anhnhoktvn** [apollographql/subscriptions-transport-ws#521]
How can I integrate this library with [graphql-request](https://github.com/prisma/graphql-request/) ?

**Comment by lunchboxer** [comment]
Integrate isn't the right word, but you can use them both. graphql-request uses fetch to handle queries and mutations. It has no support for subscriptions. You could use graphql-request to handle non-subscription queries and use subscriptions-transport-ws to handle your subscriptions. You could also forget about graphql-request and use this library to handle all of your requests over websockets, not just subscriptions.
