### ISSUE TITLE
How to use it with existing ApolloServer 

### ISSUE THREAD

**Issue by DimiMikadze** [apollographql/subscriptions-transport-ws#539]
Hello, i want to use this library with already existing `ApolloServer` that is imported from `apollo-server-express`

I couldn't find any resource how to do that. I've seen this example `https://github.com/apollographql/subscriptions-transport-ws/blob/72facabe740d7873887b16cb670f6a8d9b394fba/docs/source/express.md` but this example uses `1.0` old version and i'm using newer one `2.0`.

This is how i'm creating a Apollo Server right now.

apollo-server.js
```
const { ApolloServer } = require("apollo-server-express");
exports.createApolloServer = (schema, resolvers, models) => {
  return new ApolloServer({
    typeDefs: schema,
    resolvers,
    context: async ({ req, connection }) => {
      if (connection) {
        return Object.assign({}, models);
      }

      if (req) {
        const authUser = await checkAuthorization(req);
        req.authUser = authUser;

        return Object.assign({ authUser }, models);
      }
    }
  });
};
```

server.js
```
const server = createApolloServer(schema, resolvers, models);
server.applyMiddleware({ app, path: "/graphql" });

app.listen({ port: PORT }, () =>
  console.log(`🚀 API ready at ${API_URL}:${PORT}${server.graphqlPath}`)
);
```

any help would be much appreciated

**Comment by perrosnk** [comment]
Any updates?

**Comment by mattwr18** [comment]
Also would love to see an example of this... have a `PR` open here: https://github.com/Human-Connection/Human-Connection/pull/1705/files, but it's starting, however it's not connecting...
