### ISSUE TITLE
"Client is not connected to a websocket"

### ISSUE THREAD

**Issue by booboothefool** [apollographql/subscriptions-transport-ws#55]
Sorry for the ambiguity, but sometimes I get this error when I start my app.

I am pretty sure I set up most things correctly because I have subscriptions flying all over my app, and **it does connect about 90% of the time**, but it's a real bummer when it doesn't (nothing  realtime works of course) and I have no idea why. :c

![screen shot 2016-12-23 at 2 14 00 am](https://cloud.githubusercontent.com/assets/13257645/21448971/3f8798fc-c8b6-11e6-98d1-ae8fe61e0015.png)

**Comment by helfer** [comment]
@booboothefool I think this might happen if you subscribe when the websocket isn't ready yet. Could you try to submit a failing test case for this? It should be feasible to do so by creating a test case which subscribes as quickly as possible after initializing the client.

**Comment by Urigo** [comment]
Since https://github.com/apollographql/subscriptions-transport-ws/issues/53 merged, there is a new INIT message in the protocol, and new subscriptions are initialized only after init is done. 
@booboothefool , Can you please try with the new version? we will release it really soon.

**Comment by NeoPhi** [comment]
@Urigo I'm not seeing in the code how the INIT message acts as a guard to prevent subscription messages from being sent. Additionally in the case of a reconnect previously subscriptions are reestablished prior to the INIT event firing.

**Comment by booboothefool** [comment]
@Urigo

I no longer get
> Client is connected to a websocket
and it seems to always connect successfully initially, but now instead I am getting an error that reads
> INVALID_STATE_ERR
It seems to be a lot worse because it happens much more frequently, and while `Client is not connected to a websocket` would just error and break subscriptions, `INVALID_STATE_ERR` crashes my app completely. 

I am not sure why this is happening, as it seems completely random. It's like it's dropping the connection. 

All I did was I upgraded to the new library and changed `addGraphQLSubscriptions` to the one from the library instead of https://github.com/apollographql/GitHunt-React/blob/master/ui/helpers/subscriptions.js.

**Comment by NeoPhi** [comment]
@booboothefool I've noticed that with native WebSockets I'm seeing the client disconnect and reconnect more often. On the server do you have the `keepAlive` option set? If not does setting it to something like `20000` help reduce the incidence?

**Comment by booboothefool** [comment]
@NeoPhi cool so:

`0.3.1` => "Client is not connected to a websocket"
`0.5.0` => "INVALID_STATE_ERR"

Then I upgraded to `0.5.1` and did what you suggested setting `keepAlive: 20000` on the server, and it seems like it works great now. Client always connects successfully and it hasn't crashed me with `INVALID_STATE_ERR` in 2 days. 

Can you explain what that does and how it solves the problem?

**Comment by NeoPhi** [comment]
I've not walked through the code but I suspect that there is a race condition between the WebSocket reconnecting and the previously active subscriptions being reestablished such that the client thinks it is okay to send a message when in fact it shouldn't.

**Comment by devarashetty** [comment]
facing the same error again  using version `0.5.5`

**Comment by savovs** [comment]
I'm having a similar problem, in the SubscriptionServer, onConnect runs and is followed immediately by a disconnect. Where do you put this `keepAlive` option?
