### ISSUE TITLE
Question - purpose of context.

### ISSUE THREAD

**Issue by pfulop** [apollographql/subscriptions-transport-ws#57]
Hi,
This is more of a functionality question, but how does exactly context work? I thought that when I set context on client, which is then send to server, Subscription server will pass it to the subscriptionManager. But when I looked at the code and also consoled out context, it was always an empty object. So what exactly is the purpose of it? Or is it expected to be altered in custom onSubscribe function?

**Comment by helfer** [comment]
@pfulop As far as I can recall that is indeed the purpose of context. Did you set the context and it was still empty? If so, it's possible that it's a bug, although I believe that we have at least one test that uses context.

**Comment by pfulop** [comment]
@helfer, yes it was empty. 

Doesn't this [line](https://github.com/apollostack/subscriptions-transport-ws/blob/master/src/server.ts#L132)  set it to be an empty object?

**Comment by jacobk** [comment]
It also doesn't seem to be possible to provide a context to SubscriptionServer that will be passed to SubscriptionManager making it impossible to resolve objects that rely on a context for subscription query results.

**Comment by jacobk** [comment]
Nevermind, i noticed that it's possible to customize the subscribe params by providing a `onSubscribe` callback to `SubscriptionServer`.

**Comment by NeoPhi** [comment]
Sounds like the README should be updated to better call out this common use case.

**Comment by Urigo** [comment]
Updated in https://github.com/apollographql/subscriptions-transport-ws/commit/b144779dfece99d8ecdf76593c0535ba34c37493
