### ISSUE TITLE
Reconnecting forever even if successful in a specific case

### ISSUE THREAD

**Issue by sneko** [apollographql/subscriptions-transport-ws#598]
Hi everyone,

My frontend successfully connects through websocket to my API and I can subscribe and see updates...

But if I restart my API, a few things will happen:
1. The frontend client tries reconnecting regularly... that's normal since I specified the `reconnect: true`
2. My API is up and fully restarted
3. The frontend succeeds reconnecting to the API, and I can see successful logs in my API logs
4. ... the weird thing is... my frontend will continue connecting to the API forever, I stopped counting but I saw like 500+ reconnections, all successful on both side but it continues 😢 

I thought about the `timeout` that I didn't specified, but its default value seems 30000ms. And when looking at all WebSocket messages, the server always responds within second.
![image](https://user-images.githubusercontent.com/8195958/61011239-124ec300-a37a-11e9-88ca-e6ee30655a79.png)

Do you have any idea what could cause this weird behavior? It's totally flooding my API and for sure my API will restart for each new deployment ^^...

Thank you!

**Comment by pmachan** [comment]
@sneko I have same problem. What are you using as subscriptions server? Im using gqlgen (go graphql server)

**Comment by sneko** [comment]
@pmachan I'm using gqlgen too. Please take a look at the related issue where I provide a workaround https://github.com/99designs/gqlgen/issues/745
