### ISSUE TITLE
Directions for use outside of Apollo

### ISSUE THREAD

**Issue by spiffytech** [apollographql/subscriptions-transport-ws#609]
I found [a gist](https://gist.github.com/stubailo/8b7ff3b60221e0d648a50f9bc8065e89) that indicates it's possible to use this library outside of Apollo, but it uses an outdated API.

What are current directions for subscribing to a Subscription using this library directly, without Apollo? I'd like to use this with other GraphQL libraries.

**Comment by gklijs** [comment]
You can create a subscriptionClient and use that, but the latest version  seems broken for this. I got it to work for GraphiQL yesterday, https://github.com/gklijs/micronaut-graphql/blob/add_subscriptions/graphql/src/main/resources/graphiql/index.html.
