### ISSUE TITLE
A message was not sent because socket is not connected, is closing or is already closed.

### ISSUE THREAD

**Issue by redhouse877** [apollographql/subscriptions-transport-ws#646]
I'm receiving a message in my backend every so often saying:

`A message was not sent because socket is not connected, is closing or is already closed. Message was: {"id":"10227","type":"stop"}`

What does this error suggest?

**Comment by viktor-br** [comment]
Looks like an unsubscribe message, sent through not opened (already closed, maybe) websocket: https://github.com/apollographql/subscriptions-transport-ws/blob/0bbc7141787ca63b41a0a2dd0634b2b4c1a39e97/src/client.ts#L482

Unsubscribe message is triggered here https://github.com/apollographql/subscriptions-transport-ws/blob/0bbc7141787ca63b41a0a2dd0634b2b4c1a39e97/src/client.ts#L661

**Comment by benliger1987** [comment]
Is there a more graceful way to handle this error?
