### ISSUE TITLE
Empty `connectionParams`, although ws payload is there

### ISSUE THREAD

**Issue by tomasAlabes** [apollographql/subscriptions-transport-ws#726]
Hi, I tried all combinations of subscription with `connectionParams` possible and I'm not able to see them in the server.

Client:

```js
   // apollo-client 2.6.8
   // apollo-link-ws 1.0.19

   return new WebSocketLink({
	uri: url,
	options: {
	    reconnect: true,
	    lazy: true,
	    connectionParams: { idtoken: "blah" } 
    }
```

```js
	import { SubscriptionServer } from 'subscriptions-transport-ws'; // 0.9.16

        const httpServer = createServer(expressApp);
	const schema = makeExecutableSchema({ typeDefs, resolvers });

	httpServer.listen(httpPort, () => {
		new SubscriptionServer(
			{
				execute,
				subscribe,
				onConnect: (connectionParams) => {
					console.log("connectionParams: ", connectionParams)
                                         // always empty
				},
				schema
			},
			{
				server: httpServer
			}
		);
	});
```

I see the ws message going out with:

`{"type":"connection_init","payload":{"idtoken":"blah"}}`

But the server always receives it with an empty payload. Hence no `connectionParams` in the `onConnect`.

Anything I'm missing? Is this a bug? The client is using the plain WebSocket implementation, and the server whatever comes with `subscriptions-transport-ws` (I had `ws` installed and removed it, just to try).

Thanks! 🎅

**Comment by tomasAlabes** [comment]
I think it's the gateway in between the front-end and the service.

**Comment by koborg** [comment]
Same problem here!
`new SubscriptionServer(
        {
            execute,
            subscribe,
            schema,
            onConnect: (connectionParams, webSocket, context) => {
                console.log(connectionParams);
                return { playerId: 1 };
            },
        },
        {
            server: httpServer,
            path: '/subscriptions',
        }
    );`
here I console the connectionParams and I pass them here: 
`const wsLink = new WebSocketLink({
    uri: `ws://localhost:4000/subscriptions`,
    options: {
        reconnect: true,
    },
    connectionParams: {
        authToken: 'test token',
    },
});`

the result of the log is always empty object {}

**Comment by saurav-bhagat** [comment]
@tomasAlabes Did you get any solution to this?
I'm also facing same issue.
