### ISSUE TITLE
Multiple websocket connections created during reconnects (SubscriptionClient)

### ISSUE THREAD

**Issue by mjwinneyra** [apollographql/subscriptions-transport-ws#732]
Issue has been found in the SubscriptionClient (client.ts)

**Intended outcome:**
Single websocket connection made during a reconnect attempt and a subscription request being received during the reconnect timer period.

**Actual outcome:**
setup
- websocket connection option: reconnect is true
- Connection is down.  The reconnect timer is active and will expire in 10 seconds.
- Client sends a subscription request which makes a new websocket connection because we are in retry mode.
- The reconnect timer expires after 10 seconds it now runs connect again, which overwrites the old websocket and creates a new one.  Now have 2 established websocket connections.

**How to reproduce the issue:**
In our case we are using the GraphQL stitching, but that might not be the easiest way to reproduce issues.
Steps to reproduce:

1. Create an instance of the SubscriptionClient passing a websocket implementation.  Pass reconnect = true
2. Wait for the ReconnectTimeoutId to delay for 10 seconds (makes reproduction of timing problem easier)
3. During 10 seconds ReconnectTimeoutId bring up the GraphQL server and immediately send a subscription request to SubscriptionClient.
5. Notice that the connection is now made to the GraphQL server due to the request received and it calling connect() method to establish a websocket connection.
6. The 10 second ReconnectTimeoutId now expires and also performs a connect(), overwriting the existing websocket and creating a new one.  Now have to established websocket connections to the GraphQL server.

**Comment by perrosnk** [comment]
any updates?

**Comment by jhartzell** [comment]
would love feedback on this..

**Comment by firthh** [comment]
I've been experiencing this as well. Any update?

**Comment by sparcs360** [comment]
I'm seeing this issue too... any update?

**Comment by shotmk** [comment]
Same error, any update?

**Comment by Feedcube** [comment]
I have the same error.
Are there any updates?
