### ISSUE TITLE
npm package index.js/index.ts import and export Client instead of SubscriptionClient

### ISSUE THREAD

**Issue by patroza** [apollographql/subscriptions-transport-ws#74]
```
import Client from './client';
import SubscriptionServer from './server';
export { SubscriptionServer, Client };
```

should be:
```
import { SubscriptionClient } from './client';
import { SubscriptionServer } from './server';
export { SubscriptionServer, Client };
```

**Comment by helfer** [comment]
@sickboy I'm not 100% sure what you mean. Could you clarify what you mean and why?

**Comment by b091** [comment]
those two imports are wrong:
```typescript
import Client from './client';
import SubscriptionServer from './server';
```

`node_modules/subscriptions-transport-ws/dist/index.d.ts:1:8`

`node_modules/subscriptions-transport-ws/dist/index.d.ts:2:8`

`TS1192: Module '"node_modules/subscriptions-transport-ws/dist/client"' has no default export.`

**Comment by Pedro-vk** [comment]
It doesn't export `addGraphQLSubscriptions`, it's the same problem.

**Comment by helfer** [comment]
Ah, I see. Could someone make a PR to fix this? We should make it backwards compatible, because as far as I understand it doesn't work right now and needs to be fixed by a patch release.

**Comment by Anthony59273** [comment]
Running into the same issue here.

**Comment by Urigo** [comment]
Fixed in `0.5.2`.

**Comment by ash0080** [comment]
@Urigo 

[!] Error: 'SubscriptionClient' is not exported by node_modules/subscriptions-transport-ws/dist/index.js

"subscriptions-transport-ws": "^0.9.2" with  rollup-plugin-node-resolver

**Comment by NeoPhi** [comment]
@ash0080 Can you confirm the last released version that this worked in?

**Comment by ash0080** [comment]
@NeoPhi 0.9.2

**Comment by frederikhors** [comment]
Same problem here: https://github.com/timhall/svelte-apollo/issues/13

How can I fix this using Rollup?
