### ISSUE TITLE
Broken links in readme 

### ISSUE THREAD

**Issue by sneakyness** [apollographql/subscriptions-transport-ws#740]
Trying to learn about subscribe/subscribe to more, but both links in the readme are broken!

> Now, when you want to use subscriptions in client side, use your ApolloClient instance, with [subscribe](https://www.apollographql.com/docs/react/api/apollo-client#ApolloClient.subscribe) or query [subscribeToMore](https://www.apollographql.com/docs/react/api/core#ObservableQuery.subscribeToMore):

**Comment by andreypopp** [comment]
Same with:
> See GitHunt-API and GitHunt-React for an example server and client integration
