### ISSUE TITLE
Wrap ws in order to support multiple websocket listeners on('upgrade')

### ISSUE THREAD

**Issue by andsens** [apollographql/subscriptions-transport-ws#751]
In order to support more than one websocket on the same server, I currently need to wrap `httpServer` so that `ws` doesn't immediately grab the socket and then passes it to `SubscriptionServer`, which in turn immediately aborts the handshake if it isn't a graphql subscription.  
Currently my code to handle that issue, looks like this:
```
const serverProxy = new EventEmitter();
server.on('listening', serverProxy.emit.bind(serverProxy));
server.on('error', serverProxy.emit.bind(serverProxy));
server.on('upgrade', (req: IncomingMessage, ...rest: any[]) => {
  if (req.url === paths.graphqlSubscriptions) {
    serverProxy.emit('upgrade', req, ...rest);
  }
});
apollo.installSubscriptionHandlers(serverProxy as Server);
```
This is rather janky. It would be nice if this handling could happen in the SubscriptionServer instead.

This means that this section: https://github.com/apollographql/subscriptions-transport-ws/blob/567fca89cb4578371877faee09e1630dcddff544/src/server.ts#L134-L135

... would look more like this ([grabbed from the examples of ws](https://github.com/websockets/ws/tree/021d4ef4e3c61c2804651c77a97e4608deebb29c#multiple-servers-sharing-a-single-https-server)):
```ts
// Init and connect WebSocket server to http
if(socketOptionsOrServer) {
    this.wsServer = new WebSocket.Server({ noServer: true });
    server.on('upgrade', function upgrade(request, socket, head) {
      const pathname = url.parse(request.url).pathname;
      if (pathname === this.pathname) {
        this.wsServer.handleUpgrade(request, socket, head, (ws) => {
          this.wsServer.emit('connection', ws, request);
        });
      }
    });
} else {
    this.wsServer = new WebSocket.Server({});
}
```

The only thing missing is the `pathname` which doesn't seem to be passed to SubscriptionServer right now.

For more see websockets/ws#1726.

**Comment by A-Tokyo** [comment]
Any news on this? 🚀

**Comment by A-Tokyo** [comment]
@andsens Can we maybe create a fork with the fix? 💪 I am not using apollo server which is why the code looks a bit confusing to me. However I highly suggest creating a fork. I am willing to maintain it if it'd be troublesome for you! ( :

**Comment by A-Tokyo** [comment]
Note for future developers not using apollo server:

This function takes in your normal http server and wraps it with @andsens solution to support more than one websocket on the same server.

```js
/**
 * Adaptor between our httpServer and gql Subscription server
 * 
 * This gets socket.io to work alongside gqls
 * In order to support more than one websocket on the same server, we need to wrap httpServer so that ws doesn't immediately grab the socket and then passes it to SubscriptionServer, which in turn immediately aborts the handshake if it isn't a graphql subscription.
 * 
 * more info: https://github.com/apollographql/subscriptions-transport-ws/issues/751
 */
const adaptServerToGqls = (server: Server, gqlsEndpoint: string = '/graphql'): Server => {
  const gqlsServerProxy = new EventEmitter();
  server.on('listening', gqlsServerProxy.emit.bind(gqlsServerProxy));
  server.on('error', gqlsServerProxy.emit.bind(gqlsServerProxy));
  server.on('upgrade', (req: IncomingMessage, ...rest: any[]) => {
    if (req.url === gqlsEndpoint) {
      gqlsServerProxy.emit('upgrade', req, ...rest);
    }
  });
  return gqlsServerProxy;
};
```

**Comment by junminstorage** [comment]
Hi please see my working sample code to solve this issue:
https://github.com/junminstorage/graphql-tutorial/blob/master/src/index.js
