### ISSUE TITLE
Change README to emphasize standalone usage rather than Apollo Client

### ISSUE THREAD

**Issue by stubailo** [apollographql/subscriptions-transport-ws#76]
This package can be used by anyone in the GraphQL community even if they aren't interested in using Apollo Client to cache their results. We should have both examples and lead with the generic one.

**Comment by Urigo** [comment]
Done in https://github.com/apollographql/subscriptions-transport-ws/commit/6a2df56ce72b93b89757162ec5386eebccaa1a74
