### ISSUE TITLE
Close websocket after unsubscribe

### ISSUE THREAD

**Issue by Gilwe** [apollographql/subscriptions-transport-ws#762]
Hi, is there a way to instruct `subscription client` to close the websocket / terminate the connection?

In my case, a subscription is set one time with certain variables but when the variables change it unsubscribes from the opened websocket and creates a new one (as expected).
The problem is that the first websocket has received a GQL_STOP (unsubscribe) message but is still open, Is there a way to tell it to close the whole websocket?

Thank you.

**Comment by timcash** [comment]
Not sure but maybe there is a way to reuse the connection without closing it.
