### ISSUE TITLE
How can I use it for query/mutation request?

### ISSUE THREAD

**Issue by zhaoyi0113** [apollographql/subscriptions-transport-ws#764]
I'd like to use one websocket connection for `query`, `mutation` and `subscription` communication. I wonder whether I can use this library for that?

**Comment by nphias** [comment]
yeah i would also appreciate some detail on this.. . i am trying to inject a "context" into a schemalink which calls the websocket API via the resolvers .... schemalink is not working for me though

**Comment by lazharichir** [comment]
@zhaoyi0113 @nphias have you guys figured this one out?! thanks!
