### ISSUE TITLE
Unsubscribe not always called: remote attacker can cause a denial of service

### ISSUE THREAD

**Issue by vieira** [apollographql/subscriptions-transport-ws#765]
Hello,

We have discovered an issue that allows a remote attacker to issue multiple `start` subscriptions without id.

In this case `opId` will be undefined:
https://github.com/apollographql/subscriptions-transport-ws/blob/567fca89cb4578371877faee09e1630dcddff544/src/server.ts#L244

Subsequent subscriptions without id will overwrite the previous subscription here:
https://github.com/apollographql/subscriptions-transport-ws/blob/567fca89cb4578371877faee09e1630dcddff544/src/server.ts#L325

And `unsubscribe` will only be called for the last one:
https://github.com/apollographql/subscriptions-transport-ws/blob/567fca89cb4578371877faee09e1630dcddff544/src/server.ts#L214-L226

We wrote a patch to work-around this issue by issuing negative `opId` for subscriptions without any id defined by the client:

```js
// added to connectionHandler, where multiple attributes of connectionContext are initialized.
connectionContext.opId = 0;

// line 244 became:
const opId = parsedMessage.id || --connectionContext.opId;

// ...
```

This does not fully resolve the issue, however, as it is still possible to issue multiple subscriptions with the same id which will also cause the problem.

Would it be acceptable to reject subscriptions without a proper id or with an already used id in the current connection?

**Comment by NeoPhi** [comment]
I maybe misunderstanding the issue but I'm not seeing where the DoS is occurring. I agree that the server should be checking that the incoming opId is defined but I don't see how the leak is happening. The server checks when getting a new start request to see if there is already an operation and unsubscribes it if present:
https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L308

Given that these `opId` are being stored in an object we would end up with a key named `undefined` if the start request was missing that value which on a subsequent request would be unsubscribed.

**Comment by NeoPhi** [comment]
In looking at this again I see that the code is not always checking before updating the operations object. As such since this reassignment happens after the resolution of a promise, someone sending many requests with the same opId could cause issues: https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L412

**Comment by vieira** [comment]
Hello @NeoPhi,

The script I was using to reproduce is indeed sending two concurrent `start` messages without `id` per each connection. It opens around 200 connections and then keeps closing around 10 while opening another 10.

I imagine that if it sent more `start` messages per connection it would be even quicker to make the server run out of memory.

**Comment by NeoPhi** [comment]
@vieira Could you check if the changes in #774 help mitigate the issue?

**Comment by vieira** [comment]
Sorry for the huge delay. It seems I am not able to reproduce it anymore with #774. Thank you.
