### ISSUE TITLE
[Question] how many actual websockets? (subscription-websocket number relation)

### ISSUE THREAD

**Issue by guykatz** [apollographql/subscriptions-transport-ws#768]
Hi; I have asked in the apollo community but no answer so maybe here I can get the heko I am looking for.
lets take the graphql spec chat room subscription example when the API lets the chat app subscribe to messages for a specific room. let assume the chat app have differnt tabs, one for each room such that I can have have a chat in 4 rooms in parallel.
this means I called subscribe (room ID) 4 times. 
should I expect 4 websocket, one per room? 1 websocket and apollo will do the dispatching internally?
is this configurable? stack implementation dependent?
any comments would help. apperantly there is no real info about this and the specification does not state this behavior.
thanks!

**Comment by danmaas** [comment]
There will be one WebSocket connection. The subscriptions are all multiplexed on that one socket.
