### ISSUE TITLE
Error TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by PunkHaz4rd** [apollographql/subscriptions-transport-ws#779]
When building/running my angular project I get this error :
ERROR in node_modules/subscriptions-transport-ws/dist/client.d.ts(73,9): error TS1086: An accessor cannot be declared in an ambient context.
I don't get it in another project which also uses this lib the only difference is the failing project uses the libs "aws-amplify" & "aws-amplify-angular"
Is this it ? Is there a fix where I get to keep either libs ?

**Comment by evandavey** [comment]
I had a similar problem, upgrading typescript to 3.9.7 made this go away.

**Comment by malikmaani** [comment]
i have latest typescript version but i am still getting same error
