### ISSUE TITLE
Client-side packaging changed in 0.5.2 relative to 0.5.1

### ISSUE THREAD

**Issue by vlasenko** [apollographql/subscriptions-transport-ws#79]
Please see this issue:
https://github.com/sysgears/apollo-fullstack-starter-kit/issues/41

My solution was to force downgrade to 0.5.1. I think something is wrong with "browser" client-side package in 0.5.2

**Comment by vlasenko** [comment]
Seems module format for client-side bundle has changed from CommonJS in 0.5.1 to AMD in 0.5.2 by Pull Request:
https://github.com/apollographql/subscriptions-transport-ws/pull/77

**Comment by Urigo** [comment]
Fixed in `0.5.3`. Thanks @schrepfler .

**Comment by vlasenko** [comment]
@Urigo The same problem has happened with `0.6.0`. Browser bundle is exported as global var, whereas in 0.5.x it was exported as CommonJS module, is it intended?
