### ISSUE TITLE
abstract SubscriptionClient module to support other backend setups

### ISSUE THREAD

**Issue by willdeuschle** [apollographql/subscriptions-transport-ws#80]
Would the maintainers be open to a PR that makes the SubscriptionClient module more flexible when using an alternative WebSocket implementation? My use case is as follows: I’ve written a couple of modules for my non-JS backend to handle subscriptions for graphql (they are comparable to the graphql-subscriptions module and graphql-transport-ws server module). Fortunately, the SubscriptionClient works nearly perfectly with this setup, save a couple of API inconsistencies in the WebSocket protocol. I think offering the client-side calling code a few more hooks to modify the SubscriptionClient would make it more compatible with other backend setups.

The problem I’m experiencing is that making a WebSocket connection with my backend requires a slightly different flow than is supported by the SubscriptionClient, I first have to connect via long-polling with socketio, which then immediately gets upgraded to a WebSocket connection. However, the `client` (the eventual WebSocket connection) does not actually handle the `onopen` or `readyState` steps - that is the responsibility of the socket manager, and after both of those checkpoints are passed, all control can be handed over to the WebSocket client.

So what I’m proposing is adding an optional config parameter in the case of using a custom WebSocket implementation, that would be responsible for handling the `readyState` and `onopen` checks. If the parameter is passed via the calling code, then the manager gets used in those places, and if it’s not, then the SubscriptionClient can simply behave as it does now.

I have a working version of this based on overriding the `connect` and `sendMessage` methods on the SubscriptionClient prototype, but it feels like this should just be an optional parameter to the SubscriptionClient constructor since none of the business logic is actually changed outside of using the manager to set up the connection before handing off control to the web socket.

**Comment by Urigo** [comment]
@willdeuschle I would prefer that special cases to be handled outside of the library but maybe we can think of a nice way to do that.
It will be easier to comment on a PR, so if you are willing to send a PR with your proposed changes, I would love to go through it and comment upon.
Thank you!

**Comment by khankuan** [comment]
Hi, I have a similar question. Would I be able to use a 3rd party notification service like pubnub? I saw that `graphql-subscriptions` implements a publish/subscribe/unsubscribe interface to use a different event emitter. On `subscriptions-transport-ws`, ws client is required. Has anyone tried using something besides native websockets?

**Comment by Urigo** [comment]
We made some progress in the recent commits, and changed the socket protocol to support more generic implementation. 
Would love to see more PRs and discussion about how to make this package more compatible with use cases that you need.

**Comment by lorensr** [comment]
Here's a library for using Fanout: https://github.com/fanout/fanout-graphql-tools
