### ISSUE TITLE
Mutations never complete

### ISSUE THREAD

**Issue by mritzerfeld** [apollographql/subscriptions-transport-ws#800]
I've started using mutations with the useMutation hook from the latest Apollo client (v3). While regular queries over Websocket work without any problems, mutations never return a result, although the server completes the request successfully and the response is visible in Safari's web inspector.

When I changed Apollo to using HTTP for mutations, they worked as intended. After some investigation, it looks like SubscriptionClient's request function does not call the complete handler of the observer, only next. This leads to the promise in Apollo Client's QueryManager.mutate function never getting resolved.

Adding a call to complete the observer solved the issue:

```
if (observer.next) {
    observer.next(result);
    
    if (observer.complete) {
        observer.complete();
    }
}
```

**Comment by zbyte64** [comment]
I have observed this bug as well.
