### ISSUE TITLE
Memory leak when executing a query or mutation

### ISSUE THREAD

**Issue by fredli74** [apollographql/subscriptions-transport-ws#805]
Hi,

I've run into a memory leak problem in my project, that seems to be related to the `connectionContext.operations` retaining all previous queries and mutations until the WebSocket connection is closed.

I think this problem surfaced because of the recent change in client behavior not sending GQL_STOP messages when they receive a GQL_COMPLETE message.

Looking at the server.ts implementation, it looks like all operations - not explicitly unsubscribed - will remain in memory. There seems to be no logic implemented surrounding completed operations.

**Comment by fredli74** [comment]
Been running the previous version that sends GQL_STOP messages and it removed all memory leaks. There is a quite clear security vulnerability in the fact that the client can control ther memory usage on the server.

* If you keep the connection open and do not send GQL_STOP messages, the server will run out of memory. (I had connections with over 10k operations kept in the operations array.)

You do not even have to do it fast. If you poll 50kb of data every 10 seconds you'll most likely fly under the radar of a rate-limiter, and still end up using over 400MB of server memory after 24 hours, for just one connection.

My guess is that this happens if you create a client that keeps starting new subscriptions as well?

**Comment by onhate** [comment]
The server is already sending GQL_COMPLETE after the operation is finished, and according to the protocol "Server sends this message (GQL_COMPLETE) to indicate that a GraphQL operation is done, and no more data will arrive for the specific operation."

https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_complete

In theory is just a matter of adding unsubscribe after sending the GQL_COMPLETE

https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L389

```
 this.unsubscribe(connectionContext, opId);
```

**Comment by onhate** [comment]
https://github.com/apollographql/subscriptions-transport-ws/pull/809
