### ISSUE TITLE
Memory leak issue with multiple connections

### ISSUE THREAD

**Issue by kundkingan** [apollographql/subscriptions-transport-ws#844]
Hi!

We are running into memory leaks when having multiple websocket connections open. I can see there is already PR's for this issue

https://github.com/apollographql/subscriptions-transport-ws/pull/836 
https://github.com/apollographql/subscriptions-transport-ws/pull/809

Is someone taking any responsibility for this issue? 

There are like 1.6m weekly downloads of this package....

@helfer 
@amandajliu 
@stubailo 
@DxCx 
@kamilkisiela 
@gluck 
@NeoPhi 
@lfittl

**Comment by NeoPhi** [comment]
As noted on the main page for this repo:

The `subscriptions-transport-ws` library is not being actively maintained. It is recommended that you use the [graphql-ws](https://github.com/enisdenjo/graphql-ws) library instead. For details read the [GraphQL over WebSockets](https://the-guild.dev/blog/graphql-over-websockets) announcement.
