### ISSUE TITLE
INIT_FAIL message appears to not be properly formatted

### ISSUE THREAD

**Issue by hmaurer** [apollographql/subscriptions-transport-ws#88]
Hello,

I am completely new to this project so this may just be the fruit of my incompetence, but it would appear that the `SubscriptionClient` expect an `INIT_FAIL` message to contain a `payload` field, c.f. https://github.com/apollographql/subscriptions-transport-ws/blob/7dba040578c5964975a90cfdb99a556b52823455/src/client.ts#L287. 

However, it seems that the server sets the `error` property directly on the message and not under a `payload` field, c.f. https://github.com/apollographql/subscriptions-transport-ws/blob/7dba040578c5964975a90cfdb99a556b52823455/src/server.ts#L161

This lead to an error when I tried to use `connectionCallback`.

Furthermore, upon rejection of the connection and if `connectionCallback` was not specified (to avoid the error), the client kept trying to reconnect without any backoff delay or limit on the number of reconnects.

**Comment by hmaurer** [comment]
https://github.com/apollographql/subscriptions-transport-ws/pull/53
@Urigo you might have an idea about this! :)

**Comment by hmaurer** [comment]
@Urigo The PR is quite instructive! Why was `setTimeout` required?

**Comment by Urigo** [comment]
@hmaurer https://github.com/apollographql/subscriptions-transport-ws/blob/fd0fcac9e2e2bde9957c17f0aaf6ea23cd2104cf/src/server.ts#L299-L300
