### ISSUE TITLE
onConnected and onReconnected event do not fire

### ISSUE THREAD

**Issue by keithhackbarth** [apollographql/subscriptions-transport-ws#880]
In our React code, we see logging for `onConnecting`, `onReconnecting` and `onDisconnected` events but not `onConnected` and `onReconnected`

It appears that a few people have complained about this issue in various Stackoverflow threads but have not seen it listed here.

subscription-transport-ws: 0.9.19
python graphene blackened

client code

```javascript
export const addListeners = (subscriptionClient, onConnect, onDisconnect) => {

    subscriptionClient.onConnecting(() => {
        Log.info('connecting to websocket...');
    });

    subscriptionClient.onConnected(() => {
        Log.info('connected to websocket!');
    });

    subscriptionClient.onReconnecting(() => {
        Log.info('reconnecting to websocket...');
    });

    subscriptionClient.onReconnected(() => {
        Log.info('reconnected to websocket');
    });

    subscriptionClient.onDisconnected(() => {
        Log.warn('disconnected from websocket');
    });
};
```

**Comment by Cerberus** [comment]
Normally, `onConnected` & `onReconnected` will be fired after the server acknowledges with `{ type: 'connection_ack' }`

@keithhackbarth Could you please confirm on dev-tools ? It should display like this.

![ss](https://user-images.githubusercontent.com/9087409/127445567-e8146f66-7727-4de5-84e5-a57aba7979d1.png)
