### ISSUE TITLE
"Cannot read property 'subscribe' of undefined"

### ISSUE THREAD

**Issue by HammadUllahKhan12** [apollographql/subscriptions-transport-ws#884]
When I call the subscription in grap ql playground. it gives "Cannot read property 'subscribe' of undefined". I configured all the things right but did not know how to resolve this error.

![image](https://user-images.githubusercontent.com/48718737/124123648-fa096e80-da90-11eb-8eb0-636f42bb6c3a.png)

**Comment by MichalLytek** [comment]
I have an similar error `Cannot read property 'resolve' of undefined` after upgrading to Apollo Server v3, following the docs 🤔

**Comment by HammadUllahKhan12** [comment]
@MichalLytek Can you share the screenshot of pubsub implementation file and subscription file.

**Comment by HammadUllahKhan12** [comment]
I fixed the issue if any body need help. Please mention on this ticket.
