### ISSUE TITLE
Next.js + Apollo Server 3.0 + Subscription

### ISSUE THREAD

**Issue by nenjamin2405** [apollographql/subscriptions-transport-ws#888]
Hi guys, I successfully integrated Apollo Server 3.0 into Next.js route called /api by using below code snippet

```javascript
import { ApolloServer } from "apollo-server-micro"; // NOSONAR
import { typeDefs } from "../../graphql/schema";
import { resolvers } from "../../graphql/resolvers";

import Cors from "micro-cors";
import { API_URL } from "../../constants/common";

const cors = Cors();

const apolloServer = new ApolloServer({
  resolvers,
  typeDefs,
  introspection: true,
});

// @ts-ignore
await apolloServer.start();

export default cors(async (req, res) => {
  if (req.method === "OPTIONS") {
    res.end();
    return false;
  }

  return apolloServer.createHandler({ path: API_URL })(req, res);
});

export const config = {
  api: {
    bodyParser: false,
  },
};

```

Right now I want to integrate the Subscription functionality into this api, but I cannot get it working. 

This stackoverflow [topic](https://stackoverflow.com/questions/62371284/apollo-server-with-subscriptions-used-inside-next-js-api-routes-websockets-trou) is outdated, and the apollo-server-micro also removed the integrated subscription in the Apollo Server instance. 

If I tried to follow the example from Apollo [here](https://www.apollographql.com/docs/apollo-server/data/subscriptions/), The last step requires me to run a httpServer by following code:

```javascript
(async function () {
  const app = express();

  const httpServer = createServer(app);

  const schema = makeExecutableSchema({
    typeDefs,
    resolvers,
  });

  const server = new ApolloServer({
    schema,
  });
  await server.start();
  server.applyMiddleware({ app });

  SubscriptionServer.create(
    { schema, execute, subscribe },
    { server: httpServer, path: server.graphqlPath }
  );

  const PORT = 4000;
  httpServer.listen(PORT, () =>
    console.log(`Server is now running on http://localhost:${PORT}/graphql`)
  );
})();
```

Looking at the code snippet above, I have no idea how to convert it into Next.js's requestHandler.

In conclusion, do you guys have any suggestion of how to enable Subscription Server in Next.js route using Apollo Server 3.0, because we already got this working in the Apollo Server 2.0.

Many thanks!

**Comment by AhmedElywa** [comment]
Looking for the same thing.
@nenjamin2405 do you get any way to do Subscription in nextjs api

**Comment by glasser** [comment]
As a note, I don't recommend the use of apollo-server-micro in Next.JS (or at all unless you are specifically motivated to directly use micro for some reason). I recognize that the official Next.JS examples suggest its use; I have an open PR to convert them to apollo-server-express. https://github.com/vercel/next.js/pull/30082

We don't have much expertise in Next.JS here and subscriptions aren't built in to AS3, so I'm going to close this issue. However it still can be a useful place for other folks trying to combine Next.JS and subscription to figure out how to get it working.

I look forward to a day where Apollo Server has first-class subscription support; perhaps 2022 is that year.
