### ISSUE TITLE
SUBSCRIPTION_READY event

### ISSUE THREAD

**Issue by deanius** [apollographql/subscriptions-transport-ws#9]
This is just a proposal, but wouldn't it be good to be able to distinguish between the past items recieved on a subscription and the ones that follow the moment of the subscription? A SUBSCRIPTION_READY event emitted between SUBSCRIPTION_DATA events could serve that purpose as it does in DDP.

**Comment by stubailo** [comment]
Subscriptions in GraphQL don't usually send existing data, so I don't think this event would be a thing.

**Comment by deanius** [comment]
What else do you need for subscriptions @stubailo ?
